### ISSUE TITLE
Best strategy for read-only local caching

### ISSUE THREAD

**Issue by rpander93** [forcedotcom/SalesforceMobileSDK-ReactNative#104]
Hi,

I'm developing an app that should be able to show the most recent fetched records while being offline. Synchronization after becoming online again is explicitly not a goal. All mutate functionality will be disabled once the connection is lost.

My strategy so far was to fetch records whilst being online and storing them in SmartStore. Then, if the app loses connectivity, I want to query SmartStore rather than Salesforce and return the cached data. Once connection is restored, I clear the cache and refresh the records on demand:

```
    public findAllCurrentlyOpen = (): Promise<Task[]> => {
        const queryString = SOQL`
            SELECT
                Id,
                Subject,
                Status
            FROM
                Task
            LIMIT
                25
        `;

        return new Promise((resolve, reject) => {
            if (this.connectivityStatus.isConnected()) {
                Connection.executeQuery(queryString)     // WRAPPER AROUND net.query TO provide LOGGING
                    .then(response => {
                        smartstore.clearSoup(false, this.tasksSoupName, () => {
                            smartstore.upsertSoupEntries(false, this.tasksSoupName, response, () => {
                                resolve(this.__hydrateCurrentlyOpenFromObject(response));
                            });
                        });
                    });

                return;
            }

            const querySpec = smartstore.buildSmartQuerySpec(SOQL`
                SELECT
                    {${this.tasksSoupName}:Id},
                    {${this.tasksSoupName}:Subject},
                    {${this.tasksSoupName}:Status}
                FROM
                    {${this.tasksSoupName}}
            `);

            smartstore.runSmartQuery(false, querySpec, (cursor) => {
                traverseCursor([], cursor, 0, resolve, reject);
            });
        });
    };
}
```

However, I now find that net.query() returns an array of objects, whilst smartstore.runSmartQuery() returns an array of arrays. Is this behaviour configurable? Now I have to write two mapper functions depending on whether I query online or from SmartStore, which is not very developer-friendly.

Also as a more general question, is this even the best approach? Should I instead us a different strategy to get at what I want?

Regards

**Comment by rpander93** [comment]
Anyone has some insight?

**Comment by wmathurin** [comment]
Could you post your question on our [google+ community](https://plus.google.com/communities/114225252149514546445)? Github issues are meant for bugs / enhancements requests.

**Comment by rpander93** [comment]
Okay, wasn't aware of the existence of the Community. Thanks
