### ISSUE TITLE
Crash during sync due to known React Native issue

### ISSUE THREAD

**Issue by socialsuiteDan** [forcedotcom/SalesforceMobileSDK-ReactNative#115]
We are experiencing intermittent crashes while using SmartSync on Android, the native side error logs show the exception discussed here: https://github.com/facebook/react-native/issues/18292 

The issue is apparently resolved in React Native 0.57.5, will the next SDK release include a version update to a new enough version to resolve this? Looking at the current dev branch it still points to 0.56.1

**Comment by wmathurin** [comment]
With every version of the Mobile SDK, we try to update dependent library to the latest stable version available. There is a good chance Mobile SDK 7.1 will support React Native 0.59.

**Comment by socialsuiteDan** [comment]
I'm looking at the React Native template for the new 7.1 SDK release, it still points to 0.56.1. This is going to become a serious issue in the next few months, Android apps are required to include a 64-bit binary by 1 August but in order to do that with React Native it requires version 0.59. Can we expect a 7.2 release before that deadline?

**Comment by wmathurin** [comment]
The PR to move to 0.59 is in (see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/131) and it will be part of our soon to be released next version (7.2).
