### ISSUE TITLE
sendRequest reject callback

### ISSUE THREAD

**Issue by rpander93** [forcedotcom/SalesforceMobileSDK-ReactNative#116]
The API im working with sends a 500 response when request validation of input fails, as expected. I want to show the error to the user. However, the error message of the rejected promise contains a string rather than the response of the API:

> 2019-03-28 13:16:01.804402+0100 Medewerkers[18372:270396] SFNetReactBridge.sendRequest failed: {"message":"sendRequest failedError Domain=https://xxxxxxxxx.my.salesforce.com/services/apexrest/xxxxxx/xxxxx/v1.0/ Code=500 \"(null)\" UserInfo={error={\n    message = \"You cannot select this store.\";\n    statusCode = 500;\n}, cases=null}"}

I want to get the actual object sent by the API (the UserInfo), and not the other stuff. Can this be done? Currently, there is no way of knowing what error the API sent back without having to parse the message and grabbing the UserInfo out if it in some wacky way.

**Comment by wmathurin** [comment]
Right now, parsing the message is the only way.
(Flagging issue as enhancement request).

**Comment by wmathurin** [comment]
Finally enhanced in our next release (8.2). Se https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/189
