### ISSUE TITLE
Can we use sendRequest for community guest user 

### ISSUE THREAD

**Issue by bryonCatalyst** [forcedotcom/SalesforceMobileSDK-ReactNative#118]
I'm currently using the react native SDK v6.2 and was planning on switching all of our calls to Apex REST endpoints to use sendRequest( ) rather than using plain old javascript fetch( ) calls because doing so handles refresh tokens nicely for logged in users.

The problem I'm running into is that requests don't seem to return if the user is **not authenticated**.  We don't force the user to signup / login in our app and so we need to be able to let guests create requests as the Community guest user.  Is this possible via the sendRequest in the sdk?  I'd like to use the sdk for all salesforce calls if possible.  

Do you have any recommendations?   Thanks for your help!

**Comment by wmathurin** [comment]
Support for unauthenticated calls from react native is coming in our next version of the mobile SDK (7.1). See: https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/112 and https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/117

**Comment by bryonCatalyst** [comment]
Thanks for the quick reply - I think I'll stick with javaScript fetch( ) requests for all requests that don't require authentication and will use sendRequest( ) for logged in users only.  Once 7.1 is available, I'll migrate the remaining fetch( ) calls to also use the sdk.  Does that sound reasonable to you?

**Comment by wmathurin** [comment]
That sounds reasonable.
