### ISSUE TITLE
Documentation/example code for ParentChildSyncTarget usage

### ISSUE THREAD

**Issue by socialsuiteDan** [forcedotcom/SalesforceMobileSDK-ReactNative#119]
Would it be possible to get some documentation or example code for how to use the parent/child sync up & down targets in React Native? We have around 25 different object types that need to be synced down and 8 of those are synced back up again, most of them are hierarchical so it would let us cut the number of sync calls almost in half if we can handle two object types per sync instead of just one. It was mentioned in the closed issue #36 but that was back in 2017 and i can't find anything in the current SDK developer guide.

**Comment by wmathurin** [comment]
@rwhitley do we have an example published somewhere?

**Comment by wmathurin** [comment]
The documentation has been improved. See https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_sync_related.htm
