### ISSUE TITLE
Migration from GCM to FCM 

### ISSUE THREAD

**Issue by iServiceTrucks** [forcedotcom/SalesforceMobileSDK-ReactNative#122]
We have a react native app with salesforce mobile sdk 6.2.0 and firebase project. GCM is deprecated and will be removed by May 29th. 
Do we need to make any changes in our code or migrate to the latest versions of Mobile SDK so that the end users will continue receive notifications after May 29th 2019.

**Comment by bhariharan** [comment]
Please upgrade to `Mobile SDK 7.0.0`. It has support for FCM.
