### ISSUE TITLE
support for RN 0.59

### ISSUE THREAD

**Issue by riquier** [forcedotcom/SalesforceMobileSDK-ReactNative#127]
Is there a currently timeline for supporting React Native 0.59?

**Comment by wmathurin** [comment]
Should be in Mobile SDK 7.2 scheduled for next month #safeharbor

**Comment by riquier** [comment]
Thanks for clarifying, that's will be very handy

**Comment by prasadrodepatil** [comment]
@wmathurin That's great news! No support for the latest version of React Native is holding us back from using Salesforce Mobile SDK in our project. Going forward can we expect that Salesforce Mobile SDK will keep supporting fairly recent versions of React Native as opposed to year old versions. I am sure there must be a lot of challenges keeping up with the React Native releases but if we have to use a year old version of React Native just to use Salesforce Mobile SDK, that is a bit discouraging for the mobile app developers.

**Comment by wmathurin** [comment]
PR is in (see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/131). Will be in Mobile SDK 7.2.
