### ISSUE TITLE
compileDebugJavaWithJavac error when using react-native-image-picker

### ISSUE THREAD

**Issue by rahulsahu47** [forcedotcom/SalesforceMobileSDK-ReactNative#129]
Hi,
Trying to install react-native-image-picker in a forcereact project.
It always throw error: Task :react-native-image-picker:compileDebugJavaWithJavac FAILED

react: 16.4.1
react-native: 0.56.1
react-native-force: https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v7.1.0
react-native-image-picker: 0.28.1

**Comment by wmathurin** [comment]
You need to following [React Native Image Picker manual installation steps](https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md#android-1).
