### ISSUE TITLE
Android components? or am I missing something?

### ISSUE THREAD

**Issue by mrTuomoK** [forcedotcom/SalesforceMobileSDK-ReactNative#130]
Hi. I'm about to integrate SalesForce to our RN-based app and was just wondering where the Android files are (ios-bridging files are here but what about Android?) or am I missing something..?

**Comment by wmathurin** [comment]
Please follow our step by step instructions [here](https://trailhead.salesforce.com/en/content/learn/modules/mobile_sdk_react_native).
