### ISSUE TITLE
SDK is not Type Safe and fails to catch errors with JSON.parse(result)

### ISSUE THREAD

**Issue by JimBTek** [forcedotcom/SalesforceMobileSDK-ReactNative#132]
1. Version of Mobile SDK Used:  7.1.2
3. OS Version: iOS 12.3.1
4. Device: iPad Mini 5
5. Steps to reproduce:
It seems like it happens when the data in the SmartStore is somehow incomplete, like an interrupted sync down over cell connection. We also have a lot of special characters in our data including:
  , . '  " / % &

We have a solution that we will follow up with a Pull Request to see if it is helpful.

6. Actual behavior:
App Crashes
7. Expected Behavior:
8. Error Log:

We get this error in AppCenter occasionally when it happens for users, but is hard to reproduce. 

```_hidden#4238_
__hidden#4248_, line 132
SIGABRT: Unhandled JS Exception: JSON Parse error: Unexpected token '}'

**Comment by wmathurin** [comment]
Thanks for your PR, however, we need to figure out how one ends up with incomplete JSON in SmartStore. If you had reported the bug for 7.0, I would have said that you run into that bug: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2825/commits/560ed9a915ff2ed0be4f2f4624f8961e960eb833

**Comment by JimBTek** [comment]
@wmathurin Yeah, it doesn't fully solve the mystery.  We will continue to monitor. We have 20 users now and are rolling out to another 50 or so over the next month or so. Unfortunately I was able to test the same records/data on a 2nd device and not reproduce the crashes. They were on iOS 12.2 and I am on 12.3.1 and we are working to upgrade all the users to 12.3.1

**Comment by wmathurin** [comment]
Are you using external storage? (see https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_external_registration.htm).

**Comment by JimBTek** [comment]
@wmathurin no external storage.  It only happens very rarely/randomly. It has not happened in a couple weeks despite ~20 active daily users.

We have discovered one way to try and replicate it is if the session expires and then you try and sync. We are using a Connected App we defined in production and added the keys to the app to prevent expiring the session/auth.  Also, we are downloading  >100,000 records in 10 objects, and users tend to have 200-350 MB of data locally.  We also noticed some oddities around things like logging out the user, it would crash sometimes. Even one time logging in, it took the user to the webkit mobile version of Salesforce instead of rendering our app. Each iPad is used by one user, and we do not do any user switching with the app.

Also I was able to dig up all the thread stack traces:

## LAST EXCEPTION BACKTRACE
CoreFoundation
__exceptionPreprocess
libobjc.A.dylib
objc_exception_throw
Techapp
_hidden#4238_ __hidden#4248_:132
Techapp
_hidden#6428_ __hidden#6449_:58
CoreFoundation
__invoking___
CoreFoundation
-[NSInvocation invoke]
CoreFoundation
-[NSInvocation invokeWithTarget:]
Techapp
_hidden#8015_ __hidden#8041_:544
Techapp
_hidden#8347_ __hidden#8354_:99
Techapp
_hidden#8345_ __hidden#8354_:71
libdispatch.dylib
_dispatch_call_block_and_release
libdispatch.dylib
_dispatch_client_callout
libdispatch.dylib
_dispatch_lane_serial_drain
libdispatch.dylib
_dispatch_lane_invoke
libdispatch.dylib
_dispatch_workloop_worker_thread
libsystem_pthread.dylib
_pthread_wqthread
libsystem_pthread.dylib
start_wqthread

## MAIN THREAD
libsystem_kernel.dylib
mach_msg_trap
libdispatch.dylib
_dispatch_mach_send_and_wait_for_reply
libdispatch.dylib
dispatch_mach_send_with_result_and_wait_for_reply
libxpc.dylib
xpc_connection_send_message_with_reply_sync
Security
-[TKTokenRefCtkd transactOperation:objectID:input:output:error:]
Security
-[TKTokenRefCtkd keyOperation:onObject:algorithm:mode:in1:in2:error:]
Security
TKTokenCopyOperationResult
Security
__SecCTKKeyCopyOperationResult_block_invoke
Security
SecItemAuthDo
Security
SecCTKKeyCopyOperationResult
Security
SecKeyRunAlgorithmAndCopyResult
Security
SecKeyECDHCopyX963Result
Security
SecKeyRunAlgorithmAndCopyResult
Security
SecKeyECIESKeyExchangeKDFX963CopyResult
Security
SecKeyECIESCopyDecryptedData
Security
SecKeyRunAlgorithmAndCopyResult
Security
SecKeyCreateDecryptedDataWithParameters
Techapp
_hidden#24686_ __hidden#24699_:354
Techapp
_hidden#23030_ __hidden#23036_:103
Techapp
_hidden#23010_ __hidden#23021_:102
Techapp
_hidden#23006_ __hidden#23021_:51
Techapp
_hidden#23005_ __hidden#23021_:35
Techapp
_hidden#23041_ __hidden#23066_:69
Techapp
_hidden#23569_ __hidden#23575_:287
Techapp
_hidden#23554_ __hidden#23575_:74
Techapp
_hidden#25089_ __hidden#25140_:602
Techapp
_hidden#26527_ __hidden#26683_:1281
Techapp
_hidden#26526_ __hidden#26683_:1272
Techapp
_hidden#26394_ __hidden#26683_:348
Techapp
_hidden#26393_ __hidden#26683_:323
Techapp
_hidden#23796_ __hidden#23822_:0
Techapp
_hidden#26392_ __hidden#26683_:321
Techapp
_hidden#26391_ __hidden#26683_:302
Techapp
_hidden#21377_ __hidden#21402_:55
libdispatch.dylib
_dispatch_call_block_and_release
libdispatch.dylib
_dispatch_client_callout
libdispatch.dylib
_dispatch_main_queue_callback_4CF
CoreFoundation
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
GraphicsServices
GSEventRunModal
UIKitCore
UIApplicationMain
Techapp
main __hidden#66_:30
libdyld.dylib
start

## BACKGROUND THREAD 1
libsystem_kernel.dylib
mach_msg_trap
CoreFoundation
__CFRunLoopServiceMachPort
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
Foundation
-[NSRunLoop(NSRunLoop) runMode:beforeDate:]
Foundation
-[NSRunLoop(NSRunLoop) runUntilDate:]
UIKitCore
-[UIEventFetcher threadMain]
Foundation
-[NSThread main]
Foundation
__NSThread__start__
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 2
libsystem_kernel.dylib
mach_msg_trap
Techapp
_hidden#34436_
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 3
libsystem_kernel.dylib
mach_msg_trap
CoreFoundation
__CFRunLoopServiceMachPort
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
Techapp
_hidden#5505_ __hidden#5821_:245
Foundation
-[NSThread main]
Foundation
__NSThread__start__
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 4
libsystem_kernel.dylib
__psynch_cvwait
libc++.1.dylib
std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >)
JavaScriptCore
std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
JavaScriptCore
std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<bmalloc::Mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<bmalloc::Mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
JavaScriptCore
bmalloc::Scavenger::threadRunLoop()
JavaScriptCore
bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*)
JavaScriptCore
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*)
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 5
libsystem_kernel.dylib
mach_msg_trap
CoreFoundation
__CFRunLoopServiceMachPort
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
WebCore
RunWebThread(void*)
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 6
libsystem_kernel.dylib
mach_msg_trap
CoreFoundation
__CFRunLoopServiceMachPort
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
CFNetwork
-[__CoreSchedulingSetRunnable runForever]
Foundation
-[NSThread main]
Foundation
__NSThread__start__
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 7
libsystem_kernel.dylib
__workq_kernreturn
libsystem_pthread.dylib
start_wqthread

## BACKGROUND THREAD 9
libsystem_kernel.dylib
__psynch_cvwait
JavaScriptCore
WTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)
JavaScriptCore
WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()
JavaScriptCore
WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)
JavaScriptCore
WTF::wtfThreadEntryPoint(void*)
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 10
libsystem_kernel.dylib
__psynch_cvwait
JavaScriptCore
WTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)
JavaScriptCore
WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()
JavaScriptCore
WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)
JavaScriptCore
WTF::wtfThreadEntryPoint(void*)
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 11
libsystem_kernel.dylib
__psynch_cvwait
JavaScriptCore
WTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)
JavaScriptCore
WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()
JavaScriptCore
WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)
JavaScriptCore
WTF::wtfThreadEntryPoint(void*)
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 12
libsystem_kernel.dylib
__psynch_cvwait
JavaScriptCore
WTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)
JavaScriptCore
WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()
JavaScriptCore
WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)
JavaScriptCore
WTF::wtfThreadEntryPoint(void*)
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 13
libsystem_kernel.dylib
__psynch_cvwait
JavaScriptCore
WTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)
JavaScriptCore
WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()
JavaScriptCore
WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)
JavaScriptCore
WTF::wtfThreadEntryPoint(void*)
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 14
libsystem_kernel.dylib
__psynch_cvwait
JavaScriptCore
WTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime)
JavaScriptCore
WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)
JavaScriptCore
WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call()
JavaScriptCore
WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)
JavaScriptCore
WTF::wtfThreadEntryPoint(void*)
libsystem_pthread.dylib
_pthread_body
libsystem_pthread.dylib
_pthread_start
libsystem_pthread.dylib
thread_start

## BACKGROUND THREAD 15
libsystem_kernel.dylib
__workq_kernreturn
libsystem_pthread.dylib
start_wqthread

## BACKGROUND THREAD 16
libsystem_kernel.dylib
__workq_kernreturn
libsystem_pthread.dylib
start_wqthread

## BACKGROUND THREAD 17
libsystem_kernel.dylib
__workq_kernreturn
libsystem_pthread.dylib
start_wqthread

**Comment by wmathurin** [comment]
We have systematically tried to reproduce corruption issues and addressed problems we found.
For more information: https://github.com/wmathurin/CorruptionTester
