### ISSUE TITLE
How to use SmartStore in react-native App not created using forcereact

### ISSUE THREAD

**Issue by Vigneshlakshminarayanan** [forcedotcom/SalesforceMobileSDK-ReactNative#144]
Hi, 

I wanted to leverage the SmartStore functionality in my react native App to store data and retrieve . The project was **not** created using `Salesforce Mobile SDK` or `forcereact`. This is a simple react-native App consuming data via Heroku, and I want to store data in offline using `SmartStore`.

Is there `npm` available to install the `smartstore` to my react-native App?

Thanks

**Comment by wmathurin** [comment]
Apps generated with `forcereact` automatically get `SmartStore` and `SmartSync`.
To see them in action, you can generate an application based on the `SmartSyncExplorerReactNative` template by doing:
```shell
forcereact createwithtemplate --templaterepouri=https://github.com/forcedotcom/SalesforceMobileSDK-Templates/SmartSyncExplorerReactNative#v7.3.0
```

**Comment by Vigneshlakshminarayanan** [comment]
@wmathurin : Thanks for your reply. This is an existing App that was **not** created using `forcereact`. Can I still include the `SmartStore` capability to our app just to store and retrieve data for offline ?

**Comment by wmathurin** [comment]
Yes you can.
Are you building an application for iOS and/or Android?
On iOS, are you consuming your dependencies using cocoapods?
If you do, you could change your pod file to be something like that: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/SmartSyncExplorerReactNative/ios/Podfile

**Comment by Vigneshlakshminarayanan** [comment]
This is a `react-native` App to target `iOS` an `Android`.. I am consuming the REST APIs from my `react-native` module and trying to store it in `SmartStore`

**Comment by wmathurin** [comment]
I meant how are you bringing Mobile SDK libs into your app. Are you using submodules? 
I recommend you use cocoapods to consume dependencies. Then it will be trivial to add SmartStore (see podfile above).

**Comment by Vigneshlakshminarayanan** [comment]
It worked .. thanks.. added the dependencies as submodules and it worked..
