### ISSUE TITLE
oauth.getAuthCredentials is not getting called 

### ISSUE THREAD

**Issue by AlfBohra** [forcedotcom/SalesforceMobileSDK-ReactNative#147]
**Package.json**
"@react-native-community/async-storage": "^1.6.2",
"@react-native-community/netinfo": "^4.4.0",
"@react-native-community/push-notification-ios": "^1.0.2",
"@redux-offline/redux-offline": "^2.5.2-native.1",
"@sentry/react-native": "^1.0.9",
"axios": "^0.18.0",
"core-js": "^3.3.2",
"deprecated-react-native-listview": "0.0.6",
"lottie-ios": "^3.1.3",
"lottie-react-native": "^3.2.1",
"moment": "^2.22.2",
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-config": "git+https://github.com/luggit/react-native-config.git",
"react-native-cookies": "^3.3.0",
"react-native-device-info": "^0.24.3",
"react-native-force": "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v7.3.0",
"react-native-fs": "^2.13.2"

**My code:**
App.js file
const **authenticate** = () => new Promise((resolve) => {
try{
console.log("this is getting logged");
//  it calls **getAuthCredentials** in **react.force.oauth.js** and never returns
**oauth.getAuthCredentials**((res) => { 
   // never logged
   console.log("AUTHENTICATING FROM ROOT APP CONTROLLER");
});}
.catch (err){}

export async function bootstrap() {
console.log("calling authenticate"); // getting logged
await **authenticate**(); // call to authenticate
console.log("called authenticate"); // not getting logged
}

**File: react.force.oauth.js** 

import { NativeModules } from 'react-native';
const { SalesforceOauthReactBridge, SFOauthReactBridge } = NativeModules;
import {exec as forceExec} from './react.force.common';

const **exec** = (successCB, errorCB, methodName, args) => {
    forceExec("SFOauthReactBridge", "SalesforceOauthReactBridge", SFOauthReactBridge, 
       SalesforceOauthReactBridge, successCB, errorCB, methodName, args);
};
export const **getAuthCredentials** = (success, fail) => {
       console.log("oauth"); // getting logged
        exec(success, fail, "getAuthCredentials", {});
};

I am migrating my proiect to RN 0.60.5 and SFSDK ios 7.3.0. I am stuck on this issue, please provide assistance.
--

**Comment by bhariharan** [comment]
@AlfBohra How did you create your app? Could you use `forcereact` to generate your app and move your assets over to the generated app?

**Comment by AlfBohra** [comment]
The issue is resolved. 
Solution: include SalesforceReact in podfile:
pod 'SalesforceReact', :path => '../node_modules/react-native-force/SalesforceReact.podspec'
