### ISSUE TITLE
Expo usage

### ISSUE THREAD

**Issue by elie222** [forcedotcom/SalesforceMobileSDK-ReactNative#149]
We have an Expo project that we need to add Salesforce auth too. We can either eject from Expo and use this package, or use the HTML5 package and stay on Expo?

Which is the recommended approach? If they're equally good solutions we'd prefer to stay on Expo.

**Comment by wmathurin** [comment]
What did you mean by " use the HTML5 package" ?

I think you need to eject from Expo to use our libraries.

**Comment by elie222** [comment]
Sorry, I looked into it further. I was considering using the Cordova
version but not sure that would well with React Native.

If all I need is log in via the rest api, would it make sense to just do an
oauth login or are is there still an advantage to using the React Native
sdk?

**Comment by wmathurin** [comment]
The Mobile SDK react native library will give you:
- oauth out of the box with secure storage of the tokens,
- network plugin which will transparently do a refresh of the access token when the access token expires,
- secure storage (SmartStore),
- offline synchronization (SmartSync).

To see all the functionality we provide:
- see the sources here: https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/tree/master/src
- see our trail here: https://trailhead.salesforce.com/en/content/learn/modules/mobile_sdk_react_native
