### ISSUE TITLE
error: Multiple commands produce `Assets.car`

### ISSUE THREAD

**Issue by elie222** [forcedotcom/SalesforceMobileSDK-ReactNative#153]
Running `forcereact create` and then attempting to run the project in XCode produces the following error:

```
error: Multiple commands produce '.../testapp/ios/build/testapp/Build/Products/Debug-iphonesimulator/testapp.app/Assets.car':
1) Target 'testapp' (project 'testapp') has compile command with input '.../testapp/mobile_sdk/SalesforceMobileSDK-iOS/shared/resources/Images.xcassets'
2) That command depends on command in Target 'testapp' (project 'testapp'): script phase “[CP] Copy Pods Resources”
```

**Comment by elie222** [comment]
So for anyone else running into this problem, I don't actually know what happened but I got it working.

In case anyone else runs into this issue. This is what I did to fix it:

* Deleted all the forcereact projects I had created as tests.
* Emptied the trash (at which point I was told one of the projects was in use, even though all my applications were closed. Seemingly hinting at a problem).
* For good measure I rebooted my computer.
* I ran `forcereact create` again and all worked as expected the first time.

**Comment by elie222** [comment]
Another update. I better understand when this does and doesn't happen.

If I run `forcereact create` and select only `iOS` it works fine. If I select `ios,android` it produces the `error: Multiple commands produce` error.

**Comment by whalemare** [comment]
Try to use Legacy build system in workspace settings

**Comment by wmathurin** [comment]
It looks like the last suggestion (use Legacy build system) addressed your issue.

**Comment by multinerd** [comment]
> It looks like the last suggestion (use Legacy build system) addressed your issue.

It doesn't address the issue. It just ignores it.

**Comment by NewTech2000** [comment]
Same Issue In SDK 12.0.0 
Multiple commands produce '/Users/mob/Library/Developer/Xcode/DerivedData/Test-gehgwyxbiqjqozegitlfsnwpinsq/Build/Products/Debug-iphonesimulator/Test.app/Assets.car'
@wmathurin any solution For this ?

**Comment by Himatheja** [comment]
Same issue here. SDK V12.0.1

**Comment by YorkyNC** [comment]
anyone solved this ?

**Comment by YorkyNC** [comment]
@Himatheja did u solve this problem ?

**Comment by NewTech2000** [comment]
@YorkyNC, retry 
01. Quite X Code, 
2. Clearing X Code-derived data and restarting X Code, and compiling again
