### ISSUE TITLE
Customise login screen

### ISSUE THREAD

**Issue by elie222** [forcedotcom/SalesforceMobileSDK-ReactNative#156]
How does one customise the login screen?

I realise it's not part of the SDK itself but a webview and needs to be done in Salesforce admin but where in the Salesforce admin is the option to customise this screen?
![image](https://user-images.githubusercontent.com/3090527/72615880-54b31700-393e-11ea-9591-d76f844242e7.png)

I was able to customise the follow-up screen through the admin:
![image](https://user-images.githubusercontent.com/3090527/72615979-95ab2b80-393e-11ea-8fb7-ec7f93b88199.png)

**Comment by wmathurin** [comment]
Here is the information you are looking for: https://help.salesforce.com/articleView?id=domain_name_login_branding.htm&type=5

**Comment by elie222** [comment]
Thanks. I did that and managed to get it working on web. But on mobile I can only see the custom login screen after pressing the `Use Custom Domain` button.
Any ideas how to get it showing all the time?

**Comment by wmathurin** [comment]
To change the default login host please read  : https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/communities_login_endpoint.htm
