### ISSUE TITLE
Question: force log in

### ISSUE THREAD

**Issue by elie222** [forcedotcom/SalesforceMobileSDK-ReactNative#159]
I'd like to run e2e tests on my app using Detox but Detox cannot interact with the Salesforce webview login screen.
Is there a way for me to force log in so I can get past those screens in the e2e tests? If I could type a username and password in the code for example that would work.

**Comment by wmathurin** [comment]
We have such tests on this repo: https://github.com/forcedotcom/SalesforceMobileSDK-uitests
Please have a look, it should give you an idea on how to deal with login etc.

**Comment by elie222** [comment]
Nothing js / react native specific there right?

Best,
Eliezer

**Comment by wmathurin** [comment]
Those UI tests take any of our templates (including react-native and hybrid) and run them / login / do some basic checks afterwards. They target both iOS and Android.
