### ISSUE TITLE
syncUp default target

### ISSUE THREAD

**Issue by mkoo21** [forcedotcom/SalesforceMobileSDK-ReactNative#16]
This may be a simple question, but I am trying to use smartsync.syncUp to improve offline functionality for android. The trailhead for smartsync and the comments/code in syncUpTarget.java (in the android sdk) seem to indicate that null/no target is acceptable for syncUp. 

Calling the javascript library's smartsync.syncUp with target set to null gives me a null pointer exception at `com/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartSyncReactBridge.java` at line 75 (the ReactBridgeHelper expects an iterable).

I can modify the bridge to skip over ReactBridgeHelper and pass `JSONObject target=null` straight to SyncUpTarget, but then the call fails with the mysterious error message "sync failed".

Some relevant console outputs:
```
react.force.common.js:53 SmartSyncReactBridge.syncUp called: {"target":null,"soupName":"ContentReview__c","options":{"mergeMode":"OVERWRITE"},"isGlobalStore":false}
react.force.common.js:64 SmartSyncReactBridge.syncUp failed
```
Can I just verify that the intended functionality is that passing null results in a default target, or get a pointer in the right direction if I'm wrong? 

Thanks in advance.

**Comment by wmathurin** [comment]
On the native side and in cordova based hybrid apps, you can pass null, for react native (because of what we do on line 75), you should pass an empty map {} to get the default sync up target.
