### ISSUE TITLE
Missing access to SFUserAccountmanger::stopAuthentication

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-ReactNative#160]
# Description

I have created an application using defer login:

```objective-c
[SalesforceSDKManager sharedManager].appConfig.shouldAuthenticate = NO;
```

Within my application, I do have a button initiating authentication that looks like this:

```typescript
      <Button
        title={'Login'}
        onPress={() =>
          oauth.authenticate(
            token => console.log('done', token),
            err => console.log(err)
          )
        }
      />
```

From that point, I execute the following steps within the application:
1. Click on `Login`
2. Click on `Back` (in the OAuth modal)
3. Click on `Login` (again)

# Expected

Have the OAuth modal reappearing. However

# Actual

Clicking the button produces nothing. However, in the XCode console, I do get this error message:

```
2020-02-11 13:56:07.598648+0000 micmobile[70376:8053273] [SalesforceSDKCore] CLASS: SFUserAccountManager Login has already been called. Stop current authentication using SFUserAccountmanger::stopAuthentication and then retry.
```

Error line: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/36d6f26886dc08289224cae30c26b04caef45c93/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Security/SFUserAccountManager.m#L410

## Suggested Solution

Unless I'm missing something, it seems like the React Native bridge is missing access to some methods to clear up the initiated OAuth prompt (exposing `stopAuthentication` or `restartAuthentication`). Exposing these methods should allow to re-trigger the authentication flow.

---

## Side note

It seems like this page in the documentation is incorrect 
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/react_native_deferred_login.htm

This:

```objective-c
[SalesforceSDKManager sharedManager].authenticateAtLaunch = NO;
```

should be:

```objective-c
[SalesforceSDKManager sharedManager].appConfig.authenticateAtLaunch = NO;
```

**Comment by bhariharan** [comment]
@jpmonette Thank you for your feedback. You are correct that hitting the back button on `LoginViewController` should automatically cancel the existing authentication flow. We have already fixed this bug [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3115), and this will be a part of our next release, `Mobile SDK 8.1.0`, which is coming out soon.

**Comment by sundariragavan** [comment]
@jpmonette  i want to display the screen before the salesforce login. I have  checked this document
https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/react_native_deferred_login.htm. 

[SalesforceSDKManager sharedManager].authenticateAtLaunch = YES;  this line not in my appdelegate.m file. Where i have to add this line. 

After that i want to open the login screen while button click.
Can you please explain how to do ?
--
