### ISSUE TITLE
Best approach to syncDown() metadata (describe/layouts...)

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-ReactNative#164]
What would be the recommended approach to pull down `describe` data as well as `layout` metadata in the store?

Options I have in mind are the following:
1. Using a `custom` type of `target` with the `syncDown()` method, combine with a `iOSImpl` method name or `androidImpl` one.
2. Creating a soup, pulling metadata manually relying on `net.describe` and inserting it in the store

Is that correct? Is there an alternative to execute a `syncDown()` using a JavaScript/TypeScript implementation, or is our only option today the options #2?

Thanks

**Comment by wmathurin** [comment]
Mobile SDK comes with sync down targets for getting metadata. For more information see: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_native_metadata_layout_down.htm

**Comment by NeliHarbuzava** [comment]
@wmathurin how to use it in React Native? In the above link info provided only about Android/iOS native code.

**Comment by jpmonette** [comment]
@NeliHarbuzava 
I believe the recommended approach is in Objective C if you want to stick to the out of the box capabilities - here's an example:
```objective-c
// Getting Metadata for Account SObject
SFMetadataSyncManager *metadataSyncManager = [SFMetadataSyncManager sharedInstance];
[metadataSyncManager fetchMetadataForObject:kAccount mode:SFSDKFetchModeServerFirst completionBlock:^(SFMetadata *metadata) {}];

// Getting Layouts for Account SObject
SFLayoutSyncManager *layoutSyncManager = [SFLayoutSyncManager sharedInstance];
[layoutSyncManager fetchLayoutForObject:kAccount layoutType:nil mode:SFSDKFetchModeServerFirst completionBlock:^(NSString *objectType, SFLayout *layout) {}];
```

In our case, we preferred writing that logic in TypeScript, so manually create a soup, pull the metadata and save them.

Hope it helps.

**Comment by NeliHarbuzava** [comment]
@jpmonette @wmathurin  do you mean that there is no possibility to use `mobilesync.syncDown(storeConfig, target, "someObjectMetadata", {mergeMode:mobilesync.MERGE_MODE.OVERWRITE}, syncName)` (and `mobilesync.reSync()` for next updates) in javascript code to automatically fetch and populate the soup with metadata?
If that's true for React Native SF bridge, this is very sad.

**Comment by wmathurin** [comment]
All types of sync can be defined in config files or in JavaScript.
To help you get the json right (for the config file or for the call to syncDown), we added a json schema and a validator. See https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/offline_config_validator.htm.
This [sample config](https://raw.githubusercontent.com/forcedotcom/SalesforceMobileSDK-Package/master/shared/example.usersyncs.json) has an example for each type of sync.
