### ISSUE TITLE
SyncDown: No such column 'LastModifiedDate' on Custom Metadata

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-ReactNative#165]
**Describe the bug**
`syncDown` does not support to pull Custom metadata - it seems like it automatically adds `LastModifiedDate`, which does not exist on Custom Metadatas.

```
ERROR at Row:1:Column:8
No such column 'LastModifiedDate' on entity 'Sample_CMT__mdt'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
```

**To Reproduce**
Use `syncDown` on a custom metadata object.

**Expected behavior**
To not add `LastModifiedDate`

**Actual behavior**

```
ERROR at Row:1:Column:8
No such column 'LastModifiedDate' on entity 'Sample_CMT__mdt'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
```

**Versions (please complete the following information):**

- `v8.1.0`

**Workaround**

I assume the current workaround is to manually query Salesforce + populate the soup and not rely on `syncDown`.

**Comment by wmathurin** [comment]
Sync down needs a modification date field for incremental syncs (https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_native_inc_sync.htm). By default it is the `lastModifiedDate` field, but you can specify another field if that field does not exist on your object.
Simplify specify the alternate field via the `modificationDateFieldName` property on your target.
The json schema for your syncs.json config files is here: https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/master/shared/syncs.schema.json
