### ISSUE TITLE
Cannot execute SyncUp - Promise hangs, XCode error in loop (The requested resource does not exist)

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-ReactNative#168]
**Describe the bug**
When running `syncUp`, the promise is hanging forever and xcode console tries to sync non stop but fails (`The requested resource does not exist`), until XCode crashes.

**To Reproduce**

1. Register Soup
2. SyncDown
3. UpsertEntry
4. SyncUp (hangs here forever)

```ts
await smartStore.registerSoup(false, 'Account', [
  { path: 'Id', type: 'string' },
  { path: 'Name', type: 'string' },
  { path: 'FirstName', type: 'string' },
  { path: 'LastName', type: 'string' },
  { path: 'RecordTypeId', type: 'string' },
  { path: 'OwnerId', type: 'string' },
  { path: '__local__', type: 'string' },
  { path: '__locally_created__', type: 'string' },
  { path: '__locally_updated__', type: 'string' },
  { path: '__locally_deleted__', type: 'string' },
]);

await mobileSync.syncDown(
  false,
  {
    type: 'soql',
    query: new SOQL('Account').select(['Id', 'FirstName', 'LastName', 'Name', 'OwnerId']).build(),
  },
  'Account',
  { mergeMode: mobileSync.MERGE_MODE.OVERWRITE },
  'AccountDown'
);

await smartStore.upsertSoupEntries(false, 'Account', [
  {
    FirstName: 'Johny',
    LastName: 'Doe',
    __locally_created__: true,
    __locally_updated__: false,
    __locally_deleted__: false,
    __local__: true,
  },
]);

await mobileSync.syncUp(
  false,
  { createFieldList: ['LastName', 'FirstName', 'Name', 'RecordTypeId', 'OwnerId'] },
  'Account',
  {
    mergeMode: mobileSync.MERGE_MODE.OVERWRITE,
    fieldlist: ['Id', 'LastName', 'FirstName', 'Name', 'RecordTypeId', 'OwnerId'],
  }
);
```

**Expected behavior**
Account is inserted in Salesforce following execution of `syncUp`.

**Actual behavior**
`mobileSync.syncUp()` promise is never resolving, and XCode throws the following output in loop (until XCode crashes):

```bash
>
2020-03-31 13:18:05.012612+0100 micmobile[2581:1046571] [MobileSync] CLASS: SFMobileSyncNetworkUtils sendRequestWithMobileSyncUserAgent:response:{
    compositeResponse =     (
                {
            body =             (
                                {
                    errorCode = "NOT_FOUND";
                    message = "The requested resource does not exist";
                }
            );
            httpHeaders =             {
            };
            httpStatusCode = 404;
            referenceId = "local_14";
        }
    );
}
2020-03-31 13:18:05.013018+0100 micmobile[2581:1046571] [MobileSync] CLASS: SFMobileSyncNetworkUtils sendRequestWithMobileSyncUserAgent:request:<SFRestRequest 0x282bcada0 
endpoint: (null) 
method: GET 
path: (null) 
queryParams: [] 
```

![2020-03-31 12 48 56](https://user-images.githubusercontent.com/1114325/78025543-24cabb80-7352-11ea-9cf0-46bdd4ccb196.gif)

**Versions:**

- `8.1.0`

**Comment by jpmonette** [comment]
Out of curiosity, how do we define the target SObject to insert to? It seems like the examples do not include the SObject API Name (unit tests, sample app, documentation) and the `syncUp` target also does not specify the SOQL query:

https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/MobileSyncExplorerReactNative/js/StoreMgr.js#L91

**Comment by wmathurin** [comment]
SOQL is only used for querying data so during sync down.
The default sync up target expects to see find `{attributes: { type: "sobject-type"}}` in the record.
It will be there if you fetched the record using one of the sync down targets that we provide.
For locally created records, that field is added in the code, see here: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/MobileSyncExplorerReactNative/js/StoreMgr.js#L139

**Comment by jpmonette** [comment]
It doesn't seem to be mentioned as a requirement in the official documentation though to insert records:
https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_plugin_methods.htm?search_text=syncup

Also, is it possible to make the promise return an error whenever this is not provided? This put the application in an unrecoverable state and crashes later on - we should be able to catch those kinds of error.

**Comment by wmathurin** [comment]
@rwhitley could we add this to the doc?

**Comment by wmathurin** [comment]
This PR https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3236 will prevent the infinite looping and will cause records that don't have a sobject type or that use a "bad" type (e.g. a type the user doesn't not have permission for) to fail to sync and end up with "The requested resource does not exist" in the lastError field.
