### ISSUE TITLE
Downloading file through sendRequest() and query() not working

### ISSUE THREAD

**Issue by pedramsaleh** [forcedotcom/SalesforceMobileSDK-ReactNative#17]
I'm trying to download a file in Salesforce in my code, but it doesn't work with the API calls. If I query() ContentVersion.VersionData for the file contents, I get a url in the form of `/services/data/v36.0/sobjects/ContentVersion/{ContentVersionID}/VersionData`, as opposed to the file data as expected (like in Workbench). 

I then use that url with sendRequest() to make a rest api call for the data, but it just returns ` {"errorCode" : "NOT_FOUND", "message" : "The requested resource does not exist"}`.  I tried both with and without authentication headers. If I try the same url (but adding the salesforce server prefix) with curl (via the command line) and pass authentication headers it will work, and return the file contents as expected. It also works as expected with the apigee.com console.

Is there a reason why it doesn't work with Salesforce API calls but it doest with external tools?
The headers I'm passing with those tools are as follows:
```
Authorization: OAuth {accessToken}
Host: cs27.salesforce.com
X-Target-URI: https://cs27.salesforce.com
Connection: Keep-Alive
```

**Comment by huminzhi** [comment]
@ivanbogdanov Will you please help have a look of this issue?

**Comment by wmathurin** [comment]
Downloading/uploading binary data to/from JavaScript in a React Native application is not currently supported in Mobile SDK.

**Comment by romanravkov** [comment]
> Downloading/uploading binary data to/from JavaScript in a React Native application is not currently supported in Mobile SDK.

Have you any updates about it in the new version of SDK?
