### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-ReactNative#170]
Is there any discussion / interest / appetite to migrate the codebase to TypeScript, to benefit from type safety?

**Comment by wmathurin** [comment]
We might do the switch if/when we make big changes to the js code.

**Comment by jpmonette** [comment]
@wmathurin Are you welcoming PRs covering this enhancement?

**Comment by wmathurin** [comment]
Of course!

**Comment by wmathurin** [comment]
The work is in. See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/212. Will be in our next release (9.0).
