### ISSUE TITLE
MobileSDK.oauth.logout() crashes the application in debug mode

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-ReactNative#176]
Calling `SDK.oauth.logout()` in Debug mode crashes the application, requiring to stop it and relaunching it.

```ts
const logout = () => {
  SDK.oauth.logout();
};
```

## Expected behavior
Token is cleared, user store is flushed and application proceed with its normal execution.

## Actual behavior
User gets logged out, but an error is appearing.

### Error message
```
Runtime is not ready for debugging. Make sure Packager server is running.

RCTFatal
-[RCTCxxBridge handleError:]
__21-[RCTCxxBridge start]_block_invoke
invocation function for block in facebook::react::(anonymous namespace)::RCTObjcExecutor::RCTObjcExecutor(id<RCTJavaScriptExecutor>, void (NSError*) block_pointer, std::__1::shared_ptr<facebook::react::MessageQueueThread>, std::__1<facebook::react::ExecutorDelegate>)
__58-[RCTWebSocketExecutor _executeJSCall:arguments:callback:]_block_invoke
__44-[RCTWebSocketExecutor sendMessage:onReply:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread
```

## Extra
On another note, I believe `logout()` should also be async like `authenticate()` as it could hang / fail. This would give the right amount of information to the React Native app to expose a loading screen or an error.

**Comment by wmathurin** [comment]
Thanks for reporting this issue. We have created a bug in our internal bug tracking system.

**Comment by wmathurin** [comment]
Logout is now async and can be passed a callback if you need to know when logout completed (e.g. if you are using deferred login). See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/191
I have not been able to reproduce your crash (with the modified logout code).

**Comment by pragati-raut** [comment]
Hi, on completion of oauth.logout() my app gets minimized and then after it will redirect to login, can you please provide the solution?
