### ISSUE TITLE
How to handle push notifications callback in JS modules 

### ISSUE THREAD

**Issue by srikanthsunkari** [forcedotcom/SalesforceMobileSDK-ReactNative#177]
Hi
I am trying to integrate push notifications service in the app using mobile sdk, I am unable to find how to handle the notifications in JS modules after integrating at Native sides (iOS/Android). Is notification callback handling is also needs to be done at Native side or is it available via js modules as well? 
As I can see in hybrid we have something like below,
`cordova.require("com.salesforce.util.push").registerPushNotificationHandler(-,-, etc.,)`
Bu i couldn't find anything like this for react native.

**Comment by wmathurin** [comment]
On iOS, there is a couple of lines of code to uncomment in your AppDelegate.m ([this one ](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m#L66)and [that one](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m#L95)).
For the actual handling of the notification, we recommend you use any of the available 3rd party packages e.g. https://github.com/zo0r/react-native-push-notification

**Comment by Nayan014** [comment]
Hi @wmathurin 

I am able to implement this using `[@react-native-firebase/messaging](https://rnfirebase.io/messaging/usage#:~:text=Edit%20Page-,cloud%20messaging,-Installation%20and%20getting)` but we have one issue with that.
we are getting different FCM tokens in salesforce connected app and in 3rd party plugins i.e @react-native-firebase/messaging

Can you please suggest the best solution in that as we don't have rapper for push notification in salesforce SDK for react-native
