### ISSUE TITLE
How to upload/download documents from salesforce content Api

### ISSUE THREAD

**Issue by srikanthsunkari** [forcedotcom/SalesforceMobileSDK-ReactNative#179]
Hi 
I am looking for a way to upload and download files/attachments/documents from mobile app to salesforce as content Api.
Unlike below profile pic API example, i would like to upload/download multiple types of file contents, in a different path from user-profile as in content path location.
[this](https://github.com/wmathurin/MyUserPicReactNative/blob/master/js/UserPic.js) and [this](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/react_native_binary_upload.htm)
I couldn't find a good example documentation. Any suggestion would be highly appreciated.
Thank you.

**Comment by wmathurin** [comment]
The network module allows you to send arbitrary request to the server as highlighted in the examples you linked.

Server side, we have APIs to upload and download files. Here are some of the docs covering those topics:
* https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/quickreference_post_binary_file.htm
* https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/features_files.htm

**Comment by srikanthsunkari** [comment]
Thank you for the quick response.
I am trying to upload an image binary file using [this](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/intro_input.htm#postComment), but facing a below error,

**Exception** 
> ExceptionsManager.js:94 Exception '-[__NSDictionaryM length]: unrecognized selector sent to instance 0x600003120920' was thrown while invoking sendRequest on target SFNetReactBridge with params (
>         {
>         doesNotRequireAuthentication = 0;
>         endPoint = "/services/data";
>         fileParams =         {
>             fileUpload =             {
>                 fileMimeType = "image/jpeg";
>                 fileName = "pic.jpg";
>                 fileUrl = "file:///Users/NG/Library/Developer/CoreSimulator/Devices/C994E4F5-50ED-4C21-B660-D5E8A0617E07/data/Containers/Data/Application/CFA5256E-9A40-4BD6-BAE6-5A01299894CD/Documents/images/523B43B7-AA19-455D-B0DA-4C70D88290DB.jpg";
>             };
>         };
>         headerParams =         {
>             Accept = "application/json";
>             Connection = "Keep-Alive";
>             "Content-Disposition" = "form-data; name=\"feedElementFileUpload\"; filename=\"receipt.jpg\"";
>             "Content-Length" = 6210358;
>             "Content-Type" = "multipart/form-data; boundary=7B1A1028-BC55-46BF-8529-6C675DEA5C51";
>             "X-Connect-Bearer-Urls" = true;
>             body =             {
>                 messageSegments =                 (
>                                         {
>                         text = "Please accept this receipt.";
>                         type = Text;
>                     }
>                 );
>             };
>             capabilities =             {
>                 content =                 {
>                     description = "Receipt for expenses";
>                     title = "receipt.jpg";
>                 };
>             };
>             feedElementType = FeedItem;
>             subjectId = 005RR000000DmOb;
>         };
>         method = POST;
>         path = "/v46.0/chatter/feed-elements";
>         queryParams =         {
>         };
>         returnBinary = 0;
>     },
>     5683
> )
> callstack: (
> 	0   CoreFoundation                      0x00000001122201bb __exceptionPreprocess + 331
> 	1   libobjc.A.dylib                     0x000000011045b735 objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000011223ef44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 	3   CoreFoundation                      0x0000000112224ed6 ___forwarding___ + 1446
> 	4   CoreFoundation                      0x0000000112226da8 _CF_forwarding_prep_0 + 120
> 	5   CFNetwork                           0x0000000111b68deb _ZN15HTTPHeaderValue7isValidEPK10__CFString + 19
> 	6   CFNetwork                           0x0000000111a32ec9 _ZN11HTTPMessage25setHeaderFieldStringValueEPK10__CFStringS2_ + 41
> 	7   CFNetwork                           0x00000001119cb0a5 CFURLRequestSetHTTPHeaderFieldValue + 136
> 	8   DWM GAS                             0x000000010dff0d6b -[SFRestRequest prepareRequestForSend:] + 4443
> 	9   DWM GAS                             0x000000010dfe6d8f -[SFRestAPI enqueueRequest:delegate:shouldRetry:] + 207
> 	10  DWM GAS                             0x000000010dfe653e -[SFRestAPI send:delegate:shouldRetry:] + 2094
> 	11  DWM GAS                             0x000000010dfe5ce6 -[SFRestAPI send:delegate:] + 214
> 	12  DWM GAS                             0x000000010dfe3709 -[SFRestAPI(Instrumentation) instr_send:delegate:] + 681
> 	13  DWM GAS                             0x000000010dfdcfa3 -[SFRestAPI(Blocks) sendRESTRequest:failBlock:completeBlock:] + 259
> 	14  DWM GAS                             0x000000010df67b95 -[SFNetReactBridge sendRequest:callback:] + 2837
> 	15  CoreFoundation                      0x000000011222703c __invoking___ + 140
> 	16  CoreFoundation                      0x00000001122244d5 -[NSInvocation invoke] + 325
> 	17  CoreFoundation                      0x0000000112224926 -[NSInvocation invokeWithTarget:] + 54
> 	18  DWM GAS                             0x000000010dc63fca -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2810
> 	19  DWM GAS                             0x000000010dc68716 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 790
> 	20  DWM GAS                             0x000000010dc6822f _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127
> 	21  DWM GAS                             0x000000010dc681a9 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
> 	22  libdispatch.dylib                   0x0000000114a7b4e1 _dispatch_call_block_and_release + 12
> 	23  libdispatch.dylib                   0x0000000114a7c54b _dispatch_client_callout + 8
> 	24  libdispatch.dylib                   0x0000000114a8301c _dispatch_lane_serial_drain + 720
> 	25  libdispatch.dylib                   0x0000000114a83b5f _dispatch_lane_invoke + 401
> 	26  libdispatch.dylib                   0x0000000114a8c9a8 _dispatch_workloop_worker_thread + 645
> 	27  libsystem_pthread.dylib             0x0000000114e61fd2 _pthread_wqthread + 980
> 	28  libsystem_pthread.dylib             0x0000000114e61be9 start_wqthread + 13
> )

**Code**
```

    uploadPhoto(localPhotoUrl, callback) {
        sendRequest('/services/data', '/v46.0/chatter/feed-elements',
            (response) => {
                callback(LOG_TAG_DEBUG_RESTFUL_APIS, response);
            },
            (error) => {
                console.log(LOG_TAG_DEBUG_RESTFUL_APIS, 'Failed to upload user photo:', error);
            },
            'POST',
            {}
            ,
            {
                'X-Connect-Bearer-Urls': 'true',
                'Content-Type': 'application/json; charset=UTF-8',
                'Accept': 'application/json',
                "body": {
                    "messageSegments": [
                        {
                            "type": "Text",
                            "text": "Please accept this receipt."
                        }
                    ]
                },
                "capabilities": {
                    "content": {
                        "description": "Receipt for expenses",
                        "title": "receipt.jpg"
                    }
                },
                "feedElementType": "FeedItem",
                "subjectId": "005RR000000DmOb",
                'Content-Type': 'multipart/form-data',
                'Content-Disposition': 'form-data; name="feedElementFileUpload"; filename="receipt.jpg"'
            },
            {
                fileUpload:
                {

                    fileUrl: localPhotoUrl, fileMimeType: 'image/jpeg', fileName: 'pic.jpg'
                }
                // localPhotoUrl
            }
        );
    }
```
 ```
   renderImagePicker() {
        ImagePicker.showImagePicker(imagePickerOptions, (response) => {
            if (response.didCancel) {
            } else if (response.error) {
            } else if (response.customButton) {
            } else {
                // You can also display the image using data:
                // const source = { uri: 'data:image/jpeg;base64,' + response.data };
                console.log(LOG_TAG_DEBUG_RESTFUL_APIS, response);
                this.setState({
                    imageUrl: response.uri,
                    attachment1: `data:${response.type};base64,` + response.data,
                });
                this.uploadPhoto(this.state.imageUrl, (res) => {
                    console.log(LOG_TAG_DEBUG_RESTFUL_APIS, res);
                })
            }
        });
    }
```
I guess i messed up the request body and params, Could you please provide the right way to send the request params in my code.

**Comment by wmathurin** [comment]
What version of the Mobile SDK are you using?

**Comment by srikanthsunkari** [comment]
@wmathurin it is v7.3.0.

**Comment by srikanthsunkari** [comment]
@wmathurin could you please help on this.

**Comment by anishtr4** [comment]
@srikanthsunkari  are you able to download different files ? if yes can you please share code snippets please.

@wmathurin  Can you please provide some document for downloading different documents in react native from sales force.

**Comment by bhariharan** [comment]
@anishtr4 This forum is reserved for bugs/issues with the code in this repository. Please post any other queries on `Salesforce Stack Exchange`.

**Comment by srikanthsunkari** [comment]
@wmathurin @bhariharan 

Could you please help me with the right payload/fileParams for download operation using sendRequst.

```
const fileParams = {
    VersionData: {
        fileMimeType: "application/json",
        fileName: "TestFileName"
    }
};
const payload = {
    Title: "Testing file download title",
    Description: "Testing file download descripton ",
}
const endPoint = "/services/data";
const path = `/${net.getApiVersion()}/sobjects/ContentVersion/${documentIdResponse.ContentDocumentId}/VersionData`;
await netSendRequest(endPoint,
    path,
    (response) => {
        console.log('response::', response);
    }, (error) => {
        console.log('error::', error);
    },
    'GET',
    payload,
    null,
    fileParams,
    true, /* return binary */
    false);
```

**Comment by srikanthsunkari** [comment]
Sorry for reopening this. Fighting with this issue from yesterday. Do not bother to blame me for reopening this issue. Finally found the solution, that actually I do not necessarily need to pass any params for download request. But the problem was with the ContentVersion.Id in the path. Got it resolved now.
Thank you.
