### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `./$.html` from `E:\React\demo\node_modules\core-js\modules\es5.js`

### ISSUE THREAD

**Issue by srikanthsunkari** [forcedotcom/SalesforceMobileSDK-ReactNative#180]
While I am trying run react-native code in microsoft windows environment, facing below issue obviously this is because of the salesforce modules/react native packages are not available available in windows environment. But I am unable to understand this error in detail.

``
error: bundling failed: Error: Unable to resolve module `./$.html` from `E:\React\demo\node_modules\core-js\modules\es5.js`: The module `./$.html` could not be found from `E:\React\demo\node_modules\core-js\modules\es5.js`. Indeed, none of these files exist:   * `$.html`   * `E:\React\demo\node_modules\core-js\modules\$.html\index(.native||.windows.jsx|.native.jsx|.jsx|.windows.js|.native.js|.js|.windows.ts|.native.ts|.ts|.windows.json|.native.json|.json)`         at ModuleResolver.resolveDependency (E:\React\demo\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)         at ResolutionRequest.resolveDependency (E:\React\demo\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)         at DependencyGraph.resolveDependency (E:\React\demo\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)         at Object.resolve (E:\React\demo\node_modules\metro\src\lib\transformHelpers.js:264:42)         at dependencies.map.result (E:\React\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)         at Array.map (<anonymous>)         at resolveDependencies (E:\React\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)         at E:\React\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33         at Generator.next (<anonymous>)         at asyncGeneratorStep (E:\React\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24) BUNDLE  [windows, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓░░░ 81.3% (1203/1334), failed. 
``

It would be helpful to understand this error exact reason in detail. Could you please help me with this to understand the error?

**Comment by wmathurin** [comment]
The error is coming from React Native metro bundler. I recommend you refer to their doc to understand better the output.
For more information see: https://facebook.github.io/metro/
