### ISSUE TITLE
[Question] sendRequest method request params to upload an image binary file 

### ISSUE THREAD

**Issue by srikanthsunkari** [forcedotcom/SalesforceMobileSDK-ReactNative#181]
Hi,
I am trying to upload an image binary file using [this](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/intro_input.htm#postComment) method, but facing a below error,

**Mobile SDK Version:** `v7.3.0.`

**Exception** 

> ExceptionsManager.js:94 Exception '-[__NSDictionaryM length]: unrecognized selector sent to instance 0x600003120920' was thrown while invoking sendRequest on target SFNetReactBridge with params (
>         {
>         doesNotRequireAuthentication = 0;
>         endPoint = "/services/data";
>         fileParams =         {
>             fileUpload =             {
>                 fileMimeType = "image/jpeg";
>                 fileName = "pic.jpg";
>                 fileUrl = "file:///Users/NG/Library/Developer/CoreSimulator/Devices/C994E4F5-50ED-4C21-B660-D5E8A0617E07/data/Containers/Data/Application/CFA5256E-9A40-4BD6-BAE6-5A01299894CD/Documents/images/523B43B7-AA19-455D-B0DA-4C70D88290DB.jpg";
>             };
>         };
>         headerParams =         {
>             Accept = "application/json";
>             Connection = "Keep-Alive";
>             "Content-Disposition" = "form-data; name=\"feedElementFileUpload\"; filename=\"receipt.jpg\"";
>             "Content-Length" = 6210358;
>             "Content-Type" = "multipart/form-data; boundary=7B1A1028-BC55-46BF-8529-6C675DEA5C51";
>             "X-Connect-Bearer-Urls" = true;
>             body =             {
>                 messageSegments =                 (
>                                         {
>                         text = "Please accept this receipt.";
>                         type = Text;
>                     }
>                 );
>             };
>             capabilities =             {
>                 content =                 {
>                     description = "Receipt for expenses";
>                     title = "receipt.jpg";
>                 };
>             };
>             feedElementType = FeedItem;
>             subjectId = 005RR000000DmOb;
>         };
>         method = POST;
>         path = "/v46.0/chatter/feed-elements";
>         queryParams =         {
>         };
>         returnBinary = 0;
>     },
>     5683
> )
> callstack: (
> 	0   CoreFoundation                      0x00000001122201bb __exceptionPreprocess + 331
> 	1   libobjc.A.dylib                     0x000000011045b735 objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000011223ef44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 	3   CoreFoundation                      0x0000000112224ed6 ___forwarding___ + 1446
> 	4   CoreFoundation                      0x0000000112226da8 _CF_forwarding_prep_0 + 120
> 	5   CFNetwork                           0x0000000111b68deb _ZN15HTTPHeaderValue7isValidEPK10__CFString + 19
> 	6   CFNetwork                           0x0000000111a32ec9 _ZN11HTTPMessage25setHeaderFieldStringValueEPK10__CFStringS2_ + 41
> 	7   CFNetwork                           0x00000001119cb0a5 
....
> 	27  libsystem_pthread.dylib             0x0000000114e61fd2 _pthread_wqthread + 980
> 	28  libsystem_pthread.dylib             0x0000000114e61be9 start_wqthread + 13
> )

**Code**
```

    uploadPhoto(localPhotoUrl, callback) {
        sendRequest('/services/data', '/v46.0/chatter/feed-elements',
            (response) => {
                callback(LOG_TAG_DEBUG_RESTFUL_APIS, response);
            },
            (error) => {
                console.log(LOG_TAG_DEBUG_RESTFUL_APIS, 'Failed to upload user photo:', error);
            },
            'POST',
            {}
            ,
            {
                'X-Connect-Bearer-Urls': 'true',
                'Content-Type': 'application/json; charset=UTF-8',
                'Accept': 'application/json',
                "body": {
                    "messageSegments": [
                        {
                            "type": "Text",
                            "text": "Please accept this receipt."
                        }
                    ]
                },
                "capabilities": {
                    "content": {
                        "description": "Receipt for expenses",
                        "title": "receipt.jpg"
                    }
                },
                "feedElementType": "FeedItem",
                "subjectId": "005RR000000DmOb",
                'Content-Type': 'multipart/form-data',
                'Content-Disposition': 'form-data; name="feedElementFileUpload"; filename="receipt.jpg"'
            },
            {
                fileUpload:
                {

                    fileUrl: localPhotoUrl, fileMimeType: 'image/jpeg', fileName: 'pic.jpg'
                }
                // localPhotoUrl
            }
        );
    }
```
 ```
   renderImagePicker() {
        ImagePicker.showImagePicker(imagePickerOptions, (response) => {
            if (response.didCancel) {
            } else if (response.error) {
            } else if (response.customButton) {
            } else {
                // You can also display the image using data:
                // const source = { uri: 'data:image/jpeg;base64,' + response.data };
                console.log(LOG_TAG_DEBUG_RESTFUL_APIS, response);
                this.setState({
                    imageUrl: response.uri,
                    attachment1: `data:${response.type};base64,` + response.data,
                });
                this.uploadPhoto(this.state.imageUrl, (res) => {
                    console.log(LOG_TAG_DEBUG_RESTFUL_APIS, res);
                })
            }
        });
    }
```
I guess I am sending the wrong request body and params, Could you please provide an example for the right way to send the request params in my code.
Appreciate the help in advance.

**Comment by wmathurin** [comment]
Looking at your call, there are several problems:
* your payload is empty,
* your headers contain things like belong in the payload (e.g. "body", "capabilities", "feedElementType" etc).

Also, I think you need to upload the file first and then create the feed post with a reference to the file id.
The upload will be very similar to https://github.com/wmathurin/MyUserPicReactNative/blob/master/js/UserPic.js#L109
Except it will go to the file end point (https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_files_information.htm).

The feed element post are detailed here:
https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_feed_element.htm

**Comment by srikanthsunkari** [comment]
Thank you for the quick response @wmathurin

**Comment by wmathurin** [comment]
It looks like my response addressed your question.

**Comment by oktalk** [comment]
I'm having similar issues. Here is the response error I'm getting:
```
      {
        "message": "Cannot include more than one non-binary part",
        "errorCode": "INVALID_MULTIPART_REQUEST"
      }
```

It's not clear to me what the payload should be. I'm following this example: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/react_native_binary_upload.htm

Here is my code:
```
    net.sendRequest(
      '/services/data',
      `/v55.0/connect/communities/${authCert.communityId}/user-profiles/${authCert.userId}/photo`,
        (response) => { console.log(response); },
        (error) => { console.log(error); },
        'POST',
        {},
        {
          'X-Connect-Bearer-Urls': 'true',
          'Content-Type': 'multipart/form-data',
          'Content-Disposition': 'form-data; name="feedElementFileUpload"; filename="receipt.jpg"'
        },
        {
          fileUpload: {
            fileUrl:file.uri,
            fileMimeType:file.type,
            fileName:file.filename
          }
        }
    );
```

**Comment by wmathurin** [comment]
Could you follow the [example](https://github.com/wmathurin/MyUserPicReactNative/blob/master/js/UserPic.js#L109) more closely and try without the Content-Type and Content-Disposition headers?
