### ISSUE TITLE
Sync down not working properly with mobilesdk-ios updated to 8.2

### ISSUE THREAD

**Issue by marlonatlumary** [forcedotcom/SalesforceMobileSDK-ReactNative#188]
Upgraded to mobile sdk ios to 8.2 and /SalesforceMobileSDK-ReactNative to 8.2 

the follow code stop working
```
import {smartstore, mobilesync} from 'react-native-force';

export async function syncDownSoupFromSalesforce(soqlQuery, tableName, shouldCleanupTable = true) {

  const syncMergeMode = mobilesync.MERGE_MODE.OVERWRITE;

  syncInFlight = true;
  const soqlQueryCleaned = soqlQuery.replace(/\s+/g, ' '); // remove whitespace
  const target = {type: 'soql', query: soqlQueryCleaned};

  const result = new Promise((resolve, reject) =>
    mobilesync.syncDown(
        false,
        target,
        tableName,
        {
          mergeMode: syncMergeMode,
        },
        null,
        (sync) => {
          console.log('sync successful:'+sync);
          syncInFlight = false;
          resolve(sync);
        },
        async (result) => {
          console.log('result error:'+result);

          syncInFlight = false;
          
          reject(result);
        }
    )
  );
  
  return result;
} 
```
with errors 
```
   SFMobileSyncReactBridge.syncDown failed: {"soupName":"orgsettings","status":"FAILED","isGlobalStore":false,"maxTimeStamp":-1,"options":{"mergeMode":"OVERWRITE"},"error":"{\n    error =     (\n                {\n            errorCode = \"NOT_FOUND\";\n            message = \"The requested resource does not exist\";\n        }\n    );\n}","message":"Sync failed","_soupEntryId":37,"progress":0,"target":{"query":"select LastModifiedDate,Id, enrtcr__Disable_SMS__c, enrtcr__Shift_Acceptance__c, enrtcr__Case_Note_Warning__c, enrtcr__Foul_Linen_Allowance_Export_Code__c,enrtcr__Salesforce_One_Integration__c, enrtcr__Appointment_Start_Threshold__c from enrtcr__Settings__c order by LastModifiedDate","type":"soql","iOSImpl":"SFSoqlSyncDownTarget","modificationDateFieldName":"LastModifiedDate","idFieldName":"Id"},"endTime":1594014822951,"type":"syncDown","totalSize":-1,"storeName":"defaultStore","startTime":1594014822639}
[Mon Jul 06 2020 15:23:42.963]  LOG      result error:[object Object]
[Mon Jul 06 2020 15:23:42.965]  LOG      SFMobileSyncReactBridge.syncDown failed: {"soupName":"users","status":"FAILED","isGlobalStore":false,"maxTimeStamp":-1,"options":{"mergeMode":"OVERWRITE"},"error":"{\n    error =     (\n                {\n            errorCode = \"NOT_FOUND\";\n            message = \"The requested resource does not exist\";\n        }\n    );\n}","message":"Sync failed","_soupEntryId":38,"progress":0,"target":{"query":"select LastModifiedDate,Id,Name,Username,Phone,MobilePhone,CompanyName,Manager.Name,Manager.MobilePhone,Manager.Phone,MediumPhotoUrl,ProfileId from User where Id = '0057F000003R4cdQAC' order by LastModifiedDate","type":"soql","iOSImpl":"SFSoqlSyncDownTarget","modificationDateFieldName":"LastModifiedDate","idFieldName":"Id"},"endTime":1594014822955,"type":"syncDown","totalSize":-1,"storeName":"defaultStore","startTime":1594014822645}
```
All queries have returns from dev consoles. but simply not working in app now.   Where can i found the proper usage for the latest usage ? SFMobileSyncReactBridge seems gone in mobile sdk.

also tried out the instruction link
https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/1bc0154284160e351113093af7a8c28fe69fa97c/MobileSyncExplorerReactNative/js/StoreMgr.js#L44

with following code 

```
import {smartstore, mobilesync, forceUtil} from 'react-native-force';

const syncDown = forceUtil.promiserNoRejection(mobilesync.syncDown);
const syncName = 'mobileSyncExplorerSyncDown';

export async function syncDownSoupFromSalesforce(soqlQuery, tableName, shouldCleanupTable = true) {
 
  syncDownContacts();

}

function syncDownContacts() {
  if (syncInFlight) {
    console.log('Not starting syncDown - sync already in fligtht');
    return Promise.resolve();
  }
  console.log('Starting syncDown');
  syncInFlight = true;
  const fieldlist = ['Id', 'FirstName', 'LastName', 'Title', 'Email', 'MobilePhone','Department', 'LastModifiedDate'];
  const target = {type:'soql', query:`SELECT ${fieldlist.join(',')} FROM Contact LIMIT 10000`};
  return syncDown(false, target, 'contacts', {mergeMode: mobilesync.MERGE_MODE.OVERWRITE}, syncName)
      .then(() => {
        console.log('syncDown completed or failed');
        syncInFlight = false;
      });
}
```
also same problem, ended up with 
```
"syncDown failed, error: (null), `args`: {
    isGlobalStore = 0;
    options =     {
        mergeMode = OVERWRITE;
    };
    soupName = contacts;
    syncName = mobileSyncExplorerSyncDown;
    target =     {
        query = "SELECT Id,FirstName,LastName,Title,Email,MobilePhone,Department,LastModifiedDate FROM Contact LIMIT 10000";
        type = soql;
    };
}."
```

**Comment by marlonatlumary** [comment]
Looking into react.force.mobilesync.js

function below is calling up  SFMobileSyncReactBridge
const exec = (successCB, errorCB, methodName, args) => {
    forceExec("SFMobileSyncReactBridge", "MobileSyncReactBridge", SFMobileSyncReactBridge, MobileSyncReactBridge, successCB, errorCB, methodName, args);
};

i didn't find this class in documentation http://forcedotcom.github.io/SalesforceMobileSDK-iOS/Documentation/MobileSync/html/index.html
Is this the reason why this exe failed 
SFMobileSyncReactBridge.syncDown failed:  ...

**Comment by wmathurin** [comment]
The error you are seeing is coming back from the server when the user/profile is not allowed to access the given resource.
Could you double check the user/profile you are logging as in the mobile app?

**Comment by marlonatlumary** [comment]
> The error you are seeing is coming back from the server when the user/profile is not allowed to access the given resource.
> Could you double check the user/profile you are logging as in the mobile app?

I found the user id i am using is different from the real user id in scratch org. 
So,  i started to tidy up all RN warnings. after i got them cleaned first and then i triggered  a new build
then i got this.  **Use of unresolved identifier 'SafeMutableDictionary'**
   private var encryptionKey: SFEncryptionKey
    private static var globalStores = **SafeMutableDictionary**<NSString, KeyValueEncryptedFileStore>()
    private static var userStores = **SafeMutableDictionary**<NSString, SafeMutableDictionary<NSString, KeyValueEncryptedFileStore>>()
    private static let keyValueStoresDirectory = "key_value_stores"
    private static let encryptionKeyLabel = "com.salesforce.keyValueStores.encryptionKey"

Is this the possible cause?  how to get it fixed?

**Comment by wmathurin** [comment]
8.2 has not been released yet. Are you building your application from dev? How did you generate your application?

**Comment by marlonatlumary** [comment]
> 8.2 has not been released yet. Are you building your application from dev? How did you generate your application?
Thanks for reply in time. Yes i build my application from dev,   RN 0.62.2.   
        "react-native-force": "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#93793a5",
        "SalesforceMobileSDK-Android": "https://github.com/forcedotcom/SalesforceMobileSDK-Android.git#bc7f6be",
        "SalesforceMobileSDK-iOS": "https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#dev"
Using Pod file to generate project for ios


platform :ios, '12.2'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
use_native_modules!

project 'Lumary.xcodeproj'
target 'Lumary' do
rn_path = '../node_modules/react-native'
rn_maps_path = '../node_modules/react-native-maps'
source 'https://github.com/CocoaPods/Specs.git'

# New Added 0.62.2 Start
pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector'
pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec'
pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired'
pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
pod 'React', :path => '../node_modules/react-native/'
pod 'React-Core', :path => '../node_modules/react-native/'
pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
# New Added 0.62.2 End

pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/Yoga'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec',:modular_headers => false
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec',:modular_headers => false
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#'CxxBridge' missing
pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
# 'RCTCameraRoll' missing
# 'RCTGeolocation' missing
pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'  # New Added 0.62.2
pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'
pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'


pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'  # New Added 0.62.2
pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'  # New Added 0.62.2
pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'  # New Added 0.62.2
pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon" # New Added 0.62.2
pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native/ReactCommon'  # New Added 0.62.2

pod 'react-native-maps', path: rn_maps_path
pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

# pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'  
pod 'RNSketchCanvas', :path => '../node_modules/@terrylinla/react-native-sketch-canvas'

use_modular_headers!
pod 'SalesforceSDKCommon', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceAnalytics', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'MobileSync', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceReact', :path => '../node_modules/react-native-force'
pod 'react-native-sms', :path => '../node_modules/react-native-sms'

pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

end

post_install do |installer_representation|
  # Comment the following if you do not want the SDK to emit signpost events for instrumentation. Signposts are  enabled for non release version of the app.
  print "SQLCipher: link Pods/Headers/sqlite3.h"
  system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1','SIGNPOST_ENABLED=1']
        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-DDEBUG','-DSIGNPOST_ENABLED']
      end
    end
  end

  # https://github.com/CocoaPods/CocoaPods/issues/7314
  fix_deployment_target(installer_representation)
end

def fix_deployment_target(pod_installer)
  if !pod_installer
    return
  end
  puts "Make the pods deployment target version the same as our target"

  project = pod_installer.pods_project
  deploymentMap = {}
  project.build_configurations.each do |config|
    deploymentMap[config.name] = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
  end
  # p deploymentMap

  project.targets.each do |t|
    puts "  #{t.name}"
    t.build_configurations.each do |config|
      oldTarget = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      newTarget = deploymentMap[config.name]
      if oldTarget == newTarget
        next
      end
      puts "    #{config.name} deployment target: #{oldTarget} => #{newTarget}"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = newTarget
    end
  end
end

**Comment by marlonatlumary** [comment]
@wmathurin   i downupgraded to 8.1  by changing following in package json.  (not sure if RN version 0.62.2 matters will try out soon)
    "sdkDependencies": {
        "SalesforceMobileSDK-Android": "https://github.com/forcedotcom/SalesforceMobileSDK-Android.git#v8.1.0",
        "SalesforceMobileSDK-iOS": "https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v8.1.0"
    },

   "react-native-force": "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v8.1.0"

It is still not working.  One thing i can be sure is according to my login user id is not match the id in scratch org
I am login as user name 'test-y1sntybwjump@example.com'
[Tue Jul 07 2020 11:28:37.587]  LOG      my finalQuery generated with id incorrect:SELECT Id,Name,Username,Phone,MobilePhone,CompanyName,Manager.Name,Manager.MobilePhone,Manager.Phone,MediumPhotoUrl,ProfileId FROM User WHERE Id = '**0056D000002LN5z**'

but the search in dev console for this user test-y1sntybwjump@example.com
returns this userID is **0056D000002LN5zQAG**   test-y1sntybwjump@example.com. User User

**Last 3 letters is missing!!** 
Looping out all debug using 
following code 
export async function syncUserData()
    const oathUser = await getAuthCredentials();
    Object.entries(oathUser).forEach(([key, value]) => {
      console.log(key, value);
    });
   .......
}
   SFOauthReactBridge.getAuthCredentials succeeded
[Tue Jul 07 2020 11:53:06.110]  LOG      oathUser:WHERE Id = '0056D000002LN5z'
[Tue Jul 07 2020 11:53:06.120]  LOG      userId **0056D000002LN5z**
[Tue Jul 07 2020 11:53:06.140]  LOG      loginUrl https://test.salesforce.com
[Tue Jul 07 2020 11:53:06.330]  LOG      accessToken 00D6D00000010zX!AQgAQMtApxWpkV5Md7O_cXdocWCzUvBhVBPQ9XDHW_eRUUA420_5YFnp9Z9VJ8PBQzzuWIg7rg9mmJ.7JSdmIblWiH9zakhZ
[Tue Jul 07 2020 11:53:06.340]  LOG      communityId null
[Tue Jul 07 2020 11:53:06.350]  LOG      clientId 3MVG9d8..z.hDcPKruz60khFYJYb4G68_pOEeDI_YhU.7o.W2JDzpDpsu5Rj5PqdxcHhJjnGyIz9s9X6bgmuF
[Tue Jul 07 2020 11:53:06.370]  LOG      communityUrl null
[Tue Jul 07 2020 11:53:06.390]  LOG      refreshToken 5Aep861EvNzkxAlxVPFXKdg43dOI5o6Hn9dQIdQsYMhkM_y1sQQeu1yCPR.dH.O4utpQlD4tqUk76EXP0c2Hv6e
[Tue Jul 07 2020 11:53:06.400]  LOG      orgId 00D6D00000010zXUAQ
[Tue Jul 07 2020 11:53:06.410]  LOG      userAgent SalesforceMobileSDK/8.1.0 iOS/13.5 (iPhone) Lumary/14.8(122) ReactNative uid_4D68D07F-1A05-4F9B-8DBA-891EBA5CF2E5 ftr_UA.US Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
[Tue Jul 07 2020 11:53:06.430]  LOG      instanceUrl https://data-innovation-5107-dev-ed.cs73.my.salesforce.com

**Comment by wmathurin** [comment]
SDK 8.2 works with RN 0.62.2, but SDK 8.1 works with RN 0.61.3 (https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/blob/v8.1.0/package.json#L42).

Record ids have two representations (15 characters and 18 characters long), the longer one is case insensitive. To learn more on that topic see: http://varasi.com/uncategorized/dealing-with-15-and-18-character-salesforce-record-ids/

**Comment by marlonatlumary** [comment]
@wmathurin  Thanks down upgraded to 0.61.3 SyncDown is work
