### ISSUE TITLE
Usage of the "parentSoupEntryId" capability to track local Parent/Child relationships

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-ReactNative#190]
I am currently trying to get my head around what is the best way to track relationships between records that have been created locally and have yet to be synced (such as `Account` and `Contact`, via `ContactId`).

I had a read at this page of the documentation:
https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/offline_functions.htm?search_text=relationship

> SmartStore also lets you track inter-object relationships. For example, imagine that you create a product offline that belongs to a catalog that doesn’t yet exist on the server. You can capture the product’s relationship with the catalog entry through the parentSoupEntryId field. Once the catalog exists on the server, you can capture the external relationship by updating the local product record’s parentExternalId field.

It seems to be useful for what I am trying to achieve, but I cannot find any reference elsewhere for the `parentSoupEntryId` (even in this repo, or in the iOS repo).

Is this still supported?

**Comment by wmathurin** [comment]
The documentation is showing a possible approach you could follow in your application. We don't have sync targets for multi-level syncs in the SDK and we don't have example in our sample apps either.
