### ISSUE TITLE
JSON_PARSER_ERROR: Cannot deserialize instance of date from START_OBJECT value

### ISSUE THREAD

**Issue by JimBTek** [forcedotcom/SalesforceMobileSDK-ReactNative#194]
**Current Versions**
SDK: v8.1.0
React Native: 0.61.3
iOS: 13.5+

**Prior Versions:**
SDK: v7.1.2
React Native: 0.56.1
iOS: 13.3+

I saw your comment on #132 thanks for sorting that out.  We are noticing that the same code we had on SDK 7.1.2 is now failing on 8.1.0.  We (@Jc160 ) use momentjs to calculate a date for users and pre-populate it, allowing them to override it.  It calculates out +1 month etc. from today. We ensure it is a valid date to momentjs.  If our logic determines the date should be null, it inconsistently sends to Salesforce an empty array (`"Next_Calibration_Due__c": {}, `)instead of a date and throws an error. Also we were relying on the SDK date formatting before vs. controlling the format ourselves. We were just using momentjs to make sure it was a valid date, and let the SDK handle it. It appears that this may not work the same anymore. 

`"last_error": "{\n body = (\n {\n errorCode = "JSON_PARSER_ERROR";\n message = "Cannot deserialize instance of date from START_OBJECT value { or request may be missing a required field at [line:1, column:166]";\n }\n );\n httpHeaders = {\n };\n httpStatusCode = 400;\n referenceId = a083Z00000JVBb7QAH;\n}",
"sync_id": 948,
"As_Found__c": "N/A",
"Work_Order__c": "a0D3Z00000NzquPUAR",
"Next_Calibration_Due__c": {},
"LastModifiedDate": "2020-07-17T17:27:41.000+0000",`

We are having a lot of trouble consistently reproducing this issue to find a root cause. Happy to dig around and test further if you guys have ideas.

Thanks!

**Comment by wmathurin** [comment]
That's an error coming back from the server.
It looks very similar to https://salesforce.stackexchange.com/questions/116158/json-cannot-deserialize-instance-of-date-from-value-string

**Comment by JimBTek** [comment]
Hey @wmathurin, yeah we did find that error. It's sorting out how that empty array `{}` is getting set and sent to salesforce that is the mystery.  It is the only date field in the app that has this problem, but it's also the only one that get's cleared from a value to null.  We have several other date fields that either the user sets or the device sets that all sync over fine.  

Thanks for the quick response. we will report back here with further findings.

**Comment by JimBTek** [comment]
Also looks like if the SDK is hitting Salesforce with objects instead of strings there is a platform known issue with no fix:

https://trailblazer.salesforce.com/issues_view?id=a1p3A000000er80QAA

**Comment by JimBTek** [comment]
@wmathurin so it looks like the SDK may have previously helped with format mismatches on Date fields. We changed to storing the date as a string vs integer as well as did final format checking to make sure it matched what salesforce needs and the error went away.   It's just weird that we had not touched this code during the SDK upgrade and the error appeared.  I am closing this issue. Thank You
