### ISSUE TITLE
Syncing Related Records

### ISSUE THREAD

**Issue by StanislauTarazevich** [forcedotcom/SalesforceMobileSDK-ReactNative#202]
I'm trying to implement syncing related records in react native SDK following this manual: https://workbench.developerforce.com/query.php?qrjb=eyJRQl9vYmplY3Rfc2VsIjoiTm90ZSIsIlFCX2ZpZWxkX3NlbCI6WyJCb2R5IiwiQ3JlYXRlZERhdGUiLCJJZCIsIlBhcmVudElkIl0sIlFCX29yZGVyYnlfZmllbGQiOiIiLCJRQl9vcmRlcmJ5X3NvcnQiOiJERVNDIiwiUUJfbnVsbHMiOiJGSVJTVCIsIlFCX2xpbWl0X3R4dCI6IiIsIm1hdHJpeF9yb3dzIjoiIiwibWF0cml4X2NvbHMiOiIiLCJudW1GaWx0ZXJzIjoiMSIsInNvcWxfcXVlcnkiOiJTRUxFQ1QgQm9keSxDcmVhdGVkRGF0ZSxJZCxQYXJlbnRJZCBGUk9NIE5vdGUifQ%3D%3D#qr

This manual id for native but it looks like I can just pass `target` to `syncUp` function and it will work.
But it doesn't worn on both iOS and Android.

On Android I get following error:
`"java.lang.IllegalArgumentException: No enum constant com.salesforce.androidsdk.mobilesync.target.SyncDownTarget.QueryType.parentChildren`

And on iOS app just crashes without any logs.

It there a support for syncing related records in react native sdk and is there a documentation for it?

**Comment by wmathurin** [comment]
What version of Mobile SDK are you using?
We have a schema validator to validate the json used for defining syncs (https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/offline_config_validator.htm). It's the json you would use in a syncs config file or if defining the sync programmatically in a React Native or hybrid app.

**Comment by wmathurin** [comment]
There was a discrepancy between iOS and Android that we fixed for 8.0 (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3086/commits/6d5bf489ccdd585a3a83a7088a378ee6723b9714).
