### ISSUE TITLE
credentials.clientId cannot be nil or empty

### ISSUE THREAD

**Issue by AlkanV** [forcedotcom/SalesforceMobileSDK-ReactNative#203]
Hello, i am trying to create a demo connected app.

I have changed relevant credentials in `bootconfig.plist` but when i try to run the app it throws following exception and crash the app.

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'credentials.clientId cannot be nil or empty'`

I just check everywhere on internet but no chance. 
Is there anything i miss ?

Thank you for your help.

**Comment by wmathurin** [comment]
Could you paste your bootconfig.plist here (edit the parts you want to keep private)?

**Comment by AlkanV** [comment]
Hello, thank you for your message, below you can find my `bootconfig.plist`

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>remoteAccessConsumerKey</key>
	<string>3MVG..............qEZzkS2LMRVVIcU...............GILp2nhSU18W7V.............r</string>
	<key>oauthRedirectURI</key>
	<string>testapp:///local/callback/oauth/done</string>
	<key>oauthScopes</key>
	<array>
		<string>web</string>
		<string>api</string>
	</array>
	<key>shouldAuthenticate</key>
	<true/>
</dict>
</plist>

```

ps: remoteAccessConsumerKey are filtered for security purpose.

**Comment by wmathurin** [comment]
So you created an application using forcereact on ios.
You were able to launch it and login without issues.
Then you created a new connected app.
You substituted the remoteAccessConsumerKey and oauthRedirectURI into the bootconfig.plist.
And now the app is crashing? 
The crash only happens on iPhone 11.
What version of Mobile SDK are you using? What version of XCode are you using?

**Comment by AlkanV** [comment]
Hello, thank you for you answer, on the iPhone 11, it crash immediately after launching with the error i provided. But in the iPhone 8 and lower, i was able to open the app without any issue. I was using xCode v11.6 and MobileSDK v8.2. Now i am updating xCode which is provided 3 days ago, and will test it again.

**Comment by AlkanV** [comment]
I update xCode and it fixed. can be closed.

**Comment by wmathurin** [comment]
Good to hear.
