### ISSUE TITLE
Fail to build using Xcode 12

### ISSUE THREAD

**Issue by majidnawax** [forcedotcom/SalesforceMobileSDK-ReactNative#204]
<img width="818" alt="Screen Shot 2020-09-21 at 2 46 07 pm" src="https://user-images.githubusercontent.com/2876429/93733564-2f874e80-fc19-11ea-990d-ebdd321a5c77.png">

After upgrading xcode to latest (12) project fails to build.

mobile sdk version 8.2.0
react native info

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 284.39 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/majidnawazbhatti/.rvm/rubies/ruby-2.7.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Following is the error information
_

> Ld /Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SalesforceReact/SalesforceReact.framework/SalesforceReact normal (in target 'SalesforceReact' from project 'Pods')
>     cd /Users/majidnawazbhatti/Projects/kh-field-sales/ios/Pods
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios12.2-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk -L/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SalesforceReact -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SalesforceReact -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/DoubleConversion -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/FBReactNativeSpec -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/FMDB -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/Folly -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/MobileSync -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/RCTTypeSafety -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-Core -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-RCTAnimation -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-RCTBlob -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-RCTImage -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-RCTLinking -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-RCTNetwork -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-RCTSettings -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-RCTText -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-RCTVibration -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-cxxreact -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-jsi -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-jsiexecutor -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/React-jsinspector -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/ReactCommon -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SQLCipher -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SalesforceAnalytics -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SalesforceSDKCommon -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SalesforceSDKCore -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SmartStore -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/Yoga -F/Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/glog -filelist /Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SalesforceReact.build/Objects-normal/x86_64/SalesforceReact.LinkFileList -install_name @rpath/SalesforceReact.framework/SalesforceReact -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SalesforceReact.build/Objects-normal/x86_64/SalesforceReact_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -framework Foundation -framework MobileSync -framework React -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SalesforceReact.build/Objects-normal/x86_64/SalesforceReact_dependency_info.dat -o /Users/majidnawazbhatti/Library/Developer/Xcode/DerivedData/FieldSales-gnebegrqdnoomlcuwsokzucdglrv/Build/Products/Debug-iphonesimulator/SalesforceReact/SalesforceReact.framework/SalesforceReact
> 
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_SFSoupIndex", referenced from:
>       objc-class-ref in SFSmartStoreReactBridge.o
>   "_OBJC_CLASS_$_SFSDKDevAction", referenced from:
>       objc-class-ref in SalesforceReactSDKManager.o
>   "_OBJC_CLASS_$_SFSoupSpec", referenced from:
>       objc-class-ref in SFSmartStoreReactBridge.o
>   "_OBJC_CLASS_$_SFQuerySpec", referenced from:
>       objc-class-ref in SFSmartStoreReactBridge.o
>   "_OBJC_CLASS_$_SalesforceSDKManager", referenced from:
>       objc-class-ref in SFOauthReactBridge.o
>   "_OBJC_CLASS_$_SFUserAccountManager", referenced from:
>       objc-class-ref in SFOauthReactBridge.o
>   "_kSFNotificationUserDidLogout", referenced from:
>       -[SFOauthReactBridge logoutCurrentUser:callback:] in SFOauthReactBridge.o
>   "_kDefaultSmartStoreName", referenced from:
>       -[SFMobileSyncReactBridge storeName:] in SFMobileSyncReactBridge.o
>       -[SFSmartStoreReactBridge storeName:] in SFSmartStoreReactBridge.o
>       -[SFSmartStoreReactBridge internalCursorId:withGlobal:andStoreName:] in SFSmartStoreReactBridge.o
>   "_OBJC_CLASS_$_SFRestAPI", referenced from:
>       objc-class-ref in SFNetReactBridge.o
>   "_OBJC_CLASS_$_SFStoreCursor", referenced from:
>       objc-class-ref in SFSmartStoreReactBridge.o
>   "_OBJC_CLASS_$_SFRestRequest", referenced from:
>       objc-class-ref in SFNetReactBridge.o
>   "_OBJC_CLASS_$_SFSmartStore", referenced from:
>       objc-class-ref in SFMobileSyncReactBridge.o
>       objc-class-ref in SFSmartStoreReactBridge.o
>      (maybe you meant: _OBJC_CLASS_$_SFSmartStoreReactBridge)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

_

**Comment by majidnawax** [comment]
Already added the following patch in podfile to fix all other React Native pods

installer.pods_project.targets.each do |target|
      #Workaround for Xcode 12 and Auto-Linking
      if ['RNCAsyncStorage', 'RNGestureHandler', 'RNVectorIcons', 'RNCMaskedView', 'RNFileViewer',   'RNReanimated', 'RNScreens', 'RNShare', 'react-native-webview', 'react-native-safe-area-context',
         'react-native-restart', 'SalesforceReact', 'RNFS',  'RNSVG', 'RNDateTimePicker', 'react-native-geolocation', 'react-native-segmented-control', 'ReactNativeExceptionHandler'].include?(target.name) #list all affected target in the array
            target.build_phases.each do |build_phases|
                if build_phases.display_name == 'Frameworks'
                file_ref = installer.pods_project.new(Xcodeproj::Project::Object::PBXFileReference)
                file_ref.path = 'React.framework'
                file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
                build_phases.add_file_reference(file_ref)
                end
            end
        end

but SalesforceReact does not link with xcode 12

**Comment by AlkanV** [comment]
same error here.

**Comment by wmathurin** [comment]
I have generated an application using forcereact (version 8.2) and was able to build and run the application using XCode 12.
How did you generate your application?

**Comment by majidnawax** [comment]
I generated the application using forcereact (version 8.2) and was running the application fine on XCode 11. then upgraded my XCode to 12 and application threw the error above. 

There is linking issue with React Native 0.62.2 with XCode 12 for which I applied the recommended patch in podfile.


I also got the build to work but I had to manually add the  SalesforceReact framework as Target member into the following frameworks  in the pod project

1. SalesforceSDKCore.framework
2. SmartStore.framework

**Comment by majidnawax** [comment]
The issue is with the pod SalesforceReact. which is the main issue in this error and fails the build.

If I create a new sample template app using forcereact version 8.2.0 which does not have SalesforceReact pod in it then build is working fine..

Can you test your build by adding SalesforceReact pod

**Comment by wmathurin** [comment]
I'm not sure I follow.
When I create an application with forcereact, it uses the following podfile, which has SalesforceReact:
https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/ReactNativeTemplate/ios/Podfile#L49

What do you have in your podfile?

**Comment by majidnawax** [comment]
platform :ios, '12.2'

use_frameworks!

project '[ProjectName].xcodeproj'
target '[ProjectName]' do

source 'https://cdn.cocoapods.org/'

pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector'
pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec'
pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired'
pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
pod 'React', :path => '../node_modules/react-native/'
pod 'React-Core', :path => '../node_modules/react-native/'
pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'
pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
pod 'ReactCommon/callinvoker', :path => '../node_modules/react-native/ReactCommon'
pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native/ReactCommon'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

pod 'SalesforceSDKCommon', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceAnalytics', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'MobileSync', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceReact', :path => '../node_modules/react-native-force'


pod 'ReactNativeExceptionHandler', :podspec => '../node_modules/react-native-exception-handler/ReactNativeExceptionHandler.podspec'
pod 'RNFS', :path => '../node_modules/react-native-fs'
pod 'react-native-restart', :path => '../node_modules/react-native-restart'
  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-segmented-control', :path => '../node_modules/@react-native-community/segmented-control'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end

# Comment the following if you do not want the SDK to emit signpost events for instrumentation. Signposts are  enabled for non release version of the app.
 post_install do |installer|
    installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
               if config.name == 'Debug'
                   config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1','SIGNPOST_ENABLED=1']
                   config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-DDEBUG','-DSIGNPOST_ENABLED']
               else
                   config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
                   config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
               end
           end
       end
       installer.pods_project.targets.each do |target|
      #Workaround for Xcode 12 and Auto-Linking
      if ['RNCAsyncStorage', 'RNGestureHandler', 'RNVectorIcons', 'RNCMaskedView', 'RNFileViewer',   'RNReanimated', 'RNScreens', 'RNShare', 'react-native-webview', 'react-native-safe-area-context',
         'react-native-restart', 'react-native-camera', 'RNFS', 'SalesforceReact',  'RNSVG', 'RNDateTimePicker', 'react-native-geolocation', 'react-native-segmented-control', 'ReactNativeExceptionHandler'].include?(target.name) #list all affected target in the array
            target.build_phases.each do |build_phases|
                if build_phases.display_name == 'Frameworks'
                file_ref = installer.pods_project.new(Xcodeproj::Project::Object::PBXFileReference)
                file_ref.path = 'React.framework'
                file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
                build_phases.add_file_reference(file_ref)
                end
            end
        end
      if ['react-native-safe-area-context'].include?(target.name)
        target.build_phases.each do |build_phases|
          if build_phases.display_name == 'Frameworks'
            file_ref = installer.pods_project.new(Xcodeproj::Project::Object::PBXFileReference)
            file_ref.path = 'yoga.framework'
            file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
            build_phases.add_file_reference(file_ref)
          end
        end
      end
    end
  end

**Comment by wmathurin** [comment]
The main difference with the podfile that comes with generated app is the "Workaround for Xcode 12 and Auto-Linking". Could you try without it?

**Comment by thessler27** [comment]
See #209

**Comment by wmathurin** [comment]
The fix will be in the next version of Mobile SDK (version 9.0). See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/212

**Comment by Jalil-Irfan** [comment]
Hi I am running SDK 9.0 but still facing a similar issue please check my comment [here](https://github.com/bamlab/react-native-image-resizer/issues/216#issuecomment-801625011)
