### ISSUE TITLE
file is not a database, while compiling select count(*) from sqlite_master

### ISSUE THREAD

**Issue by AnilDeshpande** [forcedotcom/SalesforceMobileSDK-ReactNative#206]
When building react-native application using forcecreate, this happens while working with smart store. I have not seen this issue in iOS. Some body has suggested a solution (https://salesforce.stackexchange.com/questions/296851/file-is-not-a-database-error-conflict-between-sf-sdk-cordova-plugin-and-cord), but not sure why this problem happens and what exactly is the perfect solution.

**Comment by wmathurin** [comment]
You get that error when there is a mismatch between the database and the decryption key used to open it.
That happens when your code hangs on to instances to SmartStore across logout/login.

**Comment by AnilDeshpande** [comment]
Thanks, but why does it specifically happen in Android and not on iOS? And how do I get rid of it? How to make sure that code doesn't hold on to old login instance, how to clear it? Force logout?

**Comment by bhariharan** [comment]
@AnilDeshpande We upgraded the encryption scheme and keys for `Android`, but not on `iOS`. Logging out and logging back in should make the error go away.

**Comment by wmathurin** [comment]
Closing issue - does not seem like a SDK bug but rather a problem with the way app uses SmartStore.

**Comment by akshayajeevan** [comment]
Hi @wmathurin - Our app users are facing this error sometimes on their Samsung devices. 
Can you please share some info on this you have mentioned above -

> That happens when your code hangs on to instances to SmartStore across logout/login.

Even after uninstall and install the app, the error still persists.

**Comment by hcabral2024** [comment]
@akshayajeevan do you know how I can reproduce the error?
