### ISSUE TITLE
POST sendRequest from Android not sending body

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SalesforceMobileSDK-ReactNative#21]
I'm running into an issue trying with Android (working fine with iOS) posting to Salesforce with a request body.  For example, if I try to post a chatter Feed Element using sendRequest, it looks like the actual Salesforce API is called without the body and the request fails (same thing happens with custom apex REST APIs) -- again, this code works fine on iOS:

Note that I've simplified the variables below for this issue.
```
var endPoint = '/services/data';
var path = '/v35.0/connect/communities/'+communityID+'/chatter/feed-elements';
var body = { 
  body: { messageSegments: [ { type: 'Text', text: 'Hello from Android!' } ] }, // <-- updated
  feedElementType: 'FeedItem',
  subjectId: subjectId,
  visibility: 'AllUsers' 
}
forceClient.sendRequest(
  endPoint,
  path,
  (resp) => {
    // success code here
    console.log(resp);
  },
  (err) => {
    // error code here
    console.log(err);
  },
  'POST',
  body
);
```

Android Studio shows this in the log:
```
SalesforceNetReactBridge.sendRequest called: {"endPoint":"/services/data","path":"/v35.0/connect/communities/0DB6100000000KLGAY/chatter/feed-elements","method":"POST","queryParams":{"body":{"messageSegments":[{"type":"Text","text":"Hello from Android!"}]},"feedElementType":"FeedItem","subjectId":"a0261000001lyo8AAA","visibility":"AllUsers"},"headerParams":{},"fileParams":{}}
```

The following response comes back:
```
[{"errorCode":"MISSING_ARGUMENT","message":"No attachment found and body is empty. Provide a non-empty 'text' parameter, or a rich input including non-empty message segments. If providing rich JSON/XML input in REST, make sure to include Content-Type header. In multipart REST, include the Content-Type in the part."}]
```

**Comment by vinodr** [comment]
Looks like you have an extra closing bracket the end of messageSegments. If that's not it, can you try putting the keys in quotes as in the examples here and try again ? 
https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_feed_element.htm

**Comment by rgoldiez** [comment]
@vinodr - You're right and that's what I get for not simply copying and pasting into this issue.  I edited my original post to correctly (I think) compose the JSON body.  I want to re-iterate, though, that this works fine in iOS with the React Native / SF SDK.  However, it breaks with Android. 

Let me know if you want me to fork the https://github.com/forcedotcom/SmartSyncExplorerReactNative and demonstrate the issue there.

**Comment by vinodr** [comment]
@rgoldiez I am not currently using this library on Android, so can't test it. I went thru the following file which I think is making the request in the SDK but couldn't find anything that might be causing this issue: https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java

Also, can you compare the message payload being sent out from the iOS app with the Android ?

**Comment by rgoldiez** [comment]
@vinodr - Thanks for the feedback.    I don't see any difference in the message payload between iOS and Android, but these are `console.log()` in `react.force.common.js` before passing over the bridge to the native side.

I'll take a look at the java side, as you pointed out but that part is a bit greek to me.  

Separately, I see you're with Kenandy... you may have seen me in one of the customer videos that plays on the TV in the lobby area.  I'll shoot you an email separately. 

```
SFNetReactBridge.sendRequest called: {"endPoint":"/services/data","path":"/v35.0/connect/communities/0DB6100000000KLGAY/chatter/feed-elements","method":"POST","queryParams":{"body":{"messageSegments":[{"type":"Text","text":"Hello from iOS"}]},"feedElementType":"FeedItem","subjectId":"a0261000001lyo8AAA","visibility":"AllUsers"},"headerParams":{},"fileParams":{}}
```

**Comment by vinodr** [comment]
Yes, I have seen you. You can email me at vinod.rondla@kenandy.com.

**Comment by rgoldiez** [comment]
It seems that the issue is [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java#L137) and [here]( https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java#L170).  It appears that the sendRequest method on the native side is only prepared to accept a simple JSON object `{string: string}` and not something more complex, as you need to post a chatter message and other standard APIs.

**Comment by vinodr** [comment]
Ahh..good find. I guess an issue needs to be filed at https://github.com/forcedotcom/SalesforceMobileSDK-Android

**Comment by rgoldiez** [comment]
@vinodr - Good idea.  I'll do that now.

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1370).
