### ISSUE TITLE
Recommended way to store files (PDF, DOC, XLS)

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/SalesforceMobileSDK-ReactNative#211]
What is the recommended way to store such assets (PDF, DOC, XLS...)? Is it possible to store them encrypted using the SmartStore (`externalStorage`?) or is it not supported by the Mobile SDK?

Thanks

**Comment by bhariharan** [comment]
@jpmonette This forum is reserved for issues with our code. For generic questions, please use `Salesforce Stack Exchange` instead.
