### ISSUE TITLE
In-App dev screen not accessible when implementing React Native Screens

### ISSUE THREAD

**Issue by lchnnl** [forcedotcom/SalesforceMobileSDK-ReactNative#216]
Hey

I found out that the Salesforce In-App dev screen is not showing in _Android_ when I press the CMD-M key. This happens because I have implemented react-native-screens (https://reactnavigation.org/docs/native-stack-navigator/). React native screens is our preferred way of creating screens, because it allows us to create formsheets as screens.

**packages**
Salesforce Mobile SDK: v8.3
React Native: v0.63.2
@react-navigation/stack: ^5.6.2
@react-navigation/native: ^5.6.1
react-native-screens: ^2.9.0

**StackNavigator.tsx**
```
...
enableScreens();
const Stack = createNativeStackNavigator();
...
<Stack.Screen
   name="MyComponent"
   component={MyComponent}
   options={{
     stackPresentation: "formSheet",
      ...
   }}
/>
```

**Steps to reproduce / debugging**
Just simply build the app using the default CLI command. use the 'createNativeStackNavigator' to build the stack screens.
Run the app in Android. You'll see that the app will build nicely.

When pressing the CMD-M key combination (https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/tools_dev_support.htm) the regular React Dev Menu is shown and not the SF dev Menu.

During debugging it turns out that android app, due to the fact we are using react-native-screens, will actually enter the `showOverflowMenu()` method of com.swmansion.rnscreens.ScreenStackHeaderConfig file.
![image](https://user-images.githubusercontent.com/3322365/106294294-4b49d380-624f-11eb-85f8-bf3326ee3b56.png)

The `onKeyUp()` method of com.salesforce.androidsdk.ui.SalesforceActivityDelegate file was never reached. 

![image](https://user-images.githubusercontent.com/3322365/106294848-f65a8d00-624f-11eb-9693-cc6f64ded66b.png)

**Workaround**
The workaround we implemented is to override the `onKeyUp()` method in our MainActivity and tell it to listen to a key combination that is **not** CMD-M. Then afterwards to show the Salesforce InApp Dev menu. E.g.

![image](https://user-images.githubusercontent.com/3322365/106295268-80a2f100-6250-11eb-9171-d979b7eb7fd5.png)

It works, but is there any chance this will be fixed in the next release?

**Comment by wmathurin** [comment]
Our next release is almost ready to ship so new changes are unlikely to be part of it.
We will try to have a look afterwards.

**Comment by gkotula** [comment]
Hi @lchnnl Are you still experiencing this issue with the latest MobleSDK version?

**Comment by wmathurin** [comment]
Closing since there is a simple work around that application can implement.
