### ISSUE TITLE
Including dist/ in repository

### ISSUE THREAD

**Issue by rpander93** [forcedotcom/SalesforceMobileSDK-ReactNative#219]
Hi there,

Thanks for the new release. I wonder why you've chosen to require users to build the dist/* folder locally? I'd expect these files to be published with the package as is common practices with node modules.

**Comment by wmathurin** [comment]
The thing is we are not publishing the package to npm. Instead the forcereact generated apps consume it directly from github. So that would mean checking in the (generated) dist package to git - we try to only check in source code and not derived artifacts.

**Comment by wmathurin** [comment]
Fixed with https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/223 (will be in our next release).
