### ISSUE TITLE
RNC maskedview Undefined symbols for architecture x86_64 in xcode 12

### ISSUE THREAD

**Issue by crglketan** [forcedotcom/SalesforceMobileSDK-ReactNative#220]
Project works in android but showing error for @react-native-community/masked-view in xcode12, I also tried to refer [linking](https://reactnative.dev/docs/linking-libraries-ios) documentation but step 1 requires Libraries folder which I don't see in ios folder  

```
"@react-native-community/masked-view": "^0.1.10",
"@react-navigation/native": "^5.9.2",
"@react-navigation/stack": "^5.14.2",
"create-react-class": "^15.6.3",
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-force": "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v8.3.0",
"react-native-gesture-handler": "^1.10.1",
"react-native-reanimated": "^1.13.2",
"react-native-safe-area-context": "^3.1.9",
"react-native-screens": "^2.17.1",
"typescript": "^3.9.3"
```

<img width="1148" alt="Screenshot 2021-02-13 at 6 52 22 PM" src="https://user-images.githubusercontent.com/78795716/107851061-02884200-6e2d-11eb-821c-85a6e15d4c86.png">

**Comment by wmathurin** [comment]
Please upgrade to Mobile SDK 9.0 (released a few days ago).
Applications generated with [forcereact v9.0.0](https://www.npmjs.com/package/forcereact/v/9.0.0) auto-link their dependencies.
