### ISSUE TITLE
"Unsupported URL" error on iOS when SOQL query contains newlines

### ISSUE THREAD

**Issue by patrickgalbraith** [forcedotcom/SalesforceMobileSDK-ReactNative#227]
Looks like the iOS Mobile SDK doesn't work with line breaks in the SOQL query, however the Android SDK does.

Might be worth stripping line breaks from the SOQL query automatically, or maybe just documenting this limitation somewhere.

Related: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2569

**Comment by wmathurin** [comment]
Will be fixed in our upcoming release (10.1). See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3525.
