### ISSUE TITLE
Compatibility with react-native-unimodules

### ISSUE THREAD

**Issue by patrickgalbraith** [forcedotcom/SalesforceMobileSDK-ReactNative#228]
Because this project generates a very customized react-native setup, I had to make a bunch of changes to get unimodules to work. 

Since Expo provide a lot of popular packages for the react-native ecosystem I think it would be good to integrate `react-native-unimodules` out of the box, or provide documentation on how to integrate it.

It works fine on Android out of the box. But for iOS I had to modify `AppDelegate.m` and change the `setupRootViewController` method to use `RCTBridge`. However by re-initialising the bridge after login/logout this causes the react native app to get reloaded (not a problem in my case). However I am thinking there might be a better way and would be keen for any ideas you might have regarding this.

```objectivec
- (void)setupRootViewController
{
    RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:self.launchOptions];
    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                 moduleName:@"MyApp"
                                                 initialProperties:nil];
    rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

    UIViewController *rootViewController = [UIViewController new];
    rootViewController.view = rootView;
    self.window.rootViewController = rootViewController;
}
```

I also had to remove the `use_frameworks` line from the `Podfile`, and add the following:

```
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNScreens') || pod.name.eql?('RNCMaskedView')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end

    if pod.name.eql?('SalesforceAnalytics') || pod.name.eql?('FMDB') || pod.name.eql?('SQLCipher')  || pod.name.eql?('SalesforceSDKCore')  || pod.name.eql?('SalesforceSDKCommon')
      def pod.build_type
        Pod::BuildType.static_framework
      end
    end
  end
end
```

**Comment by patrickgalbraith** [comment]
Storing the bridge in the AppDelegate seems to fix the bundle reloading during login/logout:

```
@interface AppDelegate () <RCTBridgeDelegate>

@property (nonatomic, strong) UMModuleRegistryAdapter *moduleRegistryAdapter;
@property (nonatomic, strong, readwrite) RCTBridge *bridge;

@end

@implementation AppDelegate

// ...

- (void)setupRootViewController
{
    if (self.bridge == NULL) {
        self.bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:self.launchOptions];
    }

    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:self.bridge
                                                 moduleName:@"MyApp"
                                                 initialProperties:nil];
    rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

    UIViewController *rootViewController = [UIViewController new];
    rootViewController.view = rootView;
    self.window.rootViewController = rootViewController;
}
```

**Comment by gkotula** [comment]
Hi @patrickgalbraith,

Unfortunately, supporting every popular React Native/JS framework is not feasible for us -- even from an example/documentation standpoint.

We are aware of issues that arise with `use_frameworks!` in the Podfile, but we cannot yet commit to a timeframe to deliver a fix for that.

**Comment by wmathurin** [comment]
Please try Mobile SDK 10.2 where we no longer use use_frameworks in the Podfile.
