### ISSUE TITLE
SSL pinning.

### ISSUE THREAD

**Issue by anishtr4** [forcedotcom/SalesforceMobileSDK-ReactNative#231]
Hi Team,
It seems SSl pinning on MobileSdk doesn't support by salesforce , is there any progress made on this ? Is there any documentation available for the same.

**Comment by wmathurin** [comment]
You can always use https://github.com/datatheorem/TrustKit. We have used it for internal apps.

**Comment by anishtr4** [comment]
@wmathurin 

I have tried the Trustkit with the following approach 
NSDictionary *trustKitConfig =
  @{
    kTSKSwizzleNetworkDelegates: @NO,
    kTSKPinnedDomains : @{
            @"myapp.salesforce.com" : @{
                    kTSKExpirationDate: @"2017-12-01",
                    kTSKPublicKeyHashes : @[
                            @"HXXQgxueCIU5TTLHob/bPbwcKOKw6DkfsTWYHbxbqTY=",
                            @"0SDf3cRToyZJaMsoS17oF72VMavLxj/N7WBNasNuiR8="
                            ],
                    kTSKEnforcePinning : @NO,
                    },
            @"yahoo.com" : @{
                    kTSKPublicKeyHashes : @[
                            @"TQEtdMbmwFgYUifM4LDF+xgEtd0z69mPGmkp014d6ZY=",
                            @"rFjc3wG7lTZe43zeYTvPq8k4xdDEutCmIhI5dn4oCeE=",
                            ],
                    kTSKIncludeSubdomains : @YES
                    }
            }};
    
    [TrustKit initSharedInstanceWithConfiguration:trustKitConfig];


Is this only configuration which we have to do for pinning right.

When I tried using a usual fetch like below with different domain it does return result. But It should not return data rather should give error as we are using a public key of a our salesforce server/instance in trust kit.

fetch(‘https://busdue.com/‘)
.then((res) => {        console.log('**************')        console.log(res)        console.log('**************')        setValidationMsg('Valid certificate, connected.')        setValidationStatus('success')      })      .catch(() =>{        
setValidationMsg('Certificate does not match, connection refused')        setValidationStatus('failed')    
  })

Would you mind to share price of code which you have used in internal app?. Couldn’t find any tutorial related to salesforcesdk and Trustkit.

**Comment by anishtr4** [comment]
I was using "kTSKSwizzleNetworkDelegates" in the trustKitConfig which was not working as expect.  Now  I have  like TSKPinningValidator instance  below. Does this intercept all the connection from  the SDKs to enable ssl pinning ? or is there any exceptions ?


- (void)URLSession:(NSURLSession *)session 
              task:(NSURLSessionTask *)task 
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge 
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler {
{
    TSKPinningValidator *pinningValidator = [[TrustKit sharedInstance] pinningValidator];
    // Pass the authentication challenge to the validator; if the validation fails, the connection will be blocked
    if (![pinningValidator handleChallenge:challenge completionHandler:completionHandler])
    {
        // TrustKit did not handle this challenge: perhaps it was not for server trust
        // or the domain was not pinned. Fall back to the default behavior
        completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
    }
}

**Comment by wmathurin** [comment]
The whole SDK is open source so you can see exactly what it does. The class responsible for networking is: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFNetwork.m

**Comment by anishtr4** [comment]
@wmathurin  , Would you mind to share your trust kit implementation  code. Jus to to refer, could't find any proper documentation anywhere. It will be really helpfull.

**Comment by anishtr4** [comment]
@wmathurin 
The above "didReceiveChallenge" seems to be not working and unpinned connections still allowed. It would be great if you can share piece of code that you guys used to integrate Trustkit in your internal app.

**Comment by wmathurin** [comment]
@bhariharan anything we can share?

**Comment by bhariharan** [comment]
@anishtr4 We can't share internal code. However, the code sample available in `TrustKit` [here](https://github.com/datatheorem/TrustKit#sample-usage) is self-explanatory, and should be able to help.

**Comment by hmkcfs** [comment]
@wmathurin , We are in the process of implementing SSL pinning for our application and have successfully added a certificate for the development sandbox environment. However, we have encountered a potential issue.

Our application is initially configured to connect to the development sandbox, and the corresponding certificate has been pinned. That said, the SDK allows users to switch the server environment. For example, to a QA sandbox. In such cases, users are still able to authenticate via SSO, even though the application has not been configured with the QA sandbox certificate.

Given this scenario, would it be advisable to configure all possible sandbox certificates within the application? Alternatively, is there a way to utilize wildcard certificates for Salesforce sandboxes to streamline this process? We would appreciate your input on the best approach to handle this situation.
