### ISSUE TITLE
Unknown soup serviceappointments at character 21

### ISSUE THREAD

**Issue by AnilDeshpande** [forcedotcom/SalesforceMobileSDK-ReactNative#233]
Issues observed in - Android
How to Reproduce - Install the react native Android app, and use the application. Then clear the application cache and memory. and Relaunch the app. We get an error - "Unknown soup <soupname> at character 21". App basically crashed with this error in stack trace. 

After killing the app and re-launching the application, this issue doesn't arise. Once the app is killed and relaunched we don't see this issue again.

**Comment by wmathurin** [comment]
What did you mean by clear the application caches?
If you delete the soup (i.e. table) from smartstore, it makes sense for the app to complain about not finding it.
It probably works on restart because you have code run only during app initialization that creates the soup if not found.

**Comment by AnilDeshpande** [comment]
What did you mean by clear the application caches?

Go to app info, In Android device (settings), there cleat the cache and storage. Basically make the app clean slate. Then launch the application.

My expectation is, app should lanuch, ask for login, and just proceed as usual, create the soups as part of normal intialization. But I am getting this crash in console log.

**Comment by wmathurin** [comment]
And you used the basic react native template?

**Comment by AnilDeshpande** [comment]
Yes, the usual Salesforces's react-native template that gets created by the "forcereact" CLI.
