### ISSUE TITLE
Push notification issue with cold boot

### ISSUE THREAD

**Issue by anishtr4** [forcedotcom/SalesforceMobileSDK-ReactNative#234]
Hi Team,
I have created a  "forcereact" app with the push notification feature integrated successfully. But when I tested the application I came across an issue described below.

**Scenario(A)**

- The app is closed and not available in the background or  foreground.
- The user received a notification(local).
- The user clicks on the notification.
- Application opens up from cold boot and we should get the notification details/data by using the method " `PushNotificationIOS.getInitialNotification()`" provided in the push notification library but in the force react app this method always returns 'null'

We have created a vanilla react-native application to check if this is an issue with the push notification library and did the same implementation as we did for "_forcereact_" app. We did receive the notification data in the application by using " `PushNotificationIOS.getInitialNotification()`" method without any issue in the above **Scenario(A)**, hence it looks like the issue is not with the push notification library/react-native

Please find the vanilla react native application and "_forcereact_" application GitHub below with the same integration.

Forcereact - https://github.com/naveenr1592/sampleNotification
Vanila React ntive - https://github.com/naveenr1592/notificationtest

XCODE : 12.4
Forcereact - 9.1.1

**Comment by anishtr4** [comment]
@wmathurin, Can some one please look into this. ?

**Comment by anishtr4** [comment]
@bhariharan  @wmathurin 

Can some one please look into it.

**Comment by wmathurin** [comment]
For notifications to work, there is a line of code to uncomment in AppDelegate.m:
* https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m#L67
Did you do that already?

**Comment by anishtr4** [comment]
Yes , already did that and notification works, but the issue is only with when trying to get notification data from cold boot as mentioned below.

**Comment by anishtr4** [comment]
@wmathurin  Any updates on the above issue.

**Comment by wmathurin** [comment]
Are notifications pushed by Salesforce server or a third party server?

**Comment by wmathurin** [comment]
Closing. Re-open if issue still occurs with latest Mobile SDK (12.0.1).
