### ISSUE TITLE
Push notifications not delivered on Android Device

### ISSUE THREAD

**Issue by shubhang7g** [forcedotcom/SalesforceMobileSDK-ReactNative#239]
We have developed a React Native mobile app. For multiple updates in Salesforce, we are sending push notifications on this mobile app from apex with the help of standard "PushNotification" class methods as mentioned in below official link:- https://developer.salesforce.com/docs/atlas.en-us.232.0.pushImplGuide.meta/pushImplGuide/pns_apex_trigger.htm

Now these notifications are working fine on iOS, but they are **not delivered on Android** device and even logs were not generated on the firebase console. In salesforce debug logs, we got PUSH_NOTIFICATION_SENT successfully.

We tried sending push notifications from the third party then logs were generated on the firebase console and notifications were delivered to the android device.

After trying multiple ways on salesforce, we **directly called the FCM** endpoint (https://fcm.googleapis.com/fcm/send) from the apex. We have hardcoded device token generated on salesforce in the body of the request and we have successfully received notifications on android devices and even logs generated on the firebase.

So coming back to the original question, has anyone got **push notifications delivered on Android** devices in React Native app by using standard "PushNotification" class methods? If yes, please let me know any missing steps on salesforce or android.

Alternatively, is there a **way to get/query device tokens** dynamically in apex based on user? As we cannot hard code device tokens for real implementation.

Also, we are using **Salesforce mobile SDK for React-Native version 8.20**, let us know if you have encountered any issues with it.

**Comment by romanravkov** [comment]
> We have developed a React Native mobile app. For multiple updates in Salesforce, we are sending push notifications on this mobile app from apex with the help of standard "PushNotification" class methods as mentioned in below official link:- https://developer.salesforce.com/docs/atlas.en-us.232.0.pushImplGuide.meta/pushImplGuide/pns_apex_trigger.htm
> 
> Now these notifications are working fine on iOS, but they are **not delivered on Android** device and even logs were not generated on the firebase console. In salesforce debug logs, we got PUSH_NOTIFICATION_SENT successfully.
> 
> We tried sending push notifications from the third party then logs were generated on the firebase console and notifications were delivered to the android device.
> 
> After trying multiple ways on salesforce, we **directly called the FCM** endpoint (https://fcm.googleapis.com/fcm/send) from the apex. We have hardcoded device token generated on salesforce in the body of the request and we have successfully received notifications on android devices and even logs generated on the firebase.
> 
> So coming back to the original question, has anyone got **push notifications delivered on Android** devices in React Native app by using standard "PushNotification" class methods? If yes, please let me know any missing steps on salesforce or android.
> 
> Alternatively, is there a **way to get/query device tokens** dynamically in apex based on user? As we cannot hard code device tokens for real implementation.
> 
> Also, we are using **Salesforce mobile SDK for React-Native version 8.20**, let us know if you have encountered any issues with it.

I was faced with the same problem. If you take a look in Android SDK you can see that SDK works with notifications differently than firebase. SF sends payload in their own format because it can be encoded and etc. and a device can't display these notifications.
[https://developer.salesforce.com/docs/atlas.en-us.pushImplGuide.meta/pushImplGuide/connected_app_custom_push_payload_android.htm](Payload Doc)

You can find advice in MainApplication.java.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/46380664/152534340-5965f814-3ca5-4e48-b620-0ab7504e83b0.png">
`/android/app/src/...../MainApplication.java`

You need to implement your own notification receiver and improve it as you need.

So i can share my simple implementation for this receiver without any logic, only displaying.

`@Override
	public void onPushMessageReceived(Map<String, String> data) {
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
			int importance = NotificationManager.IMPORTANCE_DEFAULT;
			NotificationChannel channel = new NotificationChannel(
					"notificationChannelId", "Channel name", importance
			);
			channel.setDescription("description");
			NotificationManager notificationManager = getSystemService(NotificationManager.class);
			notificationManager.createNotificationChannel(channel);
		}

		NotificationManager mNotificationManager = (NotificationManager)
				this.getSystemService(Context.NOTIFICATION_SERVICE);

		PendingIntent contentIntent = PendingIntent.getActivity(this, 0,
				new Intent(this, MainActivity.class), 0);

		NotificationCompat.Builder mBuilder =
				new NotificationCompat.Builder(this, "notificationChannelId")
						.setSmallIcon(R.mipmap.ic_launcher)
						.setContentTitle(data.get("title"))
						.setContentText(data.get("body"))
						.setAutoCancel(true);

	
		mBuilder.setContentIntent(contentIntent);
		mNotificationManager.notify(0, mBuilder.build());
	}`

**Comment by gkotula** [comment]
Thank you for the detailed explanation @romanravkov !  Closing this issue due to lack of response from OP.
