### ISSUE TITLE
Red Screen of Death: Unhandled JS Exception: SyntaxError

### ISSUE THREAD

**Issue by davidfekke** [forcedotcom/SalesforceMobileSDK-ReactNative#24]
I just tried to create a new react_native app using the forceios command. When I use the `react-native run-ios` command, I am able to log into Salesforce, but once I get past the OAuth screens, I am getting the following error;

 `Unhandled JS Exception: SyntaxError`

I have not made any code changes, I am just trying to run the template from the forceios command.

What am I missing?

**Comment by bhariharan** [comment]
You haven't started the `react-packager CLI` before installing the app.

Here are the steps:
- Create a new `react_native` app using `forceios`.
- Navigate to the root folder of the generated app and run `npm start .`.
- Navigate to the `<app folder>/ios` and run `open <app name>.xcworkspace`.
- Run the app from within `Xcode`.
