### ISSUE TITLE
Community user login successfully and show a web page in webview instead of react native app home page

### ISSUE THREAD

**Issue by yxfeng-tw** [forcedotcom/SalesforceMobileSDK-ReactNative#240]
I am developing a react native app by using salesforce mobile sdk, and there is a problem for community user login.

Steps to reproduce:
1. Community user login through the specific url.
2. Login successfully, shows its web home page inside webview.

Expected:
1. Community user login through the specific url.
2. Login successfully, shows mobile app home page.

**Comment by atiqvia** [comment]
HI @yxfeng-tw I am seeing this behavior in a certain scenario when using the Mobile SDK user agent flow for authentication for a managed package user. Did you get this issue resolved?

**Comment by yxfeng-tw** [comment]
@atiqvia thanks, resolved already, the reason is I put a wrong url to login. For example, the login url should be `***.com/site`, but I put `***.com/site/s` instead.

**Comment by gkotula** [comment]
Apologies for the lack of reply, but it sounds like you were able to resolve the issue.  We are closing this issue, but if you are still experiencing problems, please reply here 👍
