### ISSUE TITLE
How to customize community user login page of salesforce mobile sdk-react native app

### ISSUE THREAD

**Issue by yxfeng-tw** [forcedotcom/SalesforceMobileSDK-ReactNative#241]
Steps to reproduce:
1. Community user login with specific url (Login page is Experience Builder Page)
2. login successfully and redirect to login page instead of home page

Expected:
- Community user login with specific url, login successfully and redirect to home page

Solution:
- Change the Login page to Default page

Questions:
- How to customize the login page?

**Comment by wmathurin** [comment]
Please see the documentation: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_customize_login.htm
