### ISSUE TITLE
Can't install v9.2.0 from git url with npm

### ISSUE THREAD

**Issue by mjmasn** [forcedotcom/SalesforceMobileSDK-ReactNative#244]
Looks like when installing from git url ie: `npm i -S git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v9.2.0`, npm clones the repo, installs dependencies, then builds the project.

Due to the `typescript@^4.1.2` dev dependency (and no lockfile), at this point the latest `4.4.x` typescript is installed, which then fails to build due to https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables

A quick workaround would be changing `error` to `error: any` in catch block arguments (there are 3 of these in src/react.force.util.ts), or pin TS to something pre 4.4.x - `"typescript": "4.3.5"` for instance.

In case it matters I'm using latest node / npm:
```
❯ node -v
v16.10.0
❯ npm -v
7.24.2
```

**Comment by wmathurin** [comment]
Typescript code fixed with https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/259
Will be in our next release.
