### ISSUE TITLE
Lack of proper call backs when data doesn't sync using smart store

### ISSUE THREAD

**Issue by AnilDeshpande** [forcedotcom/SalesforceMobileSDK-ReactNative#245]
1. Lack of proper Callbacks: We are been getting an error when something fails while data is getting synced. We are observing that when the data sync happens, some times we are getting an error. We want to handle that, but there is no clear way defined on how to do it. 
But we have not been able to catch it. Lack of call back is really making it more tricker.

Example 1:
const syncUp = forceUtil.promiserNoRejection(mobilesync.syncUp); return syncUp(false, {}, 'attachments', { mergeMode: mobilesync.MERGE_MODE.OVERWRITE, fieldlist, }).then(() => { console.log('syncUp completed or failed'); syncInFlight = false; emitSmartStoreChanged(); }).catch((error)=>{ console.log('TAG: Sync, FileScreen -AttachmentManager, function:syncUpAttachments, :',error); //TODO: Catch Not Working });;

Example 2:
const reSync = forceUtil.promiserNoRejection(mobilesync.reSync); return reSync(false, syncName).then(() => { syncInFlight = false; emitSmartStoreChanged(); }).catch((error)=>{ console.log('TAG: Sync, FileScreen -AttachmentManager, function:reSyncAttachments,:',error); //TODO: Catch Not Working });;
1.1 Potential bottle necks
1.1.1 Unable to delete synced photos :
Because of this we are unable to solve the another issue. We want to delete the images that have already been synced successfully so that we can avoid hitting SQLITE_DATABASE_FULL error. If we are not aware which photos are synced, we can not delete them from smart store.

1.2 Offline and Online
We have observed that when the WOs are being cancelled, especially in offline mode, when the mobile app comes back online the data doesn't get synced properly. We have not been able to observe what data actually gets synced to back end due to lack of proper call backs (issue reported in 1.1).

1.3 Discrepancy between data being stored in SmartStore Saved and actually synced (WIP)
We have observed that whatever the time stamp that we have saved saved in the smart store, when the data finally gets synced with the back end, we see that an extra time is added to the same that we have saved. That is if we have saved 11:23:32 as the time stamp, some times we observer that 11:28:32 (another extra five mins) of time is added. It is consistent.

2. Missing documentation on Promises on react-native-force forceUtil methods:
We have been trying to find the documentation which explains us methods that can be called on forceUtil and mobilesync.

import { smartstore, mobilesync, forceUtil, net } from 'react-native-force';

Other than promiser and promiserNoRejection what other option do we have.

const registerSoup = forceUtil.promiser(smartstore.registerSoup);
const getSyncStatus = forceUtil.promiser(mobilesync.getSyncStatus);

const syncDown = forceUtil.promiserNoRejection(mobilesync.syncDown);
const syncUp = forceUtil.promiserNoRejection(mobilesync.syncUp);
const reSync = forceUtil.promiserNoRejection(mobilesync.reSync);

3. Inconsistent behaviour being observed in creation on Smart Store soup in IOS & Android
When the app loads, the soups are created and all the data about SA and WO are stored in Soups. In iOS we that this happens, but in case of Android, it is not happening consistently. Thus in case of Android we have reported cases of data not being fetched from Smart Store on each screen and getting rendered there. This leads to a situation where missing Customer Name, Phone numbers are seen. Because our assumption that data is present in Smart store goes caput. The tricky part is why does this happen in Android only, why not iOS. It's the same code at react-native level from our side. It has got to do with SDK because that's where the difference lies.

3.1 Descrepency in Smart Store device database sizes
In Android starting time iself, the data base size start from 150MB, but in IOS it starts from 20MB. That's why we see this SQL_FULL error issue mainly in Android, but not in IOS.
There is no consistency in at what database size we start seeing SQL_FULL error. One it was being observed at 200 MB, another time it was observed at 150MB.
There is no call back at JavaScript level when SQL_FULL happens.
Even though the getDataBase size takes the name of the soup as argument, it displayed the over all data base size. It was nNot soup specific. This information is missing in documentation.

**Comment by gkotula** [comment]
Closing due to response inactivity.
