### ISSUE TITLE
App Crash when logout is executed in Android app

### ISSUE THREAD

**Issue by AnilDeshpande** [forcedotcom/SalesforceMobileSDK-ReactNative#248]
This is issue that is observed in Android only. When outh.logout is executed in Android. The app crashes instead of executing a success call back. In iOS the exact same code works perfectly fine.
Below the error message
![Screenshot 2021-10-21 at 11 16 09 AM](https://user-images.githubusercontent.com/7361268/138226415-83b2cbfb-d2b2-4918-9227-db0248f479f6.png)
 
It happens if logout is triggered when there is some kind of syncDown is still happening. I wanted to check whether there is a mechanism to hard stop all syncDowns, before I hit the logout, but there is no such option available.

**Comment by wmathurin** [comment]
We have not yet exposed those APIs to React Native.
Could you add a native logout handler and trigger the stop from there?

**Comment by gkotula** [comment]
Closing due to no response.
