### ISSUE TITLE
Inconsistent behaviour being observed in creation on Smart Store soup in IOS & Android

### ISSUE THREAD

**Issue by AnilDeshpande** [forcedotcom/SalesforceMobileSDK-ReactNative#250]
When the app loads, the soups are created and all the data about SA and WO are stored in Soups. In iOS we that this happens, but in case of Android, it is not happening consistently. Thus in case of Android we have reported cases of data not being fetched from Smart Store on each screen and getting rendered there. This leads to a situation where missing Customer Name, Phone numbers are seen. Because our assumption that data is present in Smart store goes caput. The tricky part is why does this happen in Android only, why not iOS. It's the same code at react-native level from our side. It has got to do with SDK because that's where the difference lies.

**Comment by wmathurin** [comment]
Have you looked at the logs or tried debugging? 
Mobile sync logs a lot of details about the data it is fetching. 
SmartStore is the database. If some writes fail for whatever reasons, they will be errors in the log.

Could you provide us more details? 
We don't know you application (what are SA or WO, the fields you mention, were are they supposed to come from).
Maybe you could tell us what kind of sync you are using, what kind of soups you have setup etc.

**Comment by AnilDeshpande** [comment]
SA - ServiceAppointment - one type of Salesforce Object.
WO - WorkOrder - one type of Salesforce Object. 
based on the logs I have seen, the syncDown method seems to be behaving inconsistently across platforms. On iOS we are not facing this issue. But on Android we have observed that we don't get syncDown success call backs for very long time. After killing the app and launching it two three times, then the syncDown seems to work correctly.

**Comment by wmathurin** [comment]
We have not seen the issue ourselves (or heard about a similar issue from other customers).
Do you see anything of interest in the logs?

**Comment by AnilDeshpande** [comment]
Yes...We have.
Have a look at this code. 
`import EventEmitter from './events';
import { smartstore, mobilesync, forceUtil, net } from 'react-native-force';
import { Alert } from 'react-native';

const registerSoup = forceUtil.promiser(smartstore.registerSoup);
const getSyncStatus = forceUtil.promiser(mobilesync.getSyncStatus);
const syncDown = forceUtil.promiserNoRejection(mobilesync.syncDown);
const syncUp = forceUtil.promiserNoRejection(mobilesync.syncUp);
const reSync = forceUtil.promiserNoRejection(mobilesync.reSync);

let syncName = 'SYNC_APPOINTMENTS';
let syncInFlight = false;
const eventEmitter = new EventEmitter();

const SMARTSTORE_CHANGED = 'smartstoreChanged';

function emitSmartStoreChanged() {
  eventEmitter.emit(SMARTSTORE_CHANGED, {});
}

function syncDownAppointments(soql_query, uniqueID) {
  syncName = uniqueID;
  console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncDownAppointments, message:  syncName:', syncName);
  if (syncInFlight) {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncDownAppointments, message:  Not starting syncDown - sync already in flight:');
    return Promise.resolve();
  }

  syncInFlight = true;
  const target = {
    type: 'soql',
    query: soql_query,
  };
  return syncDown(
    false,
    target,
    'serviceappointments',
    { mergeMode: mobilesync.MERGE_MODE.OVERWRITE },
    syncName
  )
    .then((res) => {
      syncInFlight = false;
      emitSmartStoreChanged();
      syncUpAppointments();
    })
    .catch((error) => console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncDownAppointments, message:  error in sync down', error));
}

function reSyncAppointments() {
  console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: reSyncAppointments, message:  syncName', syncName);
  if (syncInFlight) {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: reSyncAppointments, message:  Not starting reSync - sync already in fligtht');
    return Promise.resolve();
  }

  syncInFlight = true;
  return reSync(false, syncName)
    .then((res) => {
      console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: reSync, message:  completed res in resync', res);
      syncInFlight = false;
      emitSmartStoreChanged();
    })
    .catch((error) => {
      console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: reSync, message:  error', error);
    });
}

function syncUpAppointments() {
  if (syncInFlight) {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncUpAppointments, message:  Not starting syncUp - sync already in fligtht');
    return Promise.resolve();
  }
  const fieldlist = [
    'Beezr_Actual_Travel_Started__c',
    'Beezr_Actual_Travel_Completed__c',
    'Beezr_Appointment_Completed__c',
    'ActualStartTime',
    'ActualEndTime',
    'Status',
    'hasBeforePictures__c',
    'hasAfterPictures__c',

  ];
  syncInFlight = true;
  return syncUp(false, {}, 'serviceappointments', {
    mergeMode: mobilesync.MERGE_MODE.OVERWRITE,
    fieldlist,
  })
    .then((res) => {
      **console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncUpAppointments, message:  syncUp completed or failed syncUpAppointments', res);**
      syncInFlight = false;
      emitSmartStoreChanged();
    })
    .catch((error) => {
      console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncUpAppointments, message:  error', error);
    });
}

function createServiceSoup() {
  return registerSoup(false, 'serviceappointments', [
    { path: 'Id', type: 'string' },
    { path: 'Beezr_Actual_Travel_Started__c', type: 'string' },
    { path: 'Beezr_Actual_Travel_Completed__c', type: 'string' },
    { path: 'Beezr_Appointment_Completed__c', type: 'string' },
    { path: 'ActualStartTime', type: 'string' },
    { path: 'ActualEndTime', type: 'string' },
    { path: 'Status', type: 'string' },
    { path: 'SchedStartTime', type: 'full_text' },
    { path: 'hasBeforePictures__c', type: 'string' },
    { path: 'hasAfterPictures__c', type: 'string' },
    { path: '__local__', type: 'string' },
    { path: '__locally_created__', type: 'string' },
    { path: '__locally_updated__', type: 'string' },
    { path: '__locally_deleted__', type: 'string' },
    { path: '__sync_id__', type: 'integer' },
  ]).then(() => {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: createServiceSoup, message:  Service appointment soup created');
  }).catch((error)=>{
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: createServiceSoup, message:  error', error);//TODO: Catch is Working
  });;
}

function syncData() {
  return getSyncStatus(false, syncName).then((sync) => {
    if (sync == null) {
      return createServiceSoup();
    } else {
      return reSyncData();
    }
  });
}

function reSyncData() {
  return syncUpAppointments().then(reSyncAppointments);
}

function addStoreChangeListener(listener) {
  eventEmitter.addListener(SMARTSTORE_CHANGED, listener);
}

function saveAppointment(service, callback) {
  smartstore.upsertSoupEntries(
    false,
    'serviceappointments',
    service,
    (sucess) => {
      console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: saveAppointment, message:  Saving SA timestamps and status success', {
      "WorkOrderNumber": service[0].Beezr_Parent_Work_Order__r,
      "AppointmentNumber":service[0].AppointmentNumber,
      "Description": service[0].Description,
      "Beezr_Actual_Travel_Started__c": service[0].Beezr_Actual_Travel_Started__c,
      "Beezr_Actual_Travel_Completed__c":service[0].Beezr_Actual_Travel_Completed__c,
      "ActualStartTime":service[0].ActualStartTime,
      "ActualEndTime": service[0].ActualEndTime,
      "Beezr_Appointment_Completed__c": service[0].Beezr_Appointment_Completed__c,
      "Status": service[0].Status});

      callback();
      emitSmartStoreChanged();
    },
    (error) => {
      console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: saveAppointment, message:  Saving SA timestamps and status error', {
        "WorkOrderNumber": service[0].Beezr_Parent_Work_Order__r,
        "AppointmentNumber":service[0].AppointmentNumber,
        "Description": service[0].Description,
        "Beezr_Actual_Travel_Started__c": service[0].Beezr_Actual_Travel_Started__c,
        "Beezr_Actual_Travel_Completed__c":service[0].Beezr_Actual_Travel_Completed__c,
        "ActualStartTime":service[0].ActualStartTime,
        "ActualEndTime": service[0].ActualEndTime,
        "Beezr_Appointment_Completed__c": service[0].Beezr_Appointment_Completed__c,
        "Status": service[0].Status});
    }
  );
}

function addAppointment(successCallback, errorCallback) {
  const appointment = {
    Id: `local_${new Date().getTime()}`,
    Beezr_Actual_Travel_Started__c: null,
    Beezr_Actual_Travel_Completed__c: null,
    Status: null,
    attributes: { type: 'ServiceAppointment' },
    __locally_created__: true,
    __locally_updated__: false,
    __locally_deleted__: false,
    __local__: true,
  };
  smartstore.upsertSoupEntries(
    false,
    'serviceappointments',
    [appointment],
    (appointments) => {
      successCallback(appointments[0]), console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: addAppointment, message:  upsertSoupEntries success', appointments);
    },
    errorCallback
  );
}

function deleteAppointment(contact, successCallback, errorCallback) {
  smartstore.removeFromSoup(
    false,
    'serviceappointments',
    [contact._soupEntryId],
    successCallback,
    errorCallback
  );
}

function traverseCursor(
  accumulatedResults,
  cursor,
  pageIndex,
  successCallback,
  errorCallback
) {
  accumulatedResults = accumulatedResults.concat(
    cursor.currentPageOrderedEntries
  );
  if (pageIndex < cursor.totalPages - 1) {
    smartstore.moveCursorToPageIndex(
      false,
      cursor,
      pageIndex + 1,
      (cursor) => {
        traverseCursor(
          accumulatedResults,
          cursor,
          pageIndex + 1,
          successCallback,
          errorCallback
        );
      },
      errorCallback
    );
  } else {
    successCallback(accumulatedResults);
  }
}

function getAppointments(queryId, query, successCallback, errorCallback) {
  let querySpec;
  querySpec = smartstore.buildAllQuerySpec('SchedStartTime', 'ascending', 1000);

  const querySuccessCB = (contacts) => {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: getAppointments, message:  contacts in response:', contacts);
    successCallback(contacts, queryId);
  };

  const queryErrorCB = (error) => {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: getAppointments, message:  error:', error);
    errorCallback(error);
  };

  smartstore.querySoup(
    false,
    'serviceappointments',
    querySpec,
    (cursor) => {
      traverseCursor([], cursor, 0, querySuccessCB, queryErrorCB);
    },
    queryErrorCB
  );
}

function getAppointmentsForSelectedDate(
  queryId,
  query,
  successCallback,
  errorCallback
) {
  let querySpec;
  const match = `{serviceappointments:SchedStartTime}:${query}`;
  querySpec = smartstore.buildMatchQuerySpec(
    null,
    match,
    'ascending',
    100,
    'SchedStartTime'
  );

  const querySuccessCB = (contacts) => {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: getAppointmentsForSelectedDate, message: querySuccessCB contacts in response:', contacts);
    successCallback(contacts, queryId);
  };

  const queryErrorCB = (error) => {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: getAppointmentsForSelectedDate, message:  error:', error);
    errorCallback(error);
  };

  smartstore.querySoup(
    false,
    'serviceappointments',
    querySpec,
    (cursor) => {
      traverseCursor([], cursor, 0, querySuccessCB, queryErrorCB);
    },
    queryErrorCB
  );
}

export default {
  syncData,
  reSyncData,
  addStoreChangeListener,
  saveAppointment,
  getAppointmentsForSelectedDate,
  syncDownAppointments,
  createServiceSoup,
  getAppointments,
  addAppointment,
  deleteAppointment,
};
`

Now let me post the images of he logs as well.
This one is from Android
<img width="1776" alt="Screenshot 2021-11-11 at 10 02 42 AM" src="https://user-images.githubusercontent.com/7361268/141237754-2fdfedea-c848-41ec-ae49-b4618fb5d217.png">

This one is from iOS
<img width="1788" alt="Screenshot 2021-11-11 at 10 06 47 AM" src="https://user-images.githubusercontent.com/7361268/141238050-84720b9b-565f-4e45-a8ad-2b42f5ace364.png">

Can you observe the difference. In iOS (highlighted in red rectangle), we are getting the call back
 from sycnDown method. Bit in Android we are not getting this at all. It's the same react-native code on running on both Android and iOS. On iOS it is working fine, but on Android, it's not. Because of this we end up with a situation on Android where we are not sure whether have the data synced down in smart store or not.  I have highlighted the console log in bold in the code that seems to be not working in Android for your reference as well. 

The funny part is, after I kill the app two three times, and restart the app on Android, it seems to start working fine (as in  iOS). We have not changed any part of the code.

**Comment by gkotula** [comment]
Hi @AnilDeshpande, are you still encountering this issue?  It has been a while since we heard anything.

**Comment by wmathurin** [comment]
Closing for lack of response. Please open a new issue if you are still. having the same problem.
