### ISSUE TITLE
The use of `use_frameworks!`

### ISSUE THREAD

**Issue by mjmasn** [forcedotcom/SalesforceMobileSDK-ReactNative#252]
This might be more of a question for the https://github.com/forcedotcom/SalesforceMobileSDK-iOS project but posting here because it affects React Native in particular.

**Is there a reason we need to use `use_frameworks!` in the `Podfile` / is there any way to _avoid_ having to do this?** 

I think back in 8.3 we could modify an import or two and remove `use_frameworks!` with no ill effects. With 9.2 it just causes a long string of errors that I haven't been able to resolve.

With the way the React Native ecosystem is heading it seems to be frowned upon to use `use_frameworks!` and it's actually totally broken if trying to use Hermes or Flipper.

We're between a rock and a hard place at the moment because with the React Native 0.66 upgrade we also needed to upgrade React Native Reanimated to version 2, which uses turbomodules and therefore crashes if we try to use chrome debugger on Android. But we can't switch to Hermes which would allow direct debugging via Flipper because we can't enabled either Hermes or Flipper without getting build errors (cause by use_frameworks) on iOS.

Related reading:
https://github.com/facebook/react-native/issues/32451
https://github.com/facebook/hermes/issues/548
https://github.com/react-native-community/discussions-and-proposals/issues/206
https://github.com/software-mansion/react-native-reanimated/issues/1663#issuecomment-770769922

**Comment by hugo-chq** [comment]
Also running into an issue trying to use Reanimated 2 and use_frameworks,
even now that Reanimated 2 doesn't rely on turbomodules, it unfortunately still can't be used as is

**Comment by hugo-chq** [comment]
Looks like the Reanimated issue might be resolvable with Reanimated 2 beta 3, and this change to from @mjmasn https://github.com/software-mansion/react-native-reanimated/issues/2525#issuecomment-941122535

where they mention AppDelegate.m/.h weren't updated with changes match the latest react-native default starter project,
https://react-native-community.github.io/upgrade-helper/?from=0.58.6&to=0.66.0

would it be possible to get those AppDelegate changes ( mostly related to `RCTBridgeDelegate` ) in this starter project, or are they potentially incompatible? thanks

**Comment by krakz999** [comment]
> Also running into an issue trying to use Reanimated 2 (seemingly related to use_frameworks), even now that Reanimated 2 doesn't rely on turbomodules, it unfortunately still can't be used as is

Since when Reanimated 2 does not use Turbomodules? Could you link source?

**Comment by gkotula** [comment]
Hi everyone, is the use of `use_frameworks!` still causing issues, or is the latest version of Mobile SDK working when integrating Flipper or Hermes?

As far as the `AppDelegate` changes, we will take a look at it, thanks!

**Comment by wmathurin** [comment]
In our upcoming version of Mobile SDK (10.2), we are no longer using use_frameworks in our template app pod files.
See https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/348

**Comment by mjmasn** [comment]
Fantastic, thanks for the update @wmathurin
