### ISSUE TITLE
App crash when kept idle in iOS

### ISSUE THREAD

**Issue by VaibhavP04** [forcedotcom/SalesforceMobileSDK-ReactNative#253]
This is issue that is observed in iOS. When the app is kept idle for a long time, The app crashes instead of executing a success call back. 
Below the error message

<img width="1792" alt="Screen Shot 2021-11-11 at 10 13 12 AM" src="https://user-images.githubusercontent.com/53604194/141239069-b062ebb2-97da-4ca6-a9d0-7204c135967d.png">

It happens if the app is kept idle for 2 days and when we launch the app again. I wanted to check whether there is a mechanism to hard stop all syncDowns.

**Comment by wmathurin** [comment]
Please provide more details:
- iOS version
- Mobile SDK version

**Comment by wmathurin** [comment]
Regarding your question: "I wanted to check whether there is a mechanism to hard stop all syncDowns."

Please checkout the doc around stopping (and restarting) sync operations:

https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_stop_start_sync_operations.htm
