### ISSUE TITLE
Documentation for Conflict handling with Sync targets

### ISSUE THREAD

**Issue by AnuragTiwari1** [forcedotcom/SalesforceMobileSDK-ReactNative#261]
I am using salesforce mobile sdk v9.2.0 and using mobile sync to sync data between salesforce and smartstore.

I need to implement merge modes defined in this [salesforce sdk article](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_conflict_detection.htm)

currently mobilesync.MERGE_MODE only shows two options OVERWRITE and LEAVE_IF_CHANGED

**Comment by wmathurin** [comment]
The article is about a javascript smartsync.js library we wrote back in 2013 or 2014 which had more merge options.
The native Mobile Sync libraries both on iOS and Android have simplified options, similar to merge strategies you find in tools like git: in case of conflict, do you want "theirs" (OVERWRITE) or "ours" (LEAVE_IF_CHANGE
D).
