### ISSUE TITLE
Implementation of PKCE with Salesforce Mobile SDK?

### ISSUE THREAD

**Issue by kchelvan** [forcedotcom/SalesforceMobileSDK-ReactNative#263]
I am looking to implement the PKCE authorization flow using the Salesforce Mobile SDK with React Native. 

I noticed that the SDK library has identifiers for both the code challenge and verifier built into it, but there is no visible way to enable this functionality. Is there any documentation that explains how we can leverage the mobile SDK to handle PKCE implementation with Salesforce?

**Comment by bhariharan** [comment]
Look at the section for enabling advanced authentication in our developer guide.

**Comment by wmathurin** [comment]
Here is the section: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_advanced_using.htm
