### ISSUE TITLE
Syncup not working

### ISSUE THREAD

**Issue by bsrinath4839** [forcedotcom/SalesforceMobileSDK-ReactNative#268]
When I try to do sync up of locally modified records those are not changing in Salesforce end by using Android.

May be `com.salesforce.androidsdk.mobilesync.target.BatchSyncUpTarget` is not doing updation of records.

I have even added 
```
__local__: true
__locally_created__: false
__locally_deleted__: false
__locally_updated__: true 
```

But not updating using Android, whereas the sync up for modified records is working fine with iOS devices.

**Comment by wmathurin** [comment]
Check out the [MobileSyncExplorerReactNative](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/MobileSyncExplorerReactNative), it demonstrates how to successfully use mobile sync with React Native. You can create/edit/delete records. It works on both iOS and Android.
