### ISSUE TITLE
Auto sync down is not working after deleting record in SFDC

### ISSUE THREAD

**Issue by vivekdeshmane** [forcedotcom/SalesforceMobileSDK-ReactNative#270]
Version: Salesforce Mobile SDK - ReactNative SDK 9.2.1 (latest)

Issue:
Mobile App shows deleted records that were deleted in SFDC which means auto-sync down is not working.

Steps to Reproduce:
1. Login into the mobile app and open the Contact list ex. it shows a Contact count of 10
2. Login into SFDC go to the contacts tab and delete a contact record.
3. Now, relaunch the mobile app, it will still show the same contact count along with deleted records instead of excluding deleted record

**Comment by wmathurin** [comment]
(Copied from https://developer.salesforce.com/forums/?id=9062I000000ILCqQAO)
If you’re finding that sync down operations sometimes leave unwanted records in your SmartStore soups, you can use the cleanResyncGhosts API to get rid of them.

In certain prescribed cases, SmartStore soups do not reflect the exact contents of the most recent sync down request. For example, if a record is deleted on the Salesforce server, the next sync down operation doesn’t remove that record from SmartStore. Also, records that don’t satisfy the sync criteria are excluded from the sync down results but aren’t automatically removed from the soup. These records that unexpectedly remain in the SmartStore soup are known asghosts.

Please refer to below link for more information:

https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_sync_ghosts.htm
