### ISSUE TITLE
Using react.force.net.js to perform CRUD with a list of objects/records

### ISSUE THREAD

**Issue by arshadaxolt** [forcedotcom/SalesforceMobileSDK-ReactNative#275]
How do i use react.force.net.js to perform CRUD with list of records, currently it only supports single at a time.

for example: 
 net.create('contact', {FirstName: 'test', LastName: 'test'});

it only allows me to create a single record.

I want to be able to create list of contacts at once.

**Comment by gkotula** [comment]
Hi arshadaxolt,

Unfortunately the React Native SDK does not expose batch CRUD operations at this time.  We are aware of this pain point, and we will try to add this enhancement in a future release.

Closing this with the "enhancement" label.

**Comment by arshadaxolt** [comment]
Hi,

Any update on this ?
Or any alternative for this?

Please assist ASAP.

Thanks

**Comment by 6360086525** [comment]
Even I'm facing with the Similar Issue Kindly Help me out.

**Comment by nayeem81127** [comment]
Hi have Stuck with Exactly Same Issue Kindly please Assist to resolve this issue ASAP.

**Comment by wmathurin** [comment]
For a workaround (or track progress on this enhancement request), please see: https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/282
