### ISSUE TITLE
Missing documentation for SmartStore Schema migration

### ISSUE THREAD

**Issue by AnuragTiwari1** [forcedotcom/SalesforceMobileSDK-ReactNative#277]
Hi Team,

we are looking into ways to migrate the soup on app upgrade incase there are some schema level changes(eg: field rename, addition of new field or deletion of existing field).

we are currently using v10.0.0 version of Salesforce Mobile SDK

**Comment by wmathurin** [comment]
Look at this [page](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_managing_soups.htm) in the documentation.

Especially the sections:

- [Change Existing Index Specs on a Soup](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/offline_soup_change_index_specs.htm)
To change existing index specs, call the applicable soup alteration method.
- [Reindex a Soup](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/offline_soup_reindex.htm)
Use reindexing if you previously altered a soup without reindexing the data, but later you want to make sure all elements in the soup are properly indexed. Both alterSoup() and reindexSoup() perform better for conversion to, or creation of, JSON1 index specs than for other index spec types.
- [Remove a Soup](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/offline_soup_remove.htm)
Removing a soup deletes it. When a user signs out, all soups are deleted automatically. For other occasions in which you want to delete a soup, call the applicable soup removal method.

**Comment by AnuragTiwari1** [comment]
thanks @wmathurin, I will try this
