### ISSUE TITLE
android SDK: Parallel syncdown/resync is not happening 

### ISSUE THREAD

**Issue by vivekdeshmane** [forcedotcom/SalesforceMobileSDK-ReactNative#278]
Version: Salesforce Mobile SDK - ReactNative SDK 9.0  and same issue with(latest)

Issue:
We have multiple SOUP configs(Account/Contact/Task etc) to download records but parallel syncdown/resync is not happening in android SDK compared to iOS.  Hence, it's taking a long time to download all configs data than the estimated time.

**Comment by gkotula** [comment]
Thank you for the feedback!  We have opened an internal ticket to track this enhancement request.
