### ISSUE TITLE
Performing CRUD operations on list of records in one transaction using forcereact. Major dependency

### ISSUE THREAD

**Issue by arshadaxolt** [forcedotcom/SalesforceMobileSDK-ReactNative#282]
How do i use react.force.net.js to perform CRUD with list of records, currently it only supports single at a time.

for example:
net.create('contact', {FirstName: 'test', LastName: 'test'});

it only allows me to create a single record.

I want to be able to create list of contacts at once.

Please assist on this or any alternative for perform bulk CRUD operations.

Thanks

**Comment by 6360086525** [comment]
Hii Me too  Stuck with Exactly  Same Issue Kindly please Assist ASAP.

**Comment by nayeem81127** [comment]
Hi have Stuck with Exactly Same Issue Kindly please Assist to resolve this issue ASAP.

**Comment by wmathurin** [comment]
We are adding methods for sobject collections in our upcoming release (10.1).
For more details: see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/283

**Comment by arshadaxolt** [comment]
Thanks,

When can we expect this release (10.1) ?

**Comment by wmathurin** [comment]
Scheduled for some time next week.
