### ISSUE TITLE
Check creatable/updatable/deletable/accessible permissions for objects and fields using forcereact ?

### ISSUE THREAD

**Issue by arshadaxolt** [forcedotcom/SalesforceMobileSDK-ReactNative#284]
How can we check CRUD permissions for Objects or fields using forcereact - salesforceMogileSDK ?
Please assist.

Thanks

**Comment by wmathurin** [comment]
This question is answered here: https://salesforce.stackexchange.com/questions/24995/check-user-permissions-through-rest-api
