### ISSUE TITLE
After new param is added resync doesn't work, only full sync

### ISSUE THREAD

**Issue by aureosouza** [forcedotcom/SalesforceMobileSDK-ReactNative#286]
1. Version of Mobile SDK Used: 9.2.1
2. Issue found in Native App or Hybrid App: Hybrid(React Native)
3. OS Version: all
4. Device: all
5. Steps to reproduce:

5.1) Register the soup:

```
import { smartstore, forceUtil } from 'react-native-force';

const schema = [
    { path: 'Id', type: 'string' },
    { path: 'Param1__r.Param2', type: 'string' },
    { path: '__local__', type: 'string' },
    { path: '__sync_id__', type: 'string' },
  ]; // Not added Param3 or Param4 to the schema as it's not used in queries
  
const registerSoup = forceUtil.promiser(smartstore.registerSoup);  

const result = await registerSoup(
        {
          isGlobalStore: true,
          storeName: hash,
        },
        'SoupName',
        schema,
      );
```

5.2) Full Sync down the soup with Param3:

```
import { mobilesync, forceUtil } from 'react-native-force';

const syncDown = forceUtil.promiser(mobilesync.syncDown);
const result = await syncDown(
    {
      isGlobalStore: true,
      storeName: 'hash',
    },
    {
      type: 'soql',
      query: 'SELECT Param1__r.Param2, Param3 FROM SoupName',
      modificationDateFieldName: 'Param2',
    },
    'SoupName',
    { mergeMode: 'OVERWRITE' },
    'syncDownName',
  );
  ```

5.3) Full sync down the soup with new Param4:

```
import { mobilesync, forceUtil } from 'react-native-force';

const syncDown = forceUtil.promiser(mobilesync.syncDown);
const result = await syncDown(
    {
      isGlobalStore: true,
      storeName: 'hash',
    },
    {
      type: 'soql',
      query: 'SELECT Param1__r.Param2, Param4 FROM SoupName',
      modificationDateFieldName: 'Param2',
    },
    'SoupName',
    { mergeMode: 'OVERWRITE' },
    'syncDownName2',
  );
  ```

**Everything works correctly at this point, and we are able to get correctly the new Param4**

5.4) Resync the soup:

```
const resync = forceUtil.promiser(mobilesync.reSync);
const result = await resync(
        {
          isGlobalStore: true,
          storeName: hash,
        },
        'syncDownName',
      );
```
      
**Value for Param4 is null**

If we perform again step 5.3 with a full sync we always get value for Param4, but if we perform a resync it does not work.  

6. Actual behavior: value for new param is null after resync, full sync is always necessary (or reinstall which is not an option)
7. Expected Behavior:  after full sync we should be able to do only resync again without losing data
8. Error Log: no errors

**Comment by wmathurin** [comment]
Just to be sure, in step 5.4, there is typo, you are reSync-ing syncDownName2 (not syncName3)?

**Comment by aureosouza** [comment]
One important info that may help with the investigation is that `Param2` that we pass to `modificationDateFieldName` is a static string, not a date value, since for this soup we don't have yet a `LastModifiedDate` value to properly calculate the resync. 

This means the resync of this soup actually works as a full-sync, and was not showing any problems so far. The only scenario in which the resync lost data was in this present scenario when a new `Param4` was added replacing `Param3` and after a successful full-sync the subsequent resync all lost `Param4`, obligating us to always call full-sync for this soup.

Another remark is that `Param3` and `Param4` were not added as an index to `schema` when registering the soup (as they are only use in simple select) and therefore we did not call `alterSoup` with new schema.

We need to understand if with these remarks it would be expected to get correct values or if there's an issue on the SDK side. As for any other scenario, like new install, resync with same parms, etc we did not see any issues so far. Thanks!

**Comment by aureosouza** [comment]
> Just to be sure, in step 5.4, there is typo, you are reSync-ing syncDownName2 (not syncName3)?

We are calling different names for the full-sync and the re-sync, is this not expected? We were getting errors if the names were the same

**Comment by aureosouza** [comment]
> Just to be sure, in step 5.4, there is typo, you are reSync-ing syncDownName2 (not syncName3)?

Yes, for this soup the name was the same, as the initial full-sync `syncDownName`. Then we did another full-sync with `syncDownName2`, and finally the resync with `syncDownName`, could this be the issue?

**Comment by aureosouza** [comment]
> When you do a sync, the record downloaded from the server replaces the one already in the soup. So if you run a sync that pulls param3, followed by a sync that pulls param4, the local record will only contain param4. 

This is fine as we need param4, the problem is the resync is losing this value, could it be because of sync name passed? Should it be always the name of last full-sync?

> If you do a re-sync instead of full sync then the above behavior will only affect changed records since the last sync.

This is not currently true, we did a full sync with param4, but then the resync lost this param.

> If you do a re-sync instead of full sync then the above behavior will only affect changed records since the last sync.

To give you some context, these are different versions of the application. So we are obligated to perform multiple full-sync with different schemas without uninstalling the application, to fetch new params added to SalesForce. And it worked fine so far, but we are experiencing issues with this soup after the resync, that is removing the parameter added in the last full sync.

We suspect it could be as mentioned because of syncName passed was not the last sync name or because as mentioned in previous [comment](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/286#issuecomment-1165289673) the last modified date field is not a date.

From the SDK side, we'd expect the resync to not mark as ghost records a param that was succesfully synced in previous full sync. Let us know your thoughts, thanks a lot for support!

**Comment by wmathurin** [comment]
In step 5.4, if you resync the sync called "syncDownName", then you are fetching records from the server with the param3 field populated and replacing local records that had been fetched with the param4 field populated.
If you want the param4 field populated, you should do a resync of the sync called "syncDownName2". Does it make sense?

If you need param3 and param4, define a sync that does `select param3, param4 from ....` and only run this one.

**Comment by aureosouza** [comment]
Yes @wmathurin that makes sense, we will try to always use the last full sync name for the subsequent resyncs and confirm the behaviour, thanks for the support

**Comment by gkotula** [comment]
Hi @aureosouza, were you able to work through the issue?

**Comment by gkotula** [comment]
Closing due to lack of response.
