### ISSUE TITLE
Android app crashes after log in

### ISSUE THREAD

**Issue by DavidLozzi** [forcedotcom/SalesforceMobileSDK-ReactNative#287]
After a successful log-in, our app crashes. In my emulator, the screen just goes white, on a phone, it closes. Reopening the app, the user is logged in and can go to the remainder of the app. Where do I begin troubleshooting this? There's very little documentation and unclear how this is exactly configured (I inherited the app). 

Works great on iOS, just Android is broken.

```js
    "react": "16.13.1",
    "react-devtools": "^4.10.1",
    "react-native": "0.66.0",
    "react-native-force": "https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git",
```

**Comment by wmathurin** [comment]
Have you checked the logs?

**Comment by DavidLozzi** [comment]
@wmathurin what logs where exactly?

**Comment by mjmasn** [comment]
This was raised in https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1921, we still see it relatively frequently in both dev and production builds, from memory nothing stood out in the logs but can double check next time I encounter it.

**Comment by gkotula** [comment]
@DavidLozzi If there are any errors printed to `logcat` in Android Studio, that would greatly help debugging the issue you're experiencing.

**Comment by gkotula** [comment]
Closing due to lack of response.
