### ISSUE TITLE
User getting logged out automatically when the app re-opens

### ISSUE THREAD

**Issue by bsrinath4839** [forcedotcom/SalesforceMobileSDK-ReactNative#289]
Hi,
My Android app is logging out user automatically when user closes the app and opens it again. User not even able to login until or unless he removes all data of the application from AppInfo.
I am getting following error. (This is happening only for one domain and only in Android). 

"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found"

Please suggest the solution.

**Comment by wmathurin** [comment]
It seems like your phone is missing a top-level cert from one of the cert issuers. Can you tell us more about that one domain it is happening for?

**Comment by bsrinath4839** [comment]
yeah,

the domain I am using is atservices.force.com

**Comment by wmathurin** [comment]
Please review with your admin to see if any certs were setup for that custom domain.
The error you reported above is a low level error coming from the OS. The Mobile SDK has no power over certs setup on a device.
