### ISSUE TITLE
iOS app crashes on logout when smartStore.moveCursorToPageIndex is still running

### ISSUE THREAD

**Issue by AnuragTiwari1** [forcedotcom/SalesforceMobileSDK-ReactNative#291]
"react-native": "0.67.1",
    "react": "17.0.2",
    "react-native-force": "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v10.0.0",

whenever user logout and if smartStore.moveCursorToPageIndex is still running then app crashes on iOS, with following exception:

[native] Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]' was thrown while invoking moveCursorToPageIndex on target SFSmartStoreReactBridge with params (
        {
        cursorId = 0x600001633740;
        index = 242;
        isGlobalStore = 0;
    },
    8701
)

on android I don't face this issue and action completes.

**Comment by wmathurin** [comment]
We will take a look thanks.

**Comment by wmathurin** [comment]
Will be fixed in the next version of Mobile SDK - see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/351
