### ISSUE TITLE
recursive option (to process more than 200 limit) for multi-records CRUD operations using react native force

### ISSUE THREAD

**Issue by arshadaxolt** [forcedotcom/SalesforceMobileSDK-ReactNative#292]
There is a limit of the SObject collection API like (net.collectionCreate, net.collectionUpdate, net.collectionUpsert, net.collectionDelete) - up to 200 records can be processed in one-time call. So if you want to process more than 200 records you may divide the request to process them.

Please Add allowRecursive option along with allOrNone to multi-record CRUD operations to automatically divide the input and recursively call SObject Collection API until the given records are all processed.

**Comment by gkotula** [comment]
We will propose adding this enhancement in a future release of Mobile SDK.  Thank you for the suggestion!

**Comment by arshadaxolt** [comment]
Any Update on this?
