### ISSUE TITLE
Want to remove Allow Access page while logging in into the app

### ISSUE THREAD

**Issue by bsrinath4839** [forcedotcom/SalesforceMobileSDK-ReactNative#293]
I want to remove Allow Permissions page while logging in to my application.

Please check the link for details.
https://salesforce.stackexchange.com/questions/383867/want-to-remove-allow-access-page-while-logging-in-into-the-app

**Comment by gkotula** [comment]
Responded in your linked StackExchange question.  Closing this issue to continue the conversation there as this is not an issue specific to the Mobile SDK.
