### ISSUE TITLE
Salesforce created React Native Project and installed dependencies not Running

### ISSUE THREAD

**Issue by ManishPrakharan-Alstom** [forcedotcom/SalesforceMobileSDK-ReactNative#300]
Hello Team,

I am facing issue in creating project using forcereact.
I created a new project from command forcereact createwithtemplate --templaterepouri=ReactNativeTemplate 
and it works fine on both iOS and android which has react native version 0.67.1.

I tried to install dependencies of latest version as following with command npm i:->
@react-native-community/geolocation
@terrylinla/react-native-sketch-canvas
appcenter
appcenter-analytics
appcenter-crashes

When I install the pods for iOS
it starts to fail
I get following error

'React/RCTRootView.h' file not found
error build: Undefined symbol: OBJC_CLASS$_CLLocationManager
error build: Undefined symbol: _kCLDistanceFilterNone
error build: Undefined symbol: _kCLLocationAccuracyBest
error build: Undefined symbol: _kCLLocationAccuracyHundredMeters
error build: 'React/RCTBundleURLProvider.h' file not found
'SalesforceSDKCore/SFSDKAppConfig.h' file not found
'SalesforceSDKCore/SFPushNotificationManager.h' file not found
'SalesforceSDKCore/SFDefaultUserManagementViewController.h' file not found
'SalesforceSDKCore/SalesforceSDKManager.h' file not found
'SalesforceSDKCore/SFUserAccountManager.h' file not found
'SalesforceReact/SalesforceReactSDKManager.h' file not found
'SalesforceSDKCore/SFLoginViewController.h' file not found
'SalesforceReact/SFSDKReactLogger.h' file not found

Methods to reproduce

create new project with command forcereact createwithtemplate --templaterepouri=ReactNativeTemplate

npm i @react-native-community/geolocation

cd ios && pod install

open xcworspace and run try to build iOS workspace with Xcode.

And it won't Build and you will get the above errors.
But If I do the above process with command RN Cli i.e.(npx react-native init AwesomeProject) then there's no error
Can you please look into this issue ASAP

my react native info

System:    
OS: macOS 12.6    
CPU: (8) arm64 Apple M1    
Memory: 356.73 MB / 16.00 GB    
Shell: 5.8.1 - /bin/zsh  

Binaries:    
Node: 18.9.0 - /opt/homebrew/bin/node    
Yarn: 1.22.19 - /opt/homebrew/bin/yarn    
npm: 8.19.1 - /opt/homebrew/bin/npm    
Watchman: 2022.09.19.00 - /opt/homebrew/bin/watchman  

SDKs:    iOS SDK:      
Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0    
Android SDK:      
API Levels: 31, 32, 33      
Build Tools: 29.0.3, 30.0.3, 31.0.0, 33.0.0      
System Images: android-30 | Google APIs ATD ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a,
android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64  
IDEs:    
Android Studio: 2021.3 AI-213.7172.25.2113.9014738    
Xcode: 14.0/14A309 - /usr/bin/xcodebuild  

npmPackages:    
react: 16.9.0 => 16.9.0     react-native: 0.61.3 => 0.61.3  
 
npmGlobalPackages:    create-react-native-app: 3.8.0    react-native-cli: 2.0.1

**Comment by wmathurin** [comment]
I recommend you upgrade to Mobile SDK 10.2 that was released today and uses React Native 0.70.1. 
More importantly our React Native template in Mobile SDK 10.2 don't `use_frameworks` in their pod file which has caused issue with other dependencies in the past.
