### ISSUE TITLE
Upgrading devDependencies

### ISSUE THREAD

**Issue by DBB-Alstom** [forcedotcom/SalesforceMobileSDK-ReactNative#302]
Hello Team,

I have a query:-> 
I have upgraded the Salesforce mobile SDK to the latest RN version i.e. **0.70.1**
then **devDependencies** section in **package.json** file were of lower version than the current.
If i manually upgrade those **devDependencies** versions would it have any **impact** on my **current** upgraded **version** project ?
Please answer

**Comment by wmathurin** [comment]
Did you upgrade Mobile SDK to 10.2? MSDK 10.2 works with RN 0.70.1.

**Comment by brandonpage** [comment]
@DBB-Alstom please reopen this issue if upgrading to Mobile SDK 10.2 does not fix the issue.
