### ISSUE TITLE
Getting issues while running android build 

### ISSUE THREAD

**Issue by DBB-Alstom** [forcedotcom/SalesforceMobileSDK-ReactNative#303]
Hello Team,

I have a query:->
I have upgraded the Salesforce mobile SDK to the latest RN version i.e. 0.70.1

then devDependencies section in package.json file were of lower version than the current.
"@babel/runtime": "^7.12.5",
this version is causing issue when i try to run the android build
the temporary solution i founded is 
I had to install
"@babel/runtime": "7.0.0-beta.55"

Please provide the permanent fix

i am getting multiple Errors due to this devDependencies package

`error: Error: While trying to resolve module
  Unable to resolve module @babel/runtime/helpers/module/moduleName
`

**Comment by wmathurin** [comment]
Are you using Mobile SDK 10.2 (it uses RN 0.70.1) or are you running an older version of the Mobile SDK?

**Comment by DBB-Alstom** [comment]
@wmathurin I am using the current SDK 10.2 which uses RN 0.70.1
I am getting problem in the current SDK i.e. SDK 10.2

**Comment by wmathurin** [comment]
Mobile SDK 11.0 was just released. It uses RN 0.70.6, and some of the dependencies have been upgraded as well. Could you try and see if you are still have build issues?

**Comment by wmathurin** [comment]
Closing issue for lack of updates. Please open a new issue if you are still having problems.
