### ISSUE TITLE
Multiple records getting created in Salesforce

### ISSUE THREAD

**Issue by bsrinath4839** [forcedotcom/SalesforceMobileSDK-ReactNative#304]
Hi,

while we are creating a record on an object it creates multiple records. we had set up a debug log in salesforce it is showing common.api.composite.operation.execution.RestExecutor as Operation multiple times.

This is happening only for Android.

**Comment by gkotula** [comment]
We need more information to narrow down the issue.  What Mobile SDK API are you using to sync the records up to your Org?  Is it MobileSync with Sync Targets, or are you invoking the Org's Composite REST API directly?

**Comment by bsrinath4839** [comment]
I am using Salesforce Mobile SDK for React Native version 8.1.
I am using MobileSync from react-native-force.

**Comment by bsrinath4839** [comment]
MobileSync.syncup is been performed only on one record but it's creating lot of records in Salesforce.

**Comment by gkotula** [comment]
>MobileSync.syncup is been performed only on one record

MobileSync doesn't really work like that.  It will sync all local changes made to your SmartStore since the last sync.  My guess is that there are actually two copies of the record in your SmartStore when you run `syncUp`.  Could you verify if that is the case?

**Comment by bsrinath4839** [comment]
No, There is only one record in my smart store.
When I do SyncUp it's creating N records.
N is directly proportional to waiting time.

After calling SyncUp I am waiting for it to give a response. But it is not responding, so I am refreshing the app to stop the function to work. In the mean while it's creating more than 1000 records in backend

**Comment by bsrinath4839** [comment]
> 

Yes, I know how that work. But I didn't get why it is creating these many records

**Comment by gkotula** [comment]
Could you provide debug logs from when you encounter this issue (either from React Native or Android Logcat or both)?

**Comment by bsrinath4839** [comment]
I am sorry to say this, but I can't provide any Logs or source code due to my company policies.
I hope you can understand.

There is no error coming, and no response also coming from anywhere. The Log is just stopped and waiting for a response from the backend.

The common.api.composite.operation.execution.RestExecutor is shown multiple times in Salesforce.

**Comment by gkotula** [comment]
Hi @bsrinath4839, even redacted/sanitized logs would be a great help.  Knowing what methods are being executed at the time of the erroneous behavior is very important to tracking this down.

**Comment by gkotula** [comment]
Hi @bsrinath4839, I must have misunderstood when you said which version of Mobile SDK you are using.  You are on MSDK v8.1?  If so, please try to upgrade to the latest version (v10.2) and see if that fixes your issue.  v8.1 is years old, and your issue may be fixed already.

**Comment by bsrinath4839** [comment]
HI @gkotula, Sure will update the SDK and let you know about this.
But, May I know how SDK can cause this?
I mean, Is there any method available in the SDK, that can be causing this issue?

**Comment by gkotula** [comment]
A lot has changed since v8.1, both in Salesforce Orgs and MSDK.  No method I can think of should behave this way.

**Comment by bsrinath4839** [comment]
Okay,
Will update the SDK.

But as a quick fix, I want to know one thing.
How to create an array of records with net.sendRequest();?
That is how to do 
net.sendRequest('/services/data', `/${apiVersion}/sobjects/${object}`,successCB, errorCB, 'POST', [{record_1}, {record_2}...],{ "Content-Type": "application/json" })

**Comment by wmathurin** [comment]
Use the collectionCreate, collectionUpsert, collectionUpsert, CollectionDelete methods.
See [code](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/blob/dev/src/react.force.net.ts#L347) and [example code](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/blob/dev/test/net.test.js#L228).
