### ISSUE TITLE
iOS: Receiving blank white screen after login

### ISSUE THREAD

**Issue by AnuragTiwari1** [forcedotcom/SalesforceMobileSDK-ReactNative#306]
SDK version: 10.1.1
React native version: 0.67.1

device info: iPhone 13 Pro
OS info: iOS 16.1.1

for one iOS user we are getting a blank white screen after successful login. I have tried solution mentioned in below thread but still facing the same error

https://salesforce.stackexchange.com/questions/68499/recevie-a-blank-white-screen-after-logging-into-salesforce1-only-occurs-on-sams

Note: same app version and account is working on other iOS device

**Comment by AnuragTiwari1** [comment]
I am getting the same error with deferred login flow as well and as it is happening in production so can't really check the logs.

Please help me to debug more, I have tried changing code inside setupRootViewController to show red screen instead of white(which worked) but app is stuck at that only. 

```Objective-C
NSURL *jsCodeLocation;

jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"hcp_network"
                                                 initialProperties:appProperties
                                                     launchOptions:self.launchOptions];

 rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:0.0f blue:0.0f alpha:1]; // I tried changing color to red and it is reflecting but still app is not loading 

UIViewController *rootViewController = [UIViewController new];
rootViewController.view = rootView;
self.window.rootViewController = rootViewController;
```

Note: the same app version is working with other device

**Comment by wmathurin** [comment]
We have just released Mobile SDK 11.0 (which uses React Native 0.70.6). Could you update and see if you are still having the issue?

**Comment by wmathurin** [comment]
Closing issue. If it is still happening with the latest version of Mobile SDK 11.0, please re-open an issue.

**Comment by AnuragTiwari1** [comment]
found the issue and it is unrelated to Salesforce SDK
