### ISSUE TITLE
Android build issue with RN 0.70.1

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-ReactNative#307]
Hi Team,

4th Nov android build issue is fixed on 0.70.5, see full change-log here. Should be ideal if react-native dependency for SDK 11 be aligned with v0.70.5

https://github.com/facebook/react-native/releases/tag/v0.70.5

**Comment by wmathurin** [comment]
Noted.

**Comment by va1bhav** [comment]
Thank you for incorporating this quickly. @wmathurin 
https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/308
