### ISSUE TITLE
I can't find the right syntax for the externalIdFieldName

### ISSUE THREAD

**Issue by henriqueadonai** [forcedotcom/SalesforceMobileSDK-ReactNative#310]
I'm trying to use the **externalIdFieldName**
But I can't find the right syntax to use in the documentation it's too light and I don't understand. Can you please point me or show a code example to in how use the externalIdFieldName for 2 custom objects, relationship child->Parent.

```
 const target: any = {
    externalIdFieldName: 'Task__c.Task__r',
  };

  const options = {
    mergeMode: mobilesync.MERGE_MODE.OVERWRITE,
    fieldlist: ['Image_URL__c', 'Task__c'],
  };
  mobilesync.syncUp(
    false,
    target,
    'TaskImage',
    options,
    (good) => {
      console.log('good', good);
    },
    (error) => {
      console.log('error ', error);
    }
  );
```

**Comment by wmathurin** [comment]
Examples targets can be found [here](https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/dev/shared/example.usersyncs.json).
We also have the schema defined [here](https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/dev/shared/syncs.schema.json).
You can also validate your syncs.json using `forcereact`:
(From the forcereact --help)
```
forcereact checkconfig
    --configpath=path to store or syncs config to validate
    --configtype=type of config to validate (store or syncs)
```

**Comment by henriqueadonai** [comment]
@wmathurin for the answer.
Sorry for my lack of knowledge here but the documentation does not help in my case.
I have a children's object called taskImage, when I'm syncUp this object I would like to have the Task object be referenced as an external ID.
I'm able to sync up the task image but the relation with the task is never created using the external Id.

`  const target: any = {
    externalIdFieldName: 'USG_Task__c.Task__r',
    idFieldName: 'Id',
    modificationDateFieldName: 'LastModifiedDate',
  };

  const options = {
    mergeMode: mobilesync.MERGE_MODE.OVERWRITE,
    fieldlist: ['Image_URL__c', 'USG_Task__c'],
  };
  mobilesync.syncUp(
    false,
    target,
    'USGImage',
    options,
    (good) => {
      console.log('good', good);
    },
    (error) => {
      console.log('error ', error);
    }
  );
};`

**Comment by henriqueadonai** [comment]
There is no relationship child to parent, it's always parent to child.
