### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by henriqueadonai** [forcedotcom/SalesforceMobileSDK-ReactNative#312]
In IOS after the logout, the user is redirected to the granted screen instead of the login screen.
  oauth.logout(
        () => {
          logMessage('user logged out', id);
        },
        (err) => {
          logError(err, id, 'error in logout callback');
        }
      );

**Comment by bbirman** [comment]
Linked post: https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000O75ifSAB

**Comment by wmathurin** [comment]
We believe we fixed that issue in the recently released Mobile SDK 11.0 (the fix came with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3592).
Please upgrade the SDK and give it a try. Re-open an issue if you are still having a problem.
