### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by djMax** [forcedotcom/SalesforceMobileSDK-ReactNative#313]
I would love to hear the reasons why this package is not published to npm like, oh, I don't know, every other package from every other vendor that intends for their software to be used by other people.

**Comment by bbirman** [comment]
Hi @djMax, we'll take publishing into consideration. Could you tell us more about your use case like what platform(s) you're building for? Does [forcereact](https://www.npmjs.com/package/forcereact) not fit your needs?

**Comment by djMax** [comment]
We are looking at using this in the GasBuddy mobile app which has over 100mm downloads. I don't know that a web Sdk is helpful

**Comment by djMax** [comment]
What does that even mean? Are you saying that the Salesforce SDK is similar to React Native? You have a module that is meant to be used INSIDE other apps as a PACKAGE. There's this thing called the Node Package Manager (npm for short) that makes this much easier to manage. You follow a predictable versioning strategy (semver) and then publish those versions to NPM. We all win.

**Comment by djMax** [comment]
forcereact uses this SDK. This SDK should be used via package inclusion, not git references or code copying. Publish the module.

**Comment by JFoxUK** [comment]
So we’ve gone from @bbirman saying that documentation was being worked on to @wmathurin just closing the ticket and being largely unhelpful. This is a terrible example of community engagement and support.
