### ISSUE TITLE
Issue with jest 

### ISSUE THREAD

**Issue by manishprakharan067** [forcedotcom/SalesforceMobileSDK-ReactNative#318]
I am using Jest framework to write test cases.
I am not getting coverage when I try to write jest for my file 
then() => {} block does not get's called and there is no coverage

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/100135864/228453545-1ac991b4-8a87-48a9-9f70-d29f7692af1c.png">

 I get error when i mock **react-native-force** 
 and i use code 
 
`jest.mock('react-native-force', () => {
    forceUtil: jest.fn()
    mobilesync: jest.fn()
    net: jest.fn()
    oauth: jest.fn()
    smartstore: jest.fn()
});`

I am not able to mock 
`forceUtil,
  mobilesync,
  net,
  oauth,
  smartstore`
  from **react-native-force**
  
  I get error 

  `TypeError: Cannot read properties of undefined (reading 'forceUtil')`
  
<img width="872" alt="image" src="https://user-images.githubusercontent.com/100135864/228457919-4c32997f-108e-45d6-9c04-31f1ac05d39a.png">

  
  
 Please provide the solution how can I mock **react-native-force** and it's functionalities
 and how can i use Jest to get the full coverage.

**Comment by wmathurin** [comment]
Are you first doing
```javascript
import {forceUtil} from 'react-native-force';
```

**Comment by manishprakharan067** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/100135864/228717174-4558645c-cffd-41e8-93f4-6bc48d862282.png">

This is my StoreManager.js file

**Comment by manishprakharan067** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/100135864/228723540-fa3a4e30-36c9-47c6-88bd-5b26cbf1bc11.png">
<img width="872" alt="image" src="https://user-images.githubusercontent.com/100135864/228723583-da4f5bca-87cd-4c15-a072-c368e6b1237b.png">
<img width="872" alt="image" src="https://user-images.githubusercontent.com/100135864/228723647-534ad6c9-2bbd-4f47-95e4-8698bd6733a0.png">
In The above Image then() => {} block doesn’t gets called.

**i get error When I write the below code in JestSetup.js file**

<img width="872" alt="image" src="https://user-images.githubusercontent.com/100135864/228723844-88c1fe07-9bba-4eac-8202-515aff7c2f94.png">

**Comment by manishprakharan067** [comment]
hi @wmathurin can you please into

**Comment by wmathurin** [comment]
We are not expert in Jest. Have you tried getting help on https://github.com/facebook/jest ?

**Comment by manishprakharan067** [comment]
@wmathurin  Yes I have tried But not able to mock react-native-force
You guys don’t have documentation on how to mock react-native-force ?

**Comment by wmathurin** [comment]
We don't have documentation specifically for that. But the entire library is open source (and quite small).
