### ISSUE TITLE
Non ASCII characters  (Turkish language) search not working using smartSql (SQLLite) 

### ISSUE THREAD

**Issue by vivekdeshmane** [forcedotcom/SalesforceMobileSDK-ReactNative#319]
Version: Salesforce Mobile SDK - ReactNative SDK 10.0.0 (latest)

Issue:
We are using smartSql to search or filter locally downloaded data in SOUP but it is not working for outside ASCII characters ex. Turkish language. Could you please help us understand why smartSql not returning the expected results for Non-ASCII characters?

Best Regards,
-Vivek

**Comment by wmathurin** [comment]
Is it iOS or Android or both? Do you see anything relevant in the logs?

**Comment by vivekdeshmane** [comment]
It's happening on both devices. For example, in the log, we don't see returned result record list when we search for lowercase non-ASCII characters.

**Comment by wmathurin** [comment]
What is in your SmartSQL query? Are you doing a like? Are you applying an operator (e.g. lower) on a field?

**Comment by wmathurin** [comment]
We are unable to repro your issues.
We added tests to make sure that one can query back records that have non-ascii characters:
- https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2431
- https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3622

**Comment by wmathurin** [comment]
Closing as we are unable to repro the issues, and the recently added tests (see last comments) indicate that SmartStore can handle non-ASCII characters.

**Comment by vivekdeshmane** [comment]
We use a like operator that does not perform a case-insensitive search on non-ASCII Charcherts other than English. E.g. if smartstore contains 'ğ', then it returns a result if I try to search with like '%Ğ%'" it doesn’t return the same record. And this is an issue with like operator.

**Comment by wmathurin** [comment]
SmartStore uses SQLCipher which itself runs SQLite.
SQLite's like operator is case insensitive for ASCII characters only. 
- If you want it case sensitive for ASCII characters see https://database.guide/how-to-make-sqlites-like-operator-case-sensitive/.
- If you want to make it case insensitive for all characters, look at case folding function u_foldCase provided by the ICU extension (you would do something like: `select {soup:field} where u_foldCase({soup:field}) like '%ğ%'`.

**Comment by vivekdeshmane** [comment]
Hello,
I have tried to use u_foldCase function but getting the error "**SFSmartStoreReactBridge.runSmartQuery failed: {"message":"No cursor for queryError Domain=com.salesforce.smartstore.error Code=999 \"no such function: u_foldcase\" UserInfo={NSLocalizedDescription=no such function: u_foldcase}"}**"
**Query Example:**
SELECT {account-v1:_soup} from {account-v1} where (u_foldcase({account-v1:Name},true) like '%çirkin%'

**Comment by wmathurin** [comment]
It's not included in SQLCipher out of the box ([a long time ago](https://discuss.zetetic.net/t/sqlcipher-for-android-release-android-n-support/1465) it was removed). 
Two possible paths forward:
- somehow recompile SQLCipher for your application with the ICU extension to get u_foldCase
- massage your data at insertion time: create an additional field with the concatenation of the fields you are searching against but with the data in lower case, do the lower casing in JavaScript in your ReactNative application (JavaScript's toLowerCase() works for non-ASCII character unlike SQLite lowercase operator).
