### ISSUE TITLE
Upgrading to React Native 70

### ISSUE THREAD

**Issue by oktalk** [forcedotcom/SalesforceMobileSDK-ReactNative#320]
I have followed the only documentation I could find on getting a project up and running with this package. It's the SalesForce Create a React App guide (https://trailhead.salesforce.com/content/learn/modules/mobile_sdk_react_native/mobilesdk_reactnative_create_app).

Doing a fresh install with `forcereact@10.2.0` my newly created project has React Native 0.67.1 as a dependency. As this is a brand new project: how can I upgrade it to the latest version of React Native? And, does any documentation for upgrading forcereact projects exist, if not could you layout some general guidelines?

**Comment by wmathurin** [comment]
You will be able to upgrade to RN 70 only once the Mobile SDK React Native library is upgraded to depend on RN 70.
We evaluate upgrades of our dependencies with every release of the Mobile SDK. So stay tuned.

**Comment by wmathurin** [comment]
I misspoke earlier. Mobile SDK 10.2 depends on React Native 0.70.1.
You can see it from the package.json, but I just ran `forcereact create` just to make sure.
Could you do a `forcereact version` from the command line to make sure you are indeed running 10.2?
Maybe you could uninstall / reinstall it in case your npm cache is somehow messed up.
