### ISSUE TITLE
CocoaPods could not find compatible versions for pod "MobileSync"

### ISSUE THREAD

**Issue by Ritesh175862** [forcedotcom/SalesforceMobileSDK-ReactNative#322]
Model Name:	MacBook Pro
  Model Identifier:	Mac14,7
  Model Number:	Z16R0006KHN/A
  Chip:	Apple M2
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	8422.100.650
  OS Loader Version:	8422.100.650
  Serial Number (system):	
  Hardware UUID:	
  Provisioning UDID:	
  Activation Lock Status:	Enabled
  
<img width="1107" alt="Screenshot 2023-05-10 at 1 26 08 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/51701629/5c6d0a37-ac82-4840-9240-3c63eef48fdd">

**Comment by wmathurin** [comment]
Did you use forcereact to generate your application?

**Comment by wmathurin** [comment]
What's in your package.json in the top directory of your project?
In particular what do you have in the sdkDependencies section?

**Comment by wmathurin** [comment]
Closing for lack of details.
