### ISSUE TITLE
Android app closes after clicking on Allow button during login to salesforce

### ISSUE THREAD

**Issue by AnuragTiwari1** [forcedotcom/SalesforceMobileSDK-ReactNative#329]
On few android devices android app closes after clicking on allow button during login process

devices and version info:
OEM and device: MI POCO F1
OS: Android 10 and Android 12
SDK version: 10.2.0
react native version: 0.70.10

What is happening:
After pressing on Allow button in web view, App is getting backgrounded and when we tried to open the app from app switcher it shows the login page again. when open again by pressing app icon it works as expected and user is logged in.

iOS device is working fine.

Please suggest a fix or workaround as it is critical for us.

I came across a similar issue https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2379 but it is closed
reported here as well https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000JfyGYSAZ

**Comment by AnuragTiwari1** [comment]
Hi @wmathurin, @bbirman please check this once, it is blocking our production release

**Comment by JohnsonEricAtSalesforce** [comment]
Hello, @AnuragTiwari1. Thanks for reaching out.  This sounds very much like a known issue in 10.2.0 that was resolved in our recent 11.0 release.  I recommend giving that release a try.  Can you confirm if that helps?

**Comment by AnuragTiwari1** [comment]
thanks @JohnsonEricAtSalesforce, i will try out the latest version asap

**Comment by AnuragTiwari1** [comment]
thanks team for resolution, not facing it after upgrading to v11.0.0
