### ISSUE TITLE
Users face logout issue post app termination only in Production Environment.

### ISSUE THREAD

**Issue by jais-shivam** [forcedotcom/SalesforceMobileSDK-ReactNative#330]
Upon logging in, users are required to enter their credentials. However, if the app is killed (removed from RAM) immediately after logging in and when restarted, it asks for credentials again in the Production environment. This issue is not present in Predprod and developer Sandbox environments.

The error we are getting- 
"SalesforceNetReactBridge.sendRequest failed: "{\"error\":\"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.\"

I kindly request assistance with the matter at hand. Your support and expertise would be greatly appreciated.

**Comment by wmathurin** [comment]
What version of the the Mobile SDK are you using?
What about the device OS version / name where you are seeing the problem?

**Comment by jais-shivam** [comment]
thanks, @wmathurin issue was resolved Apologies for so  late reply.
