### ISSUE TITLE
Resync has an issue when trying to parse queries with an 'or' clause

### ISSUE THREAD

**Issue by socialsuiteDavid** [forcedotcom/SalesforceMobileSDK-ReactNative#331]
When a resync is run on a syncName which has a query containing an "OR" clause then the resync will fail. Giving a MALFORMED_QUERY error code and Unexpected token OR, it seems it has misparsed the WHERE clause since the query in the error message is a date stamp followed by: 'and id != null OR Name'. and then it just cuts off regardless of the rest of the clause, even if you add LIMIT TO or ORDER BY, those are all still cut off. 

Simplified example code:
```
    let querySpec = {
        type: 'soql',
        query: `SELECT Id, Name FROM myNS__myObj__c WHERE Id != null OR Name != null`
    };

     await deleteSyncPromise('myObj');
     await syncDownPromise('myObj', querySpec, smartsync.MERGE_MODE.OVERWRITE);
     await reSyncPromise('myObj');
```
_where the 3 ...Promise functions are just wrapping the mobileSync functions_

This can easily be worked around by putting the two parts of the where clause inside brackets like so: "...WHERE (Id != null OR Name != null)". This allows it to work as expected.

**Comment by wmathurin** [comment]
Are you having the issue on iOS and/or Android?
What version of the Mobile SDK are you using?

**Comment by socialsuiteDavid** [comment]
both ios (simulator) and android physical device,
mobile sdk v10.2.0

The interesting thing is that we hadn't updated anything recently yet the problem just started happening.

**Comment by wmathurin** [comment]
Can you tell from the logs what query are actually being sent to the server?

**Comment by wmathurin** [comment]
Unable to repro the issue - see the new test in https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2520
