### ISSUE TITLE
mobile sync with multiple objects in react native

### ISSUE THREAD

**Issue by vishnu-jangid** [forcedotcom/SalesforceMobileSDK-ReactNative#333]
Hi,
please share mobile sync example with multiple objects and single record sync on server. and use salesforce mobile sdk 11.0.0 in react native.

**Comment by wmathurin** [comment]
To sync down multiple kinds of objects including related objects multiple level deep, you can use our briefcase sync down (more details [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_sync_down_target_briefcase.htm)).
To sync them up however, you will have to proceed one type of records at a time.

**Comment by wmathurin** [comment]
Closing - re-open if my last comment was not helpful.
