### ISSUE TITLE
React native MobileSDK logout is NOT working for IOS, but redirecting user to SF allow access screen instead of login page

### ISSUE THREAD

**Issue by jais-shivam** [forcedotcom/SalesforceMobileSDK-ReactNative#334]
oauth.logout(); 
BackHandler.exitApp();

When I am trying to logout from my iPad it redirects me to the SF allow access screen instead of the login page.
Can someone help me how to troubleshoot this issue?

![Picture 1](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/47588402/e4f7a72b-c69b-4615-bf98-5c18f4638502)

**Comment by wmathurin** [comment]
What version of Mobile SDK are you using?
Are you using advanced authentication?

**Comment by jais-shivam** [comment]
Mobile sdk- v10.2.0
oauth  from react-native-force

**Comment by wmathurin** [comment]
You are probably running into this issue:https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3481#issuecomment-1090530386
Fortunately, it has been fixed in Mobile SDK 11.0. Please upgrade and let us know if you are still having problems.

**Comment by jais-shivam** [comment]
Thanks @wmathurin  for your help. I will update Mobile SDK.
