### ISSUE TITLE
Build issues with Xcode 15

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-ReactNative#336]
The latest version of SDK(v11.0) is not compatible with latest version of react native. There is a work around for now but the fix for the latest Xcode with RN is included in https://github.com/facebook/react-native/releases/tag/v0.72.5 along with other fixes. Please consider upgrading to latest RN in upcoming release. Thank you!

**Comment by wmathurin** [comment]
We are planning to upgrade to RN 0.72 in our next major release (MSDK 12.0). #safeharbor

**Comment by va1bhav** [comment]
Thank you for your response @wmathurin but wouldn't v12 come towards the end of next year considering the release history as the major version is bumped once a year only?

**Comment by wmathurin** [comment]
v12 should come out in the beginning of 2024. (v11 was unusually late).

**Comment by wmathurin** [comment]
We have a minor (11.1) coming out soon (end of the month) but it won't have a RN upgrade.

**Comment by va1bhav** [comment]
@wmathurin Thanks a lot! I see that you have upgraded to RN 70.13 on 11.1. v70.14 contains more fixes for latest Xcode, it's a minor path, please upgrade if possible. Thank you again!
![image](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/33320222/6744aa6d-27a5-454a-a032-79bf45f0c7dc)

**Comment by wmathurin** [comment]
Upgrading to 0.70.14. See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/342

**Comment by wmathurin** [comment]
Will be in our 11.1 release which should come out next week #safeharbor.

**Comment by va1bhav** [comment]
@wmathurin  is there a planned release timeframe for SDK 12? not looking for exact date but a timeframe probably. We want to upgrade from 11.0.1 so we plan to bypass 11.1 and go to 12.0 looking at the latest changes.

**Comment by wmathurin** [comment]
12.0 should be released by the end of April.
