### ISSUE TITLE
Can we update this library to latest react native version?

### ISSUE THREAD

**Issue by SDE-Arvind** [forcedotcom/SalesforceMobileSDK-ReactNative#337]

**Comment by wmathurin** [comment]
We will be on 0.70.13 (which includes Xcode 15 fixes) in our next release 11.1 due later this month.
In our next major release 12.0 early next year, we should be moving to the latest React Native available at the time. #safeharbor

**Comment by wmathurin** [comment]
Mobile SDK 12.0 was just released yesterday 4/25 and it uses React Native 0.73.6 - which was the latest as of last week-end (0.74 just shipped on 4/22).
