### ISSUE TITLE
Salesforce login page has http link which prevents play store encrypted data requirement

### ISSUE THREAD

**Issue by socialsuiteDavid** [forcedotcom/SalesforceMobileSDK-ReactNative#338]
On the login page if you click "forgot my password" and then "need help logging in" the site will access: http://salesforce.vidyard.com (not https) which means if you have declared that the app uses encrypted data transfers then the app will be removed from the playstore, or you can remove the declaration.

Is there some way to remove this link or update it to https?

**Comment by wmathurin** [comment]
What login host are you using in your bootconfig ?

**Comment by wmathurin** [comment]
Closing for lack of response to our last question.
