### ISSUE TITLE
queryMore should accept a path

### ISSUE THREAD

**Issue by mjmasn** [forcedotcom/SalesforceMobileSDK-ReactNative#339]
`nextRecordsUrl` returned by the query API `/services/data/v59.0/query?q=...` is already a bare path. Currently passing that path into `queryMore` fails because for some reason it's expecting a full https:// url and tries to parse the path out of that. The error message is fairly questionable as well, must be a valid what?

> queryMore failed: url must be a valid

That check could probably be removed entirely, as it's highly likely that a `queryMore` call would only ever use the `nextRecordsUrl` returned by a previous `query` call

**Comment by wmathurin** [comment]
That makes sense. We added this enhancement request to our internal work tracking system.

**Comment by wmathurin** [comment]
Fixing with https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/343
Will be in our next release (11.1).
