### ISSUE TITLE
Cannot resolve the symbol 'PackageList'

### ISSUE THREAD

**Issue by jais-shivam** [forcedotcom/SalesforceMobileSDK-ReactNative#341]
I am updating my Salesforce Mobile SDK from 10.2 to 11.0.1 while doing it I am getting this error. -I have created a new project in which sdk is 11.0.1 when I am trying to add the packages that I am using i get the below error message tried many solutions but none of them are working.

java.lang.Exception: Calling [myProject/node_modules/@react-native-community/cli/build/bin.js, config] finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

I have resolved this issue by deleting the below line from build.gradle(app) and setting.gradle.

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

But after this, i am getting this new error in my 
MainApplication.java- 
**Cannot resolve the symbol 'PackageList'** 
to solve this I have tried deleting the node module and adding a new node module.

can someone help me to resolve this issue?

**Comment by wmathurin** [comment]
Have you seen this related post: https://stackoverflow.com/questions/70992083/android-error-cannot-resolve-symbol-packagelist ?

**Comment by jais-shivam** [comment]
@wmathurin Yes I have seen this post I tried doing gradle sync and build but still i am getting this issue.

**Comment by wmathurin** [comment]
Could you try with the latest version of Mobile SDK (12.0) which uses a more recent version of React Native.

**Comment by wmathurin** [comment]
We don't believe the issue still exists in the latest version of Mobile SDK.
