### ISSUE TITLE
Refresh Token Issue 

### ISSUE THREAD

**Issue by manishCapG** [forcedotcom/SalesforceMobileSDK-ReactNative#344]
Hi, I am working on app which is built on top of ReactNative and SalesforceMobileSDK. I am using Salesforce login authentication mechanism and able to login and use the app without any issues, but when I keep my device on background mode for 1 day and opens it after token expire, the API(oauth.getAuthCredentials) is throwing the error saying refresh token error. Find below log for more details. I get oauth from "react-native-force" library;

<img width="183" alt="image" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/110014892/3abdf892-33cf-41b8-93a6-39b44f6c2385">

Can You Please look into this ASAP.
Or Can you please suggest me with any resolution.

**Comment by manishCapG** [comment]
@wmathurin I am using #v10.2.0 Mobile SDK
it is on iOS and Android

**Comment by wmathurin** [comment]
Could possibly try with the latest version of the MSDK (11.1)?

**Comment by NewTech2000** [comment]
Is there any way to get a new access token after Expiring current access token?

**Comment by wmathurin** [comment]
There is an API to get a new access token (see [doc](https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_refresh_token_flow.htm&type=5)). Mobile SDK takes care of doing that transparently when you use our APIs to send requests to the server.

**Comment by NewTech2000** [comment]
@wmathurin 

I am developing a hybrid app using Salesforce react-native. When the access token expires I must handle the re-login process. I want to get a new access token after it expires the current access token without the user logout and re-login.

I have used the below code to get current user data and it returns current user data

import { oauth } from "react-native-force";

oauth.getAuthCredentials(
          (res) => resolve(res),
          async (e) => {
            reject(e);
          }
        );
but when I called the below code to get a new access token after it expires in the Android app, it returned a new access token but the IOS app logout from the oauth.

 oauth.authenticate(
          (res) => resolve(res),
          async (e) => {
               reject(e);
          }
        );
I need to get a new access token after expire current access token. When the access token expires I must handle the re-login process. I want to get a new access token after it expires the current access token without the user logout and re-login.

**Comment by manishCapG** [comment]
@wmathurin How do we setup Salesforce mobile connected App ?

There is a Bootconfig file in iOS and Android in which we have "remoteAccessConsumerKey" and "oauthRedirectURI" Keys
SO how can we configure remoteAccessConsumerKey and oauthRedirectURI for Salesforce Mobile SDK ?
How to generate oauthRedirectURI ?

**Comment by wmathurin** [comment]
You copy the values from your connected app settings.
There is a [chapter](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/intro_oauth.htm) on the topic in the documentation.

**Comment by manishCapG** [comment]
@wmathurin 
error=invalid_scope&error_description=the%20requested%20scope%20is%20not%20available
I get this error after i try to set connected app

**Comment by wmathurin** [comment]
What scope did you configure for your connected app? They need to be a super set of the ones the client app requests.

**Comment by manishCapG** [comment]
<img width="1066" alt="image" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/110014892/09f0088f-9bf6-46d1-8f74-caa0f6cdf5cb">

https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/connected_apps_howto.htm#oauth

All these as mentioned on this attachment i went through these steps only

**Comment by wmathurin** [comment]
Get auth credentials just give you the currently stored access token but it could have expired. 
To make sure your access token is valid,  firstdo a cheap authenticated call to "rehydrate" the access token if needed and then do the call to `getAuthCredentials`. That will ensure that the access token is valid.

```javascript
import {oauth, net} from 'react-native-force';
net.resources(
    (response) => {
        oauth. getAuthCredentials(...);
    }
);
```

**Comment by manishCapG** [comment]
Can You please share the response for expired token
