### ISSUE TITLE
App Crashes on logout 

### ISSUE THREAD

**Issue by manishCapG** [forcedotcom/SalesforceMobileSDK-ReactNative#349]
<img width="938" alt="Screenshot 2023-12-14 at 6 04 37 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/110014892/f2d24ab2-ad21-4f87-822c-bc903e6be5ab">

<img width="1152" alt="Screenshot 2023-12-14 at 6 04 03 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/110014892/219de624-964b-4541-90d5-b2fc5a4d5ea8">

When I logout I am facing logout issue as attached in screenshot.
This issue i face rare and sometimes.

Can you please look into? 
 and provide resolution 

I am using **react-native force version** **#v10.2.0**

**Comment by wmathurin** [comment]
Are you using MobileSync? Could you stop all sync operations in flight before starting the logout?
See https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_stop_start_sync_operations.htm

**Comment by manishCapG** [comment]
@wmathurin Please send me react-native link
How Can I stop all sync operations before starting the logout ?

**Comment by wmathurin** [comment]
It's not exposed to React Native at this point. You will have to call it from native code.

**Comment by manishCapG** [comment]
@wmathurin Can you write an example How ?

**Comment by wmathurin** [comment]
It will be fixed in the next version of Mobile SDK. See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/351
