### ISSUE TITLE
React Native version is too old

### ISSUE THREAD

**Issue by AnuragTiwari1** [forcedotcom/SalesforceMobileSDK-ReactNative#355]
Hi, 

I was trying to integrate react-native-vision-camera into our project but it is giving me below error:
https://github.com/mrousavy/react-native-vision-camera/issues/2080

it needs 0.71+ version of react native. when I tried to upgrade manually with help of 
https://react-native-community.github.io/upgrade-helper/?from=0.70.14&to=0.71.15

it shows that I will need to modify SalesforceReactActivity.

Please upgrade react native version so that we can use latest libraries

**Comment by wmathurin** [comment]
In dev, we have already upgraded to 0.72 (see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/345).
That will be in our upcoming release MSDK 12.0 (planned for spring).
