### ISSUE TITLE
App is crashing while calling (oauth.logout();) on IOS Device

### ISSUE THREAD

**Issue by ashish-kumar1994** [forcedotcom/SalesforceMobileSDK-ReactNative#356]
SDK Version  - 10.2.0

Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]' was thrown while invoking querySoup on target SFSmartStoreReactBridge with params (
        {
        isGlobalStore = 0;
        querySpec =         {
            indexPath = "<null>";
            matchKey = "{assets:ParentId}:\"02i2z000001IdAxAAK\"";
            order = ascending;
            orderPath = "CarEquipment__c";
            pageSize = 2000;
            queryType = match;
        };
        soupName = assets;
    },
    5233947
)

**Comment by Hema-Sridharan** [comment]
Hi, Facing the same issue on iOS device after log out, after upgrading to SDK version 11.0.1

Error:
Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]' was thrown while invoking querySoup on target SFSmartStoreReactBridge with params (
        {
        isGlobalStore = 0;
        querySpec =         {
            indexPath = "<null>";
            matchKey = "{assets:ParentId}:\"02i2p00000hI1SxAAK\"";
            order = ascending;
            orderPath = "CarEquipment__c";
            pageSize = 2000;
            queryType = match;
        };
        soupName = assets;
    },
    155565
)

**Comment by wmathurin** [comment]
This issue has been fixed in dev. See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/351
It will be in our next version of the Mobile SDK.

**Comment by Hema-Sridharan** [comment]
Hi @wmathurin, when can we expect the next version of Mobile SDK release.

**Comment by Hema-Sridharan** [comment]
Hi @wmathurin, when can we expect the next version of Mobile SDK release.

**Comment by wmathurin** [comment]
MSDK 12.0 is scheduled to come out in April/May. #safeharbor

**Comment by Hema-Sridharan** [comment]
Thanks @wmathurin , please let us know this fix release date is decided in April.

**Comment by Hema-Sridharan** [comment]
@wmathurin can you let us know the exact release date in Apr/May.

**Comment by wmathurin** [comment]
We are in the final round of testing. MSDK 12 should be released by the end of April.
