### ISSUE TITLE
Upgrading past 0.70.14

### ISSUE THREAD

**Issue by oktalk** [forcedotcom/SalesforceMobileSDK-ReactNative#359]
Just trying to upgrade past 0.70.14. I attempted to upgrade to 0.70.15 and got the following error during the Android build:
`Could not find com.facebook.react:react-native:0.70.14`

Is there anything that would hold this project back from upgrading to RN 0.73? I haven't gotten too far in my upgrade since I'm getting errors already, but I would like to know if this will even work.

**Comment by wmathurin** [comment]
Our dev branch (the future MSDK 12.0) is on 0.72.7 (see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/345) - we had to upgrade gradle too.

**Comment by wmathurin** [comment]
I recommend you wait for MSDK 12 (which uses RN 0.73.6) and should be released by the end of April.
