### ISSUE TITLE
Is Sync related records available in 5.2.0?

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-ReactNative#36]
I just read the documentation and found there is a new sync target in 5.2.0

However, the page doesn't mention about hybrid app

Is it available in ReactNative and how to use it?

https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_sync_related.htm

**Comment by wmathurin** [comment]
We have not documented the hybrid / react-native use of that new sync target.
We are planning to do that in the future, and that point we will probably add some JavaScript helpers to make it easier to setup such syncs.
