### ISSUE TITLE
Server Error: Can't connect to the server: Unexpected HTTP response code from the identity service: 404

### ISSUE THREAD

**Issue by rahulchauhan9** [forcedotcom/SalesforceMobileSDK-ReactNative#361]
Not able to log into any application created with v11.0.0. 
Getting this error when a user enters user id and password and tries to log into the app.

 **Server Error: Can't connect to the server: Unexpected HTTP response code from the identity service: 404**

Full error logs from Xcode 

```
Custom_APP[22681:1636695] [SalesforceSDKCore] CLASS: SFIdentityCoordinator SFIdentityCoordinator:Starting identity request at https://test.salesforce.com/id/00D3S0000008hTzUAI/00D3S0000008iJbUAI 

Custom_APP[22681:1635560] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service 

Custom_APP[22681:1636050] [connection] nw_connection_add_timestamp_locked_on_nw_queue [C3] Hit maximum timestamp count, will start dropping events 

Custom_APP[22681:1636050] [connection] nw_connection_add_timestamp_locked_on_nw_queue [C1] Hit maximum timestamp count, will start dropping events 

Custom_APP[22681:1636050] [connection] nw_connection_add_timestamp_locked_on_nw_queue [C4] Hit maximum timestamp count, will start dropping events 

Custom_APP[22681:1635560] [SalesforceSDKCore] CLASS: SFUserAccountManager Error retrieving idData:Error Domain=com.salesforce.Identity.ErrorDomain Code=769 "Unexpected HTTP response code from the identity service: 404" UserInfo={error=bad_http_response, error_description=Unexpected HTTP response code from the identity service: 404, NSLocalizedDescription=Unexpected HTTP response code from the identity service: 404}


```

**

> I can see Login successful in the user login history on salesforce, but on the app, it returns Unexpected HTTP response code from the identity service: 404"

**

Additional Information:

- The login did work until last Friday (22 Mar). I did not change anything in the app configuration and it suddenly stopped working in all the apps I have created using forcereact.
- Attempts to revert changes and use an older Xcode archive did not resolve the issue.
- Even creating a new app with force react with the latest SDK version v11.0.0  did not solve the problem.

Screenshots attached.
Any insights or suggestions regarding this issue would be greatly appreciated.

<img width="523" alt="Screenshot 2024-03-26 at 8 44 13 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/31926797/3493090c-716e-4540-9cc0-f86f265ee03b">

<img width="503" alt="Screenshot 2024-03-27 at 12 23 37 AM" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/31926797/4a5b9115-8c7a-49be-81cf-cc624df5454a">

**Comment by lokendra-jhala-mtx** [comment]
This issue only occurred in Gov Cloud org for normal org it's working as expected.

**Comment by wmathurin** [comment]
The issue is now solved see
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3709#issuecomment-2099739964
