### ISSUE TITLE
React native version is very old. I want to use the RN 0.71+ but due to this sdk not able to use it.

### ISSUE THREAD

**Issue by vinod1988** [forcedotcom/SalesforceMobileSDK-ReactNative#363]
Hi Team

Currently i am facing the RN 0.70 issue. I want latest sdk to be supported for the RN 0.71 plus. 

Please let me know when i get the new version of sdk 12 release.

@wmathurin Please help

**Comment by wmathurin** [comment]
In dev, we are on 0.73.6 (see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/360).
It will be part of our next release MSDK 12.0 - which should ship by the end of April.
