### ISSUE TITLE
issue with removeFromSoup in smartstore SDK 12.0.1 

### ISSUE THREAD

**Issue by LuoShao** [forcedotcom/SalesforceMobileSDK-ReactNative#368]
<img width="914" alt="Screenshot 2024-05-13 at 22 37 07" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/20217641/494d603e-000f-4bbf-a2d4-e751cad4f7a4">

undefined does not exist in Java,  undefined should be changed to null

**Comment by wmathurin** [comment]
This is typescript not java. Where are you getting an error?

**Comment by LuoShao** [comment]
@wmathurin  I made an error when calling the removeFromSoup method of smartstore. After I modified the above code, smartstore can run normally.

**Comment by wmathurin** [comment]
There was actually an issue (ReactNativeMap.isNull throwing when the key is missing). It's getting fixed in dev (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2583/commits/c0cac2d5eaf627d325909ebe5e7a6fdd0c5931f9).
