### ISSUE TITLE
Unable to install other npm library

### ISSUE THREAD

**Issue by sneka2611** [forcedotcom/SalesforceMobileSDK-ReactNative#372]
Unable to install other npm library , after create project, It throwing following error.
I tried to install  drawer react navigation, I can't install, I  tried different solution to fix this. Still I cant' find solution, Any one help me to find, What I missed ?
<img width="1011" alt="Screenshot 2024-06-27 at 11 16 07 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/54669196/5a75c533-dffe-42bd-9a66-eb2abe7a49dd">

**Comment by wmathurin** [comment]
What version of Mobile SDK are you using?
How did you create your project?

**Comment by sneka2611** [comment]
1. I am using Mobile SDK version 12.0.1
2. I am using  "forcereact create" command line to create project . I referred this link https://developer.salesforce.com/docs/platform/mobile-sdk/guide/react-native-new-project.html.

**Comment by sneka2611** [comment]
I can resolve the issue, after spend a day. 
I have installed forcereact version12.0.1. Now I uninstalled it and  install version 11.0.0 with npm install forcereact@11.0.0 --force. Now I can install any library in my react project.

**Comment by K-sivasankar** [comment]
Hi @sneka2611 , I am facing same issue.
How to resolve it
