### ISSUE TITLE
Deleting Records from Soup Database Does Not Decrease Database Size

### ISSUE THREAD

**Issue by dheeraj-bartwal** [forcedotcom/SalesforceMobileSDK-ReactNative#379]
I am encountering an issue with the deleteAllSyncedImagesById function in our project, which is intended to remove records from the soup database. The function successfully deletes records, as confirmed by the testgetImagesByStop function returning 0 content. However, the size of the database does not decrease as expected after deletion.

`async function deleteAllSyncedImagesById(imageSoupEntryId) {
  console.log('deleteAllSyncedImagesById', imageSoupEntryId);
  if (!imageSoupEntryId?.length) return Promise.resolve(null);
  return new Promise((resolve, reject) => {
    smartstore.removeFromSoup(
      storeConfig,
      'ContentVersion',
      imageSoupEntryId,
      (result) => {
        resolve();
      },
      (error) => {
        console.log('deleteAllSyncedImagesByIdErr', error);
        reject();
      },
    );
  });
}

function testgetImagesByStop() {
  return new Promise((resolve, reject) => {
    const target = `SELECT {ContentVersion:_soup} FROM {ContentVersion}`;

    let querySpec = smartstore.buildSmartQuerySpec(target, 500);
    smartstore.runSmartQuery(
      storeConfig,
      querySpec,
      async (cursor) => {
        console.log(
          'testgetImagesByStop',
          cursor?.currentPageOrderedEntries?.flat()?.length,
        );
        if (cursor?.currentPageOrderedEntries?.length > 0) {
          resolve(cursor?.currentPageOrderedEntries?.flat());
        } else {
          resolve(null);
        }
      },
      (error) => {
        reject(error);
      },
    );
  });
}`

Expected Behavior:
After executing deleteAllSyncedImagesById, the size of the soup database should decrease, reflecting the removal of all specified records.

Actual Behavior:
The deleteAllSyncedImagesById function completes successfully and deletes records as confirmed by testgetImagesByStop.
The database size does not decrease after the deletion of records, despite the fact that no records are returned by testgetImagesByStop.

**Comment by shivamcfs** [comment]
Hi @dheeraj-bartwal, I am also facing same issue, any luck on that?

**Comment by wmathurin** [comment]
SmartStore uses SQLCipher (which is SQLite with encryption) under the hood.
When content is deleted from an SQLite database, the content is not usually erased but rather the space used to hold the content is marked as being available for reuse.
There is a command (see [here](https://sqlite.org/lang_vacuum.html)) to reclaim that space but we are not exposing it through the SmartStore React Native bridge.
You will have to invoke it from the Java/Swift code of your application.
