### ISSUE TITLE
Crash while try to upsert single record to soup

### ISSUE THREAD

**Issue by rublemangoo** [forcedotcom/SalesforceMobileSDK-ReactNative#38]
Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]' was thrown while invoking syncUp on target SFSmartSyncReactBridge with params (
        {
        isGlobalStore = 0;
        options =         {
            mergeMode = OVERWRITE;
        };
        soupName = Attendance;
        target =         {
            query = "SELECT Id,Name,OsPcmt__Assigned_To__c,OsPcmt__Assignment__c,OsPcmt__Assignment_Type__c,OsPcmt__Location__c,OsPcmt__Assignment_Parent_Id__c,OsPcmt__Operation__c,OsPcmt__Student_Id__c,OsPcmt__Attended__c,OsPcmt__Status__c,OsPcmt__Student__c,OsPcmt__Assignment_Student_Id__c,OsPcmt__Attendance_Result__c,OsPcmt__Check_In_Code__c,OsPcmt__Check_In_Location_Accuracy__c,OsPcmt__Check_In_Location__Latitude__s,OsPcmt__Check_In_Location__Longitude__s,OsPcmt__Check_In_Location__c,OsPcmt__Check_In_Time__c,OsPcmt__Check_Out_Location_Accuracy__c,OsPcmt__Check_Out_Location__Latitude__s,OsPcmt__Check_Out_Location__c,OsPcmt__Check_Out_Location__Longitude__s,OsPcmt__Check_Out_Time__c,OsPcmt__DNA_Documents_Uploaded__c,OsPcmt__DNA_Reason_Provided__c,OsPcmt__DNA_Reviewed__c,OsPcmt__DNA_Session_Date_Time__c,OsPcmt__DNA_Session_Duration__c,OsPcmt__DNA_Type__c,OsPcmt__Check_In_Code_Valid__c,OsPcmt__Check_In_Location_Distance__c,OsPcmt__Check_Out_Location_Distance__c,OsPcmt__Check_Out_Required__c,OsPcmt__Did_Not_Attend__c,OsPcmt__Duration__c,OsPcmt__User_is_Student__c FROM OsPcmt__Attendance__c WHERE ";
            type = soql;
        };
    },
    57
)

RCTFatal
-[RCTBatchedBridge callNativeModule:method:params:]
__33-[RCTBatchedBridge handleBuffer:]_block_invoke.477
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_queue_serial_drain
_dispatch_queue_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread3
_pthread_wqthread
start_wqthread

**Comment by wmathurin** [comment]
What version of the Mobile SDK are you using?

**Comment by rublemangoo** [comment]
@wmathurin, my SDK version is 5.2.0

**Comment by wmathurin** [comment]
Could you share the few lines of JavaScript you used when invoking syncUp?
Thanks.

**Comment by rublemangoo** [comment]
Was issue with apex trigger
