### ISSUE TITLE
PhaseScriptExecution fails for Hermes Engine after install of react-native-reanimated

### ISSUE THREAD

**Issue by mstohr1975** [forcedotcom/SalesforceMobileSDK-ReactNative#380]
Did anybody get react-native-reanimated package to work with Mobile SDK?

I get following error after installing the package into vanilla Mobile SDK project:

The following build commands failed:
PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users//Library/Developer/Xcode/DerivedData/ReanimateTest-cbxampfvgdijsheyaooblqxhwpyc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hermes-engine.build/Script-46EB2E0001C820.sh (in target 'hermes-engine' from project 'Pods')

Deleting .xcode.env.local, clearing cache or deleting DerivedData did not resolve. Thus I believe it is systemically to Mobile SDK setup. Anybody had this before?

**Comment by wmathurin** [comment]
What version of Mobile SDK are you using?

**Comment by wmathurin** [comment]
We just released Mobile SDK 12.1.0 which works with React Native 0.74.3. Do you mind giving it a try to see if the issue still exists?

**Comment by iamsurajnambiar** [comment]
@mstohr1975 Can you guide how did you set the reactNativePath in post_install exactly ?
