### ISSUE TITLE
Duplicate records of child object getting inserted in CRM when the parent record is deleted.

### ISSUE THREAD

**Issue by psinghal213** [forcedotcom/SalesforceMobileSDK-ReactNative#381]
SDK version used: 10.2.0

Steps to replicate:
1. Login to custom Mobile application after setting up the connected app settings on salesforce and configuring the secrets in bootconfig.plist.
2. After initial/first sync is complete, Navigate to Account list screen
3. Open an Account (Account A) -> Create a new Contact on this account.
4. Navigate back to Account list screen.
5. Choose a different account from the list (Account B).
6. Login to Salesforce (on browser) as an admin role and delete Account B from Salesforce CRM. (note application is offline so Account B is still present in mobile local DB)
7. Switch back to mobile application and create a contact on Account B
8. Start a data Sync.
9. Data sync will receive error on Contact Syncup “Entity is deleted” (Since we deleted Account B from Salesforce CRM during the process).
10. Open Workbench or Salesforce Lightning page and navigate to Account A, we will be able to see 2 contacts created on Account A even though we just created 1 contact from mobile on Account A. so the record is duplicated. both records contain the same values for all the fields present on contact object even the same createdDate and same local ID passed from mobile custom app.

NOTE: Account is the parent Object whereas Contact is a child object linked to account object using a specific field called "AccountId".
<img width="756" alt="Contact_Mobile_SyncUp_Error" src="https://github.com/user-attachments/assets/1215bc3f-cbd0-4a50-848a-2482f258cdae">
<img width="1315" alt="Workbench_Contact_Dupliacte" src="https://github.com/user-attachments/assets/ba6d94f7-30f1-4e32-89d4-0f590f5cae78">

**Comment by wmathurin** [comment]
What type of sync up target are you using to save records back to the server?

**Comment by wmathurin** [comment]
Are you using [ParentChildrenSyncUpTarget](https://developer.salesforce.com/docs/platform/mobile-sdk/guide/entity-framework-sync-related.html)?

**Comment by wmathurin** [comment]
Closing issue. We have not heard from customer in a long time.
Please open a new issue if you are still having the same problem and are using the latest Mobile SDK.
