### ISSUE TITLE
Provide example on using Expo AuthSession

### ISSUE THREAD

**Issue by oktalk** [forcedotcom/SalesforceMobileSDK-ReactNative#385]
Could anybody provide an example of using Expo AuthSession with Salesforce? I've been using this SDK since version 10, and it is a nightmare to upgrade. I feel like things would be a lot easier if we could just build apps in the recommended way by using a framework like Expo.

**Comment by wmathurin** [comment]
We are a small team with limited capacity, and currently, there are no plans to support Expo.

**Comment by dipakparmar** [comment]
@oktalk Check this out https://github.com/dipakparmar/salesforce-auth-expo
