### ISSUE TITLE
Integration of react-native-reanimated with Salesforce React Native app causing Pod install and Fabric architecture issues

### ISSUE THREAD

**Issue by iamsurajnambiar** [forcedotcom/SalesforceMobileSDK-ReactNative#389]
I am integrating react-native-reanimated into my Salesforce React Native app. During pod install, I encountered the following error:

[!] An error occurred while processing the post-install hook of the Podfile.

no implicit conversion of nil into String

/Users/ind040101397/Documents/forcedotcom/sgnext/node_modules/react-native/scripts/cocoapods/utils.rb:83:in `join'
/Users/ind040101397/Documents/forcedotcom/sgnext/node_modules/react-native/scripts/cocoapods/utils.rb:83:in `block (2 levels) in set_node_modules_user_settings'
...
/opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/bin/pod:25:in `<main>'

Following the resolution from a similar [thread](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/380), I modified my post_install section as follows:

      post_install do |installer|
        if defined?($config[:reactNativePath]) && !$config[:reactNativePath].nil?
          react_native_post_install(
            installer,
            $config[:reactNativePath],
            :mac_catalyst_enabled => false
          )
        else
          puts "reactNativePath is not defined or is nil!"
        end
      end

After following this approach and cleaning the pod cache (pod cache clean --all), I managed to bypass the initial error. However, I encountered a Fabric architecture issue afterward when running npx react-native run-ios.

**Steps Taken:**
cd ios
pod cache clean --all
pod install
Removed .xcode.env.local
Tried running the project again: npx react-native run-ios

**Current Issue:**
I'm now stuck with a Fabric architecture issue, which seems related to the integration of react-native-reanimated with Salesforce's Mobile SDK. I've tried several methods, but nothing has resolved the problem.
<img width="402" alt="Screenshot 2024-10-08 at 11 51 15 PM" src="https://github.com/user-attachments/assets/81746bdb-2408-476f-9f58-1c1ce66bac75">

**Environment:**

React Native: 0.74
react-native-reanimated version: 3.15.4
macOS: Apple Silicon M2 Pro
Cocoapods: 1.15.2
Any advice or further troubleshooting steps would be greatly appreciated!

**Comment by wmathurin** [comment]
We just released Mobile SDK 12.2, which depends on React Native 0.74.5. 
Could you try and see if you are still having the same issues?

**Comment by wmathurin** [comment]
Closing issue - we have not heard from customer.
Please open an new issue if you are still running into the same problem and are running the latest Mobile SDK.
