### ISSUE TITLE
Salesforce Mobile SDK React Native - Inflight library issue

### ISSUE THREAD

**Issue by mingfeng-alphline** [forcedotcom/SalesforceMobileSDK-ReactNative#391]
During our source code scanning, the inflight library (version 1.0.6) was flagged as a risk. This library is used on Salesforce Mobile SDK Version 12.0.1 (package with ReactNative version 0.73). We did find out that this inflight library has since been deprecated. 

Is there a solution to mitigate this risk? 
What function does this inflight library perform?

**Comment by wmathurin** [comment]
Inflight is packaged with React Native. We recommend you open an issue against [React Native github repo](https://github.com/facebook/react-native).
