### ISSUE TITLE
How to Refresh Access Token Within SDK Without Losing Session

### ISSUE THREAD

**Issue by imransiddiquirn** [forcedotcom/SalesforceMobileSDK-ReactNative#393]
Hi team,

I’m looking for a way to refresh the access token directly within the Salesforce Mobile SDK for react-native-force to avoid session loss. Currently, I’m manually refreshing the token by calling the API endpoint for token refresh (/services/oauth2/token) using the stored refresh token and updating the local state with the new access token.

Issue: After refreshing the token this way, the SDK doesn’t seem to recognize the new token, resulting in a lost session and forcing the user to reauthenticate.

Request: Is there a method within the SDK to renew the access token, or a recommended approach for refreshing it internally without disrupting the session?

Thank you!

**Comment by wmathurin** [comment]
The easiest way is to send a "cheap" request that requires authentication, the Mobile SDK will automatically refresh the access token if it is no longer valid (assuming the refresh token is still valid). We even have a `cheapRequest` exposed on [iOS](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI.h) and on [Android](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java#L982) for that very purpose.
If you want to do it from you React Native javascript code, just call [this method](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/blob/dev/src/react.force.net.ts#L105).

**Comment by imransiddiquirn** [comment]
Thank you for the suggestion! I’ve implemented the "cheap" request as mentioned, which checks for the access token's validity. When it's invalid, the SDK automatically refreshes it. Here’s my implementation for that:

`const ensureValidToken = () => {
  return new Promise((resolve, reject) => {
    net.resources(
      (response) => {
        // Token is valid, get credentials
        oauth.getAuthCredentials((credentials) => {
          dispatch(getAuthTokenDetails({...authTokenDetails, accessToken: credentials.accessToken}));
          dispatch(authToken(credentials.accessToken));
          resolve(credentials.accessToken);
        }, reject);
      },
      (error) => {
        // Token expired, try refreshing
        const refreshToken = authTokenDetails?.refreshToken;
        const body = `/token?grant_type=refresh_token&client_secret=${ENVIRONMENT.tokenClientSecret}&client_id=${ENVIRONMENT.tokenClientID}&refresh_token=${refreshToken}`;
        net.sendRequest(
          `/services/oauth2`,
          body,
          (response) => {
            dispatch(getAuthTokenDetails({...authTokenDetails, accessToken: response.access_token}));
            dispatch(authToken(response.access_token));
            resolve(response.access_token);
          },
          reject,
          'POST',
          { 'Content-Type': 'application/x-www-form-urlencoded' }
        );
      }
    );
  });
};`

I am receiving the new access token, but I am facing the issue SmartStoreReactBridge.clearSoup failed: "java.lang.Exception: No user account found".

Let me know if there’s anything I need to check to resolve this. Thanks!

![image (2)](https://github.com/user-attachments/assets/1d53b1cd-83eb-4e16-8321-edd403e6ad18)
![image (3)](https://github.com/user-attachments/assets/9daf9c73-db92-47ec-b9a3-2cd15c0e8457)
