### ISSUE TITLE
HTTP Response error 411 forceClient.sendRequest method POST

### ISSUE THREAD

**Issue by rublemangoo** [forcedotcom/SalesforceMobileSDK-ReactNative#43]
I have an error while try to send post request to salesforce. Look like 'Content-length' was lost. Could you please check, maybe this issue related to [this](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/37)

SDK version v5.3.0

**Comment by bhariharan** [comment]
Thanks for bringing this to our attention. We will investigate.

**Comment by wmathurin** [comment]
Could you try with our most recent release (v6.0)?

**Comment by bhariharan** [comment]
This was fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2032). Please try with `Mobile SDK 6.1` and reopen if it still exists.
