### ISSUE TITLE
How to upload attachment with 'react-native-force'

### ISSUE THREAD

**Issue by rublemangoo** [forcedotcom/SalesforceMobileSDK-ReactNative#44]
I am building react-native application with SF Mobile SDK 5.3. Currently, I have a task to upload attachment to salesforce. Could you please provide action plan how to do this. 

jsforce don't work with react-native.

**Comment by bhariharan** [comment]
@rublemangoo This forum is reserved for bugs/issues with our code. Please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1) for any other queries/discussions.

**Comment by rublemangoo** [comment]
@bhariharan, thanks for the link. But, this is a documentation issue. SDK doc suggest to use other SF approach to upload a file. And this is an issue: REST couldn't be but used because I don't have any way to login, or get a token. JsForce don't work at all.

**Comment by rublemangoo** [comment]
@bhariharan, looks like G+ community is dead...

**Comment by aantonyuk** [comment]
@bhariharan I have the same issue and I will be very happy if you provide us.

**Comment by wmathurin** [comment]
We support file upload -  see https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/react_native_binary_upload.htm
But you can only specify a file path not its content. Do you need to be able to specify a blob or base64 encoded string for the content?
