### ISSUE TITLE
Compiling release version fails with 'Couldn't follow symbolic link' message.

### ISSUE THREAD

**Issue by daraselia** [forcedotcom/SalesforceMobileSDK-ReactNative#48]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3.0
2. Issue found in Native App or Hybrid App: React native
3. OS Version: iOS 11
4. Device: iPad Air
5. Steps to reproduce:
> forcedroid create (react native)
> react-native run-android (all works so far)
> when following the steps described in this [link](https://facebook.github.io/react-native/docs/signed-apk-android.html) it fails on './gradlew assembleRelease' saying:

`Could not list contents of '/Users/ilya/Playground/test25/mobile_sdk/salesforcemobilesdk-android/hybrid/HybridSampleApps/AccountEditor/assets/www/AccountEditor.html'. Couldn't follow symbolic link.`

6. Actual behavior: error compiling release version
7. Expected Behavior: successful generation of android app apk
8. Error Log:

`Could not list contents of '/Users/ilya/Projects/booker25-touch-android/mobile_sdk/salesforcemobilesdk-android/hybrid/HybridSampleApps/AccountEditor/assets/www/AccountEditor.html'. Couldn't follow symbolic link.`

**Comment by bhariharan** [comment]
@daraselia We don't currently support the `react-native` CLI. Please use `Android Studio` to compile the generated project.

**Comment by daraselia** [comment]
@bhariharan Could you maybe tell then how to bundle the app in Android Studio?

**Comment by bhariharan** [comment]
Please follow the instructions in our [development guide](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/preface_intro.htm).

**Comment by daraselia** [comment]
Thanks for the link. According to the guideline, the only available option to build apk is `gradlew assembleDebug`. Is there an option to build release version?

**Comment by bhariharan** [comment]
Use `assembleRelease`.

**Comment by daraselia** [comment]
When do that it complains:

`* What went wrong:
Could not list contents of '/Users/ilya/Projects/booker25-touch-android/mobile_sdk/salesforcemobilesdk-android/hybrid/HybridSampleApps/AccountEditor/assets/www/AccountEditor.html'. Couldn't follow symbolic link.`

**Comment by bhariharan** [comment]
How did you create the app?

**Comment by daraselia** [comment]
With `forcedoid`. Right after I install app I try to run `assembleRelease ` and it fails.

**Comment by bhariharan** [comment]
Could you try importing the project in `Android Studio` based on our instructions? Are you able to build the project with `Android Studio`?

**Comment by daraselia** [comment]
Yes I was only able to build debug not release with Android Studio.

Would you advice any other way to use SF mobile sdk without force CLI?

**Comment by bhariharan** [comment]
Looks like there's something going on with `assembleRelease`. I'm not sure why it's looking for `AccountEditor` only for release builds, even though it's not declared in `settings.gradle`. We will take a look. Thanks for reporting!

**Comment by bhariharan** [comment]
This has being fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/101) and will be a part of our upcoming release, `Mobile SDK 6.0`.
