### ISSUE TITLE
Smartstore Storage Speed with Encryption and External Storage

### ISSUE THREAD

**Issue by lpt-joshua** [forcedotcom/SalesforceMobileSDK-ReactNative#50]
Hi there,

I am currently trying to speed up the sync down process on my application and was thinking if removing encryption would speed up the time it takes to write into the storage, and if so could this be done from the RN library/Native libraries easily?

I'm also trying to increase the sync down process by using external storage on iOS but receive an error when trying to save into the storage:
`Saving external soup to file failed! encrypted: YES, soupEntryId: 120, soupTableName: TABLE_1, filePath: '/var/mobile/Containers/Data/Application/.../Documents/.../stores/.../store_external_soup_blobs/TABLE_1/soupelt_120', error: (null).`

code used when registering soup:
`let soupSpec = new smartstore.SoupSpec(soupName, ['externalStorage']);
smartstore.registerSoupWithSpec(getStoreConfig(), spec, indexFields, () => {...})`

Any advice would be greatly appreciated, and thank you ahead of time.

**Comment by bhariharan** [comment]
Encryption of data is at the core of everything the mobile SDK does, due to our security requirements. I would not encourage removing the encryption piece. However, if encryption must be removed, you will probably need to fork the Mobile SDK and make the required changes in your fork.

**Comment by lpt-joshua** [comment]
Thank you for the quick response.
