### ISSUE TITLE
bundling failed: ambiguous resolution: module

### ISSUE THREAD

**Issue by javimenesesdxc** [forcedotcom/SalesforceMobileSDK-ReactNative#57]
Hi,
Trying to install module in a react-native project. Adding this line:

"react-native-force": "https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git"

In package.json file, source link: https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/react_native_components.htm

Getting this error:

error: bundling failed: ambiguous resolution: module `/mypath/SDKTest/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/mypath/SDKTest/node_modules/react-native-force/node_modules/react-native/package.json`
  * `/mypath/SDKTest/node_modules/react-native/package.json`

Tried to remove node_modules with rm -rf and execute npm install, but same error.
Tried to execute npm start --reset-cache, same error.

What can I do? Thanks!

**Comment by wmathurin** [comment]
It's not a mobile sdk issue.
Please try the suggested solution here: https://github.com/react-native-community/react-native-svg/issues/463
