### ISSUE TITLE
Support on iOS 9

### ISSUE THREAD

**Issue by kdenz** [forcedotcom/SalesforceMobileSDK-ReactNative#59]
Hi! It says in 6.0 that you guys are dropping support for iOS 9 Devices, does that mean app wouldn't build or function properly on iOS 9 after I upgrade from 5.3 to 6.0? Thanks!

**Comment by bhariharan** [comment]
Yes - `iOS 10` is the minimum required OS version for `Mobile SDK 6.0`.
