### ISSUE TITLE
500 APEX_ERROR on iOS but not Android

### ISSUE THREAD

**Issue by jarmstrong** [forcedotcom/SalesforceMobileSDK-ReactNative#68]
```
"sendRequest failedError Domain=https://xxx-xxx-ed.my.salesforce.com/services/apexrest/ForceAppBranding?lastSync=2017-01-01T12:00:00.000? Code=500 "(null)" UserInfo={error=(
        {
        errorCode = "APEX_ERROR";
        message = "SvcForceAppException: Invalid format: \"2017-01-01T12:00:00.000?\" is malformed at \"?\"\n\nClass.SvcForceAppBranding.getDateTimeParameter: line 96, column 1\nClass.SvcForceAppBranding.doGet: line 31, column 1";
    }
)}"
```

My apexrest request works fine on Android, however I get this error when running the identical code from iOS.

```
    net.sendRequest(
      "/services/apexrest",
      "/ForceAppBranding?lastSync=2017-01-01T12:00:00.000Z",
      response => {
        ...
      },
      error => {
        ...
      }
    );
```

Any idea why this code would succeed on Android and give the strange error above on iOS?

Using a project built using the latest version of forcereact.

**Comment by jarmstrong** [comment]
Woops, I used the payload parameter instead of passing like above, and it works on both platforms. Odd that the above works on Android and not iOS though.

**Comment by wmathurin** [comment]
iOS is treating non 2xx responses as errors, and Android wasn't (it only calls the error callback, if the network request could not be placed).

In the upcoming release, we decided to have both platforms behave the same way - and we decided to go with the iOS behavior.

Here is the PR that is changing the Android behavior: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1629
