### ISSUE TITLE
rctfatal + 400

### ISSUE THREAD

**Issue by aantonyuk** [forcedotcom/SalesforceMobileSDK-ReactNative#71]
Many users when work with app face the issue: app crashes.
The only thing that was able to track:

<img width="1349" alt="screenshot at mar 19 21-53-07" src="https://user-images.githubusercontent.com/26109453/37616480-1a6b7c7c-2bc1-11e8-8921-8706b809e75c.png">

My dependencies:

<img width="1212" alt="screenshot at mar 19 21-53-27" src="https://user-images.githubusercontent.com/26109453/37616490-25e800b6-2bc1-11e8-8a4a-9a5ecfb46713.png">

**Comment by wmathurin** [comment]
There is not enough information for us to know what is going on.
Are you able to reproduce the crash in house. Can you tell what module is getting invoked when it crashes?

**Comment by bhariharan** [comment]
We are unable to reproduce this at our end. Feel free to reopen this issue if you have more information or can provide repro steps.
