### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by gla5001** [forcedotcom/SalesforceMobileSDK-ReactNative#72]
Im running into an issue on android with logging out. The code here

```
export const logout = () => {
    if (!logoutInitiated) {
        logoutInitiated = true;
        exec(null, null, "logoutCurrentUser", {});
    }
};
```

only allows the logout to be called once. So if you login as a user and then logout, you are prompted to sign in with your credentials again, but if you then logout again and sign in, you get signed right in, no credentials to fill in. How do you support multiple user logins with this code? after the first logout, the account is never deleted on the device and user is logged right back in.

This seems to be working as expected on iOS.

**Comment by wmathurin** [comment]
Following logout, the react native context should be re-initialized and therefore logoutInitiated should be back to being false.

**Comment by gla5001** [comment]
@wmathurin thanks. But for android, the context only seems to be re-initialized on the first logout. After that, it seems to keep the same context. Is this something that needs to be handled by the app?

**Comment by wmathurin** [comment]
Sounds like we might have a bug. We will have a look. Thanks.

**Comment by gla5001** [comment]
@wmathurin any updates on this?

**Comment by bhariharan** [comment]
@gla5001 We haven't looked into this issue yet. We will post an update here once we do.

**Comment by bhariharan** [comment]
@gla5001 I attempted to reproduce the issue you mentioned with our sample app and couldn't do so. It appears to be working as expected on `Android` - the context is being reset correctly after every logout attempt (I logged out 4 times in a row). Could you try using our sample app:
- Checkout [this repo](https://github.com/forcedotcom/SmartSyncExplorerReactNative).
- Run `node installandroid.js`.
- Run `npm start`.
- Import the `android/` folder in `Android Studio` and run the app.
- Log in and use the button on the action bar to logout.
Let me know if you find a way to reproduce the issue.

**Comment by gla5001** [comment]
I’ll try it out

**Comment by gla5001** [comment]
I’m happy to help with a fix for this if you point me in the correct direction

**Comment by bhariharan** [comment]
The issue exists only in the deferred authentication scenario. The reason is that the `ReactNative` context is never reset at the end of logout. The issue doesn't show up if auto-login is configured because in this case, we use the native `login` method which re-creates the `ReactNative` context and resets the flag (see the call `restartReactNativeApp()`):
```
    protected void login() {
        SalesforceReactLogger.i(TAG, "login called");
        clientManager.getRestClient(this, new RestClientCallback() {

            @Override
            public void authenticatedRestClient(RestClient client) {
                if (client == null) {
                    SalesforceReactLogger.i(TAG, "login callback triggered with null client");
                    logout();
                } else {
                    SalesforceReactLogger.i(TAG, "login callback triggered with actual client");
                    SalesforceReactActivity.this.restartReactNativeApp();
                }
            }
        });
    }
```
The issue shows up in the deferred authentication scenario because the method call in this case is `authenticate()`, which does NOT trigger a reset of the context:
```
    public void authenticate(final Callback successCallback, final Callback errorCallback) {
        SalesforceReactLogger.i(TAG, "authenticate called");
        clientManager.getRestClient(this, new RestClientCallback() {

            @Override
            public void authenticatedRestClient(RestClient client) {
                SalesforceReactActivity.this.setRestClient(client);
                getAuthCredentials(successCallback, errorCallback);
            }
        });
    }
```

**Comment by bhariharan** [comment]
I'm exploring options for a proper fix here, but I think we need a little bit of additional handling on the native side after logout, in `onLogoutComplete()` of `SalesforceReactActivity`.

**Comment by gla5001** [comment]
Sure. That sounds reasonable. I’ll close those open PRs I have out there

**Comment by gla5001** [comment]
Could you not just check shouldAuthentcate on logout and if it’s false, restart the app after logout?

**Comment by bhariharan** [comment]
Yeah, that was my thinking too. But that doesn't seem to work as well - it has a ripple effect. I'll continue exploring options and keep you posted.

**Comment by bhariharan** [comment]
@gla5001 After evaluating different use cases, I think the safest approach is the one you proposed - resetting the flag on the callback.
- [Android PR](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1687).
- [Bridge PR](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/73).
I verified that this does the trick. Thanks for the detailed findings and for the PRs.

**Comment by gla5001** [comment]
awesome! no problem at all

**Comment by Ruslan-Mz** [comment]
Hello @bhariharan!

Sorry for reviving such an old thread, but It seems there's now a similar issue on iOS with deffered login (using temlpate https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/ReactNativeDeferredTemplate, but version 10.0). When user logs out and then presses login, he is not asked for credentials and is just logged in immediately, even on first attempt. 
Can you please comment on what can be done to prevent this? Maybe some workarounds available? Or some more information is needed?

Regards,
Ruslan
