### ISSUE TITLE
No Support for Push Notifications?

### ISSUE THREAD

**Issue by salesvue-alex** [forcedotcom/SalesforceMobileSDK-ReactNative#74]
Unless I'm missing something, there doesn't seem to be support for handling Salesforce Push Notifications.

**Comment by bhariharan** [comment]
@salesvue-alex Push notification support is available on `ReactNative` apps as well, but it requires some native code to be written. We don't automatically receive notifications and pass them along to JS land.

**Comment by salesvue-alex** [comment]
It is my understanding that Salesforce Mobile Push Notifications (as described here: https://developer.salesforce.com/docs/atlas.en-us.pushImplGuide.meta/pushImplGuide/pns_overview.htm) have to be handled through the salesforce mobile sdk.  Is that the case?

If so, are there plans to support this for the ReactNative implementation of the sdk?  Other implementations of the sdk seem to support it (SalesforceMobileSDK-Android, SalesforceMobileSDK-iOS, SalesforceMobileSDK-CordovaPlugin).

**Comment by bhariharan** [comment]
The `ReactNative` implementation of the SDK simply exposes the underlying native functionality from `SalesforceMobileSDK-Android` and `SalesforceMobileSDK-iOS` via bridges. You can follow the instructions in that guide and implement push notifications in the native portion of your app and it would work for `ReactNative` as well. The notifications will be received in the native portion of your app though.

**Comment by salesvue-alex** [comment]
Ok, got it.  I wasn't fully understanding how Salesforce push notifications work.  All I had to do was log in with the mobile sdk, which automatically registered me to get the push notifications for my user.  After that the notifications came in through the device's native notification channels.  

Thanks!

**Comment by anishtr4** [comment]
It would be great if there is some kind of documentation for react native as well on how to procced with push notification. Some kind of minimal sample application does help us to procced further. I am not much into native IOS /android  so it is bit difficult.
