### ISSUE TITLE
"Missing Content-Type HTTP header" error when using net.update() in React Native app

### ISSUE THREAD

**Issue by brendacs** [forcedotcom/SalesforceMobileSDK-ReactNative#77]
After authenticating with `oauth` from `react-native-force`, I use this query in my app (replaced query with placeholder):

```
import { net } from 'react-native-force';

fetchData = () => {
    net.query('my query here',
               (response) => this.setState({ data: response.records }),
               (error) => console.log(error)
             );
};
```

The above works and succeeds. Then, I try to update information.
```
updateData = () => {
    this.setState({ update: "updating" });
    let data = this.state.data;
    data.field = 'NewValue';
    net.update('Object', this.state.data, 'field',
                (response) => this.setState({ update: response }),
                (error) => console.log(error)
              );
};
```

As a result (testing on iOS) I get these errors in the console (replaced object queried with placeholder):
```
2018-06-12 14:26:35:989 AppName[708:152449] invalid object passed to JSONDataRepresentation???
```
```
SFNetReactBridge.sendRequest failed: {"message":"sendRequest failedError Domain=https://cs70.salesforce.com/services/data/v42.0/sobjects/ObjectQueriedHere/ObjectIdQueriedHere Code=400 \"(null)\" UserInfo={error=(\n        {\n        errorCode = \"INVALID_CONTENT_TYPE\";\n        message = \"Missing Content-Type HTTP header\";\n    }\n)}"}
```

I am unsure how I would set the Content-Type HTTP header when using `net.update()` to send a request or why this error shows up in the first place. This file might be relevant: [SFNetReactBridge.m](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceReact/SalesforceReact/Classes/SFNetReactBridge.m).

**Comment by bhariharan** [comment]
@brendacs Which version of Mobile SDK are you using? Could you try the latest version, `Mobile SDK 6.1`?

**Comment by brendacs** [comment]
@bhariharan I am using version `6.1`.

**Comment by wmathurin** [comment]
You should be passing:
- sobject type
- id
- map with updated fields 

For instance to update the last name of a contact you would do:
```javascript
net.update('Contact', contactId, {LastName: lastNameUpdated}, ...)
```

We have unit tests for all our react native libraries.
They can be run from the main repo (look for the tests on the SalesforceReact library in our [iOS repo](https://github.com/forcedotcom/SalesforceMobileSDK-iOS) and our [Android repo](https://github.com/forcedotcom/SalesforceMobileSDK-Android).

The source code for the tests themselves live in our [ReactNative repo](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative).

E.g. the tests for the net library are [here](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/blob/master/test/net.test.js).
