### ISSUE TITLE
Ability to specify endpoint other than current user's connected org for net.sendRequest

### ISSUE THREAD

**Issue by fahey252** [forcedotcom/SalesforceMobileSDK-ReactNative#83]
After successfully authenticating, if want to make a request to get the current user's info at <https://login.salesforce.com/services/oauth2/userinfo> using the following: 
```javascript
function successHandler(response) {
  console.log(response)
}

function errorHandler(response) {
   console.log(response);
}

net.sendRequest('https://login.salesforce.com', '/services/oauth2/userinfo', successHandler, errorHandler);

// or

net.sendRequest('https://login.salesforce.com/services/oauth2/userinfo', '/', successHandler, errorHandler);
```
the response is: 
`"sendRequest failedError Domain=https://dev0-i360-dev-ed.my.salesforce.com/https://login.salesforce.com/services/oauth2/userinfo/?`.

What appears to be happening is the current users org domain is prepended to all requests. Authenticated requests may not always be to the current users domain. The method signature for net.sentRequest would make you think you could provide an absolute url or relative URL based on the current organization connected to.
``` javascript
export const sendRequest = (endPoint, path, successCB, errorCB, method, payload, headerParams, fileParams, returnBinary)
```

**Comment by wmathurin** [comment]
Right now sendRequest does not allow you specify the server to it. All requests go to the instance URL you are currently logged in against. We are planning to lift that limitation in an upcoming release. #safeharbor

If waiting is not an option, we recommend you tweak the Mobile SDK [code](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceReact/SalesforceReact/Classes/SFNetReactBridge.m) to fit your needs.

**Comment by fahey252** [comment]
Thanks! Ill do some more digging. However, now I think the bug is in SalesforceSDKCore as the correct endpoint is being passed in SFRestAPI.sendRESTRequest. See image below.

![image](https://user-images.githubusercontent.com/757838/42956458-005120c0-8b4e-11e8-8f42-8e15d9a8923f.png)

**Comment by fahey252** [comment]
After stepping through code, I figured out that using the following gets what I need/work around to original problem:
```javascript
net.sendRequest('', '/services/oauth2/userinfo', successHandler, errorHandler);
```
Turns out `<custom-domain>/services/oauth2/userinfo` works, don't have to use `login.salesforce` domain. Previously, it had not worked because I was using:
```javascript
net.sendRequest( '/services/oauth2/userinfo', '', successHandler, errorHandler);
```
Since the path was first, it was appending a '/' and saying <custom-domain>/services/oauth2/userinfo/ HTTP 404 not found.

**Comment by wmathurin** [comment]
When you build a SFRestRequest, you can specify the base URL: see [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestRequest.h#L159)

**Comment by wmathurin** [comment]
Good to know that you got it working.
We will still offer a way to provide the base URL from javascript in cases where you truly need to talk to another server (e.g. if you want to talk to Heroku).

**Comment by fahey252** [comment]
Thank you for your help. After stepping through code and working with other projects, I see the term `endpoint` used interchangeably... i.e. is the endpoint the domain only or does it include the path? Sometimes `endpoint` is only the (domain) or (scheme + domain) or (scheme + domain + path).

**Comment by wmathurin** [comment]
For us, end point is just the beginning of the path (corresponding to a servlet): /services/oauth2 is handled by the auth servlet, /services/data is handled by another one etc.

**Comment by bhariharan** [comment]
@fahey252 Could you try [this fix](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2598)?

**Comment by fahey252** [comment]
@bhariharan Yes, give me a little bit of time as I was pulled into some production support issues. Ill be in touch and thank you for your prompt help!

**Comment by bhariharan** [comment]
This has been addressed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2611) and will be in our next release.

**Comment by fahey252** [comment]
@bhariharan tested and confirmed the fix worked for me. The default baseUrl was `my.salesforce.com` however, I needed to make a request to a different domain, `content.force.com`, to get the current users profile picture. Setting the endpoint to the empty string and the path to the absolute URL worked.

Thank you!
