### ISSUE TITLE
Missing documentation for integration into existing app

### ISSUE THREAD

**Issue by bartolkaruza** [forcedotcom/SalesforceMobileSDK-ReactNative#86]
The [forcereact](https://www.npmjs.com/package/forcereact) cli provides an easy way to get started if you are generating a new app. It contains some best practices that can be used to figure out how to integrate the SF RN sdk and the native sdk's, but it would be even better if a clearly documented step by step approach would be published about how to integrate the sdk's into an existing React Native app.

**Comment by elie222** [comment]
Any updates on this?

**Comment by paritosh-yadav** [comment]
Hi @elie222 , @wmathurin @bartolkaruza , any updates?

**Comment by elie222** [comment]
If I remember correctly what I ended up doing was creating the app from scratch again using this SDK. I then copied all my files from my existing React Native project into it to get it working.

Worked fine for me.

**Comment by rwhitley** [comment]
@elie222 Not to say that it couldn't be refined, but you did in fact hit upon our documented recommendation for app migration:

"Recreate your app [in this case, create a Mobile SDK template app] with forcereact, and then migrate your app’s artifacts into the new template."

**Comment by patrickgalbraith** [comment]
As a react native developer this is a really strange way of distributing a react native library. My expectation would be that Salesforce would provide a NPM package that can be linked against an existing react native project. If you want to provide a way to generate a sample app that is fine but should not be the only way.

The way this is being distributed now is really counter intuitive. See https://reactnative.dev/docs/native-modules-setup for how it should be done.

**Comment by NadjibSb** [comment]
This is how I integrated Salesforce Mobile SDK in an existing ReactNative app :
### Steps to integrate Salesforce Mobile SDK
1. Clone these dependencies in *package.json* (the react-native 63.4 version is a must), and then run *npm install*:
    ```   
     "dependencies": {
        "react": "17.0.1",
        "react-native": "0.63.4",
        "react-native-force": "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git",
        "create-react-class": "^15.7.0"
      },
      "devDependencies": {
        "@babel/core": "^7.12.9",
        "@babel/runtime": "^7.12.5",
        "@types/jest": "^26.0.18",
        "@types/react": "^17.0.0",
        "@types/react-native": "^0.63.37",
        "@types/react-test-renderer": "^17.0.0",
        "@react-native-community/eslint-config": "^2.0.0",
        "babel-jest": "^26.6.3",
        "eslint": "7.14.0",
        "jest": "^26.6.3",
        "metro-react-native-babel-preset": "^0.64.0",
        "react-test-renderer": "17.0.1"
      },
    ```
2. Create a *mobile_sdk* folder and clone inside the SalesforceMobileSdk-Android repo :
    ```
    cd mobile_sdk
    git clone https://github.com/forcedotcom/SalesforceMobileSDK-Android
    ```
3. Add this dependency in *"/Users/mac/Altius/Projetinterne/ProjetDistributionRN/android/app/build.gradle"*

    ```
   dependencies {
    ...
    implementation project(':libs:SalesforceReact') // From node_modules
    ...
    }
    ```
4. Edit sdk versions in *"/Users/mac/Altius/Projet interne/ProjetDistributionRN/android/build.gradle"*
     ```
        minSdkVersion = 23 
        compileSdkVersion = 30 
        targetSdkVersion = 30 
        ```
5. Add these lines in file *"/Users/mac/Altius/Projet interne/ProjetDistributionRN/android/settings.gradle"*  
    ```
        def libsRootDir = new File( settingsDir, '../mobile_sdk/SalesforceMobileSDK-Android/libs' )
    include ':app'
    
    include ':libs:SalesforceAnalytics'
    project( ':libs:SalesforceAnalytics' ).projectDir = new File( libsRootDir, 'SalesforceAnalytics' )
    
    include ':libs:SalesforceSDK'
    project( ':libs:SalesforceSDK' ).projectDir = new File( libsRootDir, 'SalesforceSDK' )
    
    include ':libs:SmartStore'
    project( ':libs:SmartStore' ).projectDir = new File( libsRootDir, 'SmartStore' )
    
    include ':libs:MobileSync'
    project( ':libs:MobileSync' ).projectDir = new File( libsRootDir, 'MobileSync' )

    include ':libs:SalesforceReact'
    project( ':libs:SalesforceReact' ).projectDir = new File( libsRootDir, 'SalesforceReact' )
    ```

6. Edit MainActivity to extend SalesforceReactActivity in *"/Users/mac/Altius/Projet interne/ProjetDistributionRN/android/app/src/main/java/com/projetdistributionrn/MainActivity.java"*
    ```
    import com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity;

    public class MainActivity extends SalesforceReactActivity {

5. Edit MainApplication, add following lines in *"/Users/mac/Altius/Projet interne/ProjetDistributionRN/android/app/src/main/java/com/projetdistributionrn/MainApplication.java"* : 

     ```
      import com.salesforce.androidsdk.reactnative.app.SalesforceReactSDKManager;
     ```
     - Update getPackages() function :
     ```
          @Override
          protected List<ReactPackage> getPackages() {
             ...
              //add this line
              packages.add(SalesforceReactSDKManager.getInstance().getReactPackage());
              return packages;
            }
      ```
      - Update onCreate() function :
      ```
          @Override
          public void onCreate() {
            ...
            // add this line
            SalesforceReactSDKManager.initReactNative(getApplicationContext(), MainActivity.class);
           ...
      }
      ```

**Comment by wmathurin** [comment]
This issue is more than 3 years old. The code has changed a lot since then. 
Please open a new issue if you think it is still relevant today.

**Comment by djMax** [comment]
This is classic Salesforce. It is stunning that you think that in 2023, the best way for someone to integrate your SDK is to rebuild an app.

**Comment by daraul** [comment]
Are there any tips for bringing the "new" project into the "old" project's version control?
