### ISSUE TITLE
RN 0.57 + release roadmap

### ISSUE THREAD

**Issue by rpander93** [forcedotcom/SalesforceMobileSDK-ReactNative#96]
Hi all,

I have two questions:

1. What are the plans to support react native 0.57?
2. Do you have a roadmap with respect to releases? I see that this repository has 0.56.1 as RN version, but the `forcereact` tool still uses 0.55.4 as version.

Thanks!

**Comment by wmathurin** [comment]
The plan is to support 0.56.1 in Mobile SDK 7.0.
Mobile SDK 7.0 should be released in the coming weeks.
The last version of Mobile SDK released was 6.2 which indeed uses RN 0.55.4.
